"""Ozon FBS slot fines («Отгрузка в нерекомендованный слот», type_id=94).

Persists accrual events by accrual_id and aggregates by unit_number so late
storno (same type_id, positive amount) can close older fines without re-syncing
full history every time.
"""
from __future__ import annotations

import json
import logging
from datetime import date, datetime, timedelta
from decimal import Decimal, InvalidOperation
from typing import Any

from .ozon_fbs import OzonFbsClient
from .repository import ReviewRepository
from .security import decrypt_secret, encrypt_secret, mask_secret

_log = logging.getLogger(__name__)

SLOT_TYPE_ID = 94
SLOT_TYPE_NAME = "DefectFineShipmentDelayRate"
SLOT_TYPE_LABEL = "Отгрузка в нерекомендованный слот"
_EPS = Decimal("0.01")
_SYNC_LOG_KEEP = 300


def ensure_ozon_fbs_fines_tables(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_settings (
                user_id BIGINT PRIMARY KEY,
                client_id TEXT NOT NULL DEFAULT '',
                api_key_encrypted TEXT NOT NULL DEFAULT '',
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_events (
                user_id BIGINT NOT NULL,
                accrual_id BIGINT NOT NULL,
                event_date DATE NOT NULL,
                unit_number TEXT NOT NULL DEFAULT '',
                amount NUMERIC(18, 2) NOT NULL,
                currency TEXT NOT NULL DEFAULT 'RUB',
                accrued_category TEXT NOT NULL DEFAULT '',
                raw_json TEXT NOT NULL DEFAULT '{}',
                synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (user_id, accrual_id)
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_unit "
                "ON ozon_fbs_fines_events(user_id, unit_number, event_date)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_date "
                "ON ozon_fbs_fines_events(user_id, event_date)"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_sync_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                level TEXT NOT NULL DEFAULT 'info',
                message TEXT NOT NULL DEFAULT ''
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_sync_log_user "
                "ON ozon_fbs_fines_sync_log(user_id, id DESC)"
            )
        )


def get_settings(repo: ReviewRepository, *, user_id: int) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted, updated_at
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        return {
            "client_id": "",
            "api_key_masked": "",
            "has_api_key": False,
            "updated_at": None,
        }
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
        "updated_at": row[2],
    }
    enc = str(data.get("api_key_encrypted") or "")
    plain = decrypt_secret(enc) if enc else None
    return {
        "client_id": str(data.get("client_id") or ""),
        "api_key_masked": mask_secret(plain) if plain else "",
        "has_api_key": bool(plain),
        "updated_at": str(data.get("updated_at") or "") or None,
    }


def save_settings(
    repo: ReviewRepository,
    *,
    user_id: int,
    client_id: str | None = None,
    api_key: str | None = None,
) -> dict[str, Any]:
    """Update settings. Empty api_key keeps previous key. None client_id keeps previous."""
    ensure_ozon_fbs_fines_tables(repo)
    current = get_settings(repo, user_id=user_id)
    next_client = (
        str(client_id).strip()
        if client_id is not None
        else str(current.get("client_id") or "")
    )
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                "SELECT api_key_encrypted FROM ozon_fbs_fines_settings WHERE user_id = ?"
            ),
            (int(user_id),),
        ).fetchone()
        prev_enc = ""
        if row is not None:
            prev_enc = str(
                row["api_key_encrypted"] if hasattr(row, "keys") else row[0] or ""
            )
        if api_key is None:
            next_enc = prev_enc
        else:
            clean = str(api_key).strip()
            next_enc = encrypt_secret(clean) if clean else ""
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_settings (user_id, client_id, api_key_encrypted, updated_at)
                VALUES (?, ?, ?, NOW())
                ON CONFLICT (user_id) DO UPDATE SET
                    client_id = EXCLUDED.client_id,
                    api_key_encrypted = EXCLUDED.api_key_encrypted,
                    updated_at = NOW()
                """
            ),
            (int(user_id), next_client, next_enc or ""),
        )
    return get_settings(repo, user_id=user_id)


def _credentials(repo: ReviewRepository, *, user_id: int) -> tuple[str, str]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
    }
    client_id = str(data.get("client_id") or "").strip()
    api_key = decrypt_secret(str(data.get("api_key_encrypted") or "")) or ""
    if not client_id or not api_key:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    return client_id, api_key


def append_sync_log(
    repo: ReviewRepository, *, user_id: int, message: str, level: str = "info"
) -> None:
    ensure_ozon_fbs_fines_tables(repo)
    msg = str(message or "").strip()
    if not msg:
        return
    lvl = str(level or "info").strip().lower() or "info"
    if lvl not in ("info", "warn", "error", "ok"):
        lvl = "info"
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_sync_log (user_id, level, message)
                VALUES (?, ?, ?)
                """
            ),
            (int(user_id), lvl, msg[:2000]),
        )
        rows = conn.execute(
            repo._sql(
                """
                SELECT id FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), int(_SYNC_LOG_KEEP)),
        ).fetchall()
        keep_ids = [
            int(r["id"] if hasattr(r, "keys") else r[0])
            for r in rows
        ]
        if keep_ids:
            placeholders = ",".join("?" for _ in keep_ids)
            conn.execute(
                repo._sql(
                    f"""
                    DELETE FROM ozon_fbs_fines_sync_log
                    WHERE user_id = ?
                      AND id NOT IN ({placeholders})
                    """
                ),
                (int(user_id), *keep_ids),
            )


def list_sync_log(
    repo: ReviewRepository, *, user_id: int, limit: int = 100
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    lim = max(1, min(int(limit or 100), 300))
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT id, created_at, level, message
                FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), lim),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "id": row[0],
            "created_at": row[1],
            "level": row[2],
            "message": row[3],
        }
        out.append(
            {
                "id": int(d.get("id") or 0),
                "created_at": str(d.get("created_at") or ""),
                "level": str(d.get("level") or "info"),
                "message": str(d.get("message") or ""),
            }
        )
    out.reverse()
    return out


def _parse_amount(value: Any) -> Decimal:
    if isinstance(value, dict):
        value = value.get("amount")
    try:
        return Decimal(str(value or "0").replace(",", ".").strip() or "0")
    except (InvalidOperation, ValueError):
        return Decimal("0")


def extract_slot_fees(accrual: dict[str, Any]) -> list[Decimal]:
    """Return amounts for type_id=94 found in one accrual (usually one)."""
    amounts: list[Decimal] = []
    seen: set[tuple[str, str]] = set()

    def add(tid: Any, accrued: Any) -> None:
        try:
            type_id = int(tid)
        except (TypeError, ValueError):
            return
        if type_id != SLOT_TYPE_ID:
            return
        amt = _parse_amount(accrued)
        key = (str(type_id), str(amt))
        if key in seen:
            return
        seen.add(key)
        amounts.append(amt)

    nif = accrual.get("non_item_fee")
    if isinstance(nif, dict):
        if nif.get("type_id") is not None:
            add(nif.get("type_id"), nif.get("accrued"))
        for fee in nif.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    item_fees = accrual.get("item_fees") or {}
    if isinstance(item_fees, dict):
        for block in item_fees.get("fees") or []:
            if not isinstance(block, dict):
                continue
            for fee in block.get("fees") or []:
                if isinstance(fee, dict):
                    add(fee.get("type_id"), fee.get("accrued"))

    cf = accrual.get("container_fees")
    if isinstance(cf, dict):
        if cf.get("type_id") is not None:
            add(cf.get("type_id"), cf.get("accrued"))
        for fee in cf.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    return amounts


def upsert_event(
    repo: ReviewRepository,
    *,
    user_id: int,
    accrual_id: int,
    event_date: date,
    unit_number: str,
    amount: Decimal,
    currency: str,
    accrued_category: str,
    raw: dict[str, Any],
) -> bool:
    """Insert or update event. Returns True if newly inserted."""
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        existing = conn.execute(
            repo._sql(
                """
                SELECT 1 FROM ozon_fbs_fines_events
                WHERE user_id = ? AND accrual_id = ?
                """
            ),
            (int(user_id), int(accrual_id)),
        ).fetchone()
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_events (
                    user_id, accrual_id, event_date, unit_number, amount,
                    currency, accrued_category, raw_json, synced_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())
                ON CONFLICT (user_id, accrual_id) DO UPDATE SET
                    event_date = EXCLUDED.event_date,
                    unit_number = EXCLUDED.unit_number,
                    amount = EXCLUDED.amount,
                    currency = EXCLUDED.currency,
                    accrued_category = EXCLUDED.accrued_category,
                    raw_json = EXCLUDED.raw_json,
                    synced_at = NOW()
                """
            ),
            (
                int(user_id),
                int(accrual_id),
                event_date.isoformat(),
                str(unit_number or "").strip(),
                str(amount),
                str(currency or "RUB")[:8],
                str(accrued_category or "")[:64],
                json.dumps(raw, ensure_ascii=False)[:20000],
            ),
        )
    return existing is None


def _fetch_day_accruals(client: OzonFbsClient, day: date, *, max_pages: int = 200) -> list[dict[str, Any]]:
    all_rows: list[dict[str, Any]] = []
    last_id: str | None = None
    for _ in range(max_pages):
        body: dict[str, Any] = {"date": day.isoformat()}
        if last_id:
            body["last_id"] = last_id
        data = client.post_json("/v1/finance/accrual/by-day", body)
        chunk = data.get("accruals") if isinstance(data, dict) else None
        if not isinstance(chunk, list) or not chunk:
            break
        for item in chunk:
            if isinstance(item, dict):
                all_rows.append(item)
        new_last = str(data.get("last_id") or "") if isinstance(data, dict) else ""
        if not new_last or new_last == last_id or len(chunk) < 1000:
            if len(chunk) < 1000:
                break
            if not new_last or new_last == last_id:
                break
        last_id = new_last
    return all_rows


def sync_range(
    repo: ReviewRepository,
    *,
    user_id: int,
    date_from: date,
    date_to: date,
) -> dict[str, Any]:
    if date_to < date_from:
        raise ValueError("Дата «по» не может быть раньше даты «с»")
    if (date_to - date_from).days > 92:
        raise ValueError("Интервал синхронизации не больше 92 дней за раз")

    client_id, api_key = _credentials(repo, user_id=user_id)
    client = OzonFbsClient(client_id=client_id, api_key=api_key, timeout=90)

    append_sync_log(
        repo,
        user_id=user_id,
        message=f"Синхронизация {date_from.isoformat()} … {date_to.isoformat()}",
        level="info",
    )

    days_done = 0
    inserted = 0
    updated = 0
    slot_hits = 0
    errors: list[str] = []

    day = date_from
    while day <= date_to:
        try:
            accruals = _fetch_day_accruals(client, day)
            day_new = 0
            day_hits = 0
            for acc in accruals:
                amounts = extract_slot_fees(acc)
                if not amounts:
                    continue
                try:
                    accrual_id = int(acc.get("accrual_id") or 0)
                except (TypeError, ValueError):
                    continue
                if accrual_id <= 0:
                    continue
                unit = str(acc.get("unit_number") or "").strip()
                currency = "RUB"
                total = acc.get("total_amount")
                if isinstance(total, dict):
                    currency = str(total.get("currency") or "RUB")
                category = str(acc.get("accrued_category") or "")
                # One accrual can theoretically carry multiple fee lines; store net of type 94.
                amount = sum(amounts, Decimal("0"))
                is_new = upsert_event(
                    repo,
                    user_id=user_id,
                    accrual_id=accrual_id,
                    event_date=day,
                    unit_number=unit,
                    amount=amount,
                    currency=currency,
                    accrued_category=category,
                    raw=acc,
                )
                day_hits += 1
                slot_hits += 1
                if is_new:
                    inserted += 1
                    day_new += 1
                else:
                    updated += 1
            days_done += 1
            append_sync_log(
                repo,
                user_id=user_id,
                message=(
                    f"{day.isoformat()}: начислений {len(accruals)}, "
                    f"штраф/сторно {day_hits}, новых {day_new}"
                ),
                level="ok" if day_hits else "info",
            )
        except Exception as exc:
            msg = f"{day.isoformat()}: ошибка — {exc}"
            _log.warning("ozon fines sync day failed user=%s day=%s err=%s", user_id, day, exc)
            errors.append(msg)
            append_sync_log(repo, user_id=user_id, message=msg, level="error")
        day += timedelta(days=1)

    summary = (
        f"Готово: дней {days_done}, событий слота {slot_hits}, "
        f"новых {inserted}, обновлено {updated}"
    )
    if errors:
        summary += f", ошибок {len(errors)}"
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="error" if errors and not slot_hits else "ok",
    )
    return {
        "ok": True,
        "days_done": days_done,
        "slot_events": slot_hits,
        "inserted": inserted,
        "updated": updated,
        "errors": errors,
        "summary": summary,
    }


def _status_for_net(net: Decimal) -> str:
    if abs(net) <= _EPS:
        return "closed"
    if net < 0:
        return "open"
    return "over"


def list_units(
    repo: ReviewRepository,
    *,
    user_id: int,
    status: str = "open",
    fine_date_from: date | None = None,
    fine_date_to: date | None = None,
    limit: int = 500,
) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    status_key = str(status or "open").strip().lower()
    if status_key not in ("open", "closed", "all", "over"):
        status_key = "open"
    lim = max(1, min(int(limit or 500), 2000))

    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT
                    unit_number,
                    SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS fine_sum,
                    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS storno_sum,
                    SUM(amount) AS net_sum,
                    MIN(CASE WHEN amount < 0 THEN event_date END) AS first_fine_date,
                    MAX(CASE WHEN amount > 0 THEN event_date END) AS last_storno_date,
                    COUNT(*) AS event_count
                FROM ozon_fbs_fines_events
                WHERE user_id = ?
                  AND unit_number <> ''
                GROUP BY unit_number
                ORDER BY MIN(CASE WHEN amount < 0 THEN event_date END) DESC NULLS LAST,
                         unit_number
                """
            ),
            (int(user_id),),
        ).fetchall()

    units: list[dict[str, Any]] = []
    summary = {
        "open_count": 0,
        "closed_count": 0,
        "over_count": 0,
        "open_remainder": "0.00",
    }
    open_rem = Decimal("0")

    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "unit_number": row[0],
            "fine_sum": row[1],
            "storno_sum": row[2],
            "net_sum": row[3],
            "first_fine_date": row[4],
            "last_storno_date": row[5],
            "event_count": row[6],
        }
        unit = str(d.get("unit_number") or "").strip()
        if not unit:
            continue
        fine_sum = _parse_amount(d.get("fine_sum"))
        storno_sum = _parse_amount(d.get("storno_sum"))
        net = _parse_amount(d.get("net_sum"))
        st = _status_for_net(net)
        first_fine = d.get("first_fine_date")
        first_fine_s = str(first_fine)[:10] if first_fine else ""
        last_storno = d.get("last_storno_date")
        last_storno_s = str(last_storno)[:10] if last_storno else ""

        if st == "open":
            summary["open_count"] += 1
            open_rem += net
        elif st == "closed":
            summary["closed_count"] += 1
        else:
            summary["over_count"] += 1

        if fine_date_from and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) < fine_date_from:
                    continue
            except ValueError:
                pass
        if fine_date_to and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) > fine_date_to:
                    continue
            except ValueError:
                pass

        if status_key != "all" and st != status_key:
            continue

        units.append(
            {
                "unit_number": unit,
                "fine_sum": f"{fine_sum:.2f}",
                "storno_sum": f"{storno_sum:.2f}",
                "net_sum": f"{net:.2f}",
                "status": st,
                "first_fine_date": first_fine_s or None,
                "last_storno_date": last_storno_s or None,
                "event_count": int(d.get("event_count") or 0),
            }
        )

    summary["open_remainder"] = f"{open_rem:.2f}"
    return {"units": units[:lim], "summary": summary, "total": len(units)}


def list_unit_events(
    repo: ReviewRepository, *, user_id: int, unit_number: str
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    unit = str(unit_number or "").strip()
    if not unit:
        return []
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT accrual_id, event_date, amount, currency, accrued_category, synced_at
                FROM ozon_fbs_fines_events
                WHERE user_id = ? AND unit_number = ?
                ORDER BY event_date ASC, accrual_id ASC
                """
            ),
            (int(user_id), unit),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "accrual_id": row[0],
            "event_date": row[1],
            "amount": row[2],
            "currency": row[3],
            "accrued_category": row[4],
            "synced_at": row[5],
        }
        amt = _parse_amount(d.get("amount"))
        out.append(
            {
                "accrual_id": int(d.get("accrual_id") or 0),
                "event_date": str(d.get("event_date") or "")[:10],
                "amount": f"{amt:.2f}",
                "currency": str(d.get("currency") or "RUB"),
                "accrued_category": str(d.get("accrued_category") or ""),
                "kind": "storno" if amt > 0 else "fine",
                "synced_at": str(d.get("synced_at") or ""),
            }
        )
    return out


def default_sync_dates() -> tuple[date, date]:
    today = date.today()
    return today - timedelta(days=14), today
