"""Ozon FBS slot fines («Отгрузка в нерекомендованный слот», type_id=94).

Persists accrual events by accrual_id and aggregates by unit_number so late
storno (same type_id, positive amount) can close older fines without re-syncing
full history every time.
"""
from __future__ import annotations

import json
import logging
import re
import threading
from datetime import date, datetime, timedelta
from decimal import Decimal, InvalidOperation
from typing import Any

from .ozon_fbs import OzonFbsClient
from .repository import ReviewRepository
from .security import decrypt_secret, encrypt_secret, mask_secret

_log = logging.getLogger(__name__)

SLOT_TYPE_ID = 94
SLOT_TYPE_NAME = "DefectFineShipmentDelayRate"
SLOT_TYPE_LABEL = "Отгрузка в нерекомендованный слот"
_EPS = Decimal("0.01")
_SYNC_LOG_KEEP = 300

# In-memory job state — nginx ~60s proxy timeout cannot wait for multi-day
# accrual sync; POST returns immediately and UI polls /sync/status.
_fines_sync_lock = threading.Lock()
_fines_sync_state: dict[int, dict[str, Any]] = {}


def _is_fatal_ozon_auth_error(exc: BaseException) -> bool:
    """True when further day retries are pointless (bad/deactivated key)."""
    msg = str(exc or "").lower()
    if "api-key is deactivated" in msg or "api-key is missing a required role" in msg:
        return True
    if "ozon http 403" in msg and ("deactivated" in msg or "required role" in msg):
        return True
    return False


def ensure_ozon_fbs_fines_tables(repo: ReviewRepository) -> None:
    """Create fines tables; ignore concurrent CREATE type races on Postgres."""
    try:
        _ensure_ozon_fbs_fines_tables_inner(repo)
    except Exception as exc:
        # Concurrent CREATE TABLE IF NOT EXISTS can still race on pg_type.
        text = str(exc)
        if (
            "pg_type_typname_nsp_index" in text
            or "already exists" in text.lower()
            or type(exc).__name__ == "UniqueViolation"
        ):
            _log.info("ozon fines tables ensure race ignored: %s", text[:200])
            return
        raise


def _ensure_ozon_fbs_fines_tables_inner(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_settings (
                user_id BIGINT PRIMARY KEY,
                client_id TEXT NOT NULL DEFAULT '',
                api_key_encrypted TEXT NOT NULL DEFAULT '',
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_events (
                user_id BIGINT NOT NULL,
                accrual_id BIGINT NOT NULL,
                event_date DATE NOT NULL,
                unit_number TEXT NOT NULL DEFAULT '',
                amount NUMERIC(18, 2) NOT NULL,
                currency TEXT NOT NULL DEFAULT 'RUB',
                accrued_category TEXT NOT NULL DEFAULT '',
                raw_json TEXT NOT NULL DEFAULT '{}',
                synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (user_id, accrual_id)
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_unit "
                "ON ozon_fbs_fines_events(user_id, unit_number, event_date)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_date "
                "ON ozon_fbs_fines_events(user_id, event_date)"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_sync_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                level TEXT NOT NULL DEFAULT 'info',
                message TEXT NOT NULL DEFAULT ''
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_sync_log_user "
                "ON ozon_fbs_fines_sync_log(user_id, id DESC)"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_log_files (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                filename TEXT NOT NULL DEFAULT '',
                content_b64 TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_log_files_user "
                "ON ozon_fbs_fines_log_files(user_id, id DESC)"
            )
        )
        try:
            conn.execute(
                "ALTER TABLE ozon_fbs_fines_sync_log "
                "ADD COLUMN IF NOT EXISTS attachment_id BIGINT"
            )
        except Exception as exc:
            _log.info("ozon fines sync_log attachment_id column: %s", str(exc)[:160])


def get_settings(repo: ReviewRepository, *, user_id: int) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted, updated_at
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        return {
            "client_id": "",
            "api_key_masked": "",
            "has_api_key": False,
            "updated_at": None,
        }
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
        "updated_at": row[2],
    }
    enc = str(data.get("api_key_encrypted") or "")
    plain = decrypt_secret(enc) if enc else None
    return {
        "client_id": str(data.get("client_id") or ""),
        "api_key_masked": mask_secret(plain) if plain else "",
        "has_api_key": bool(plain),
        "updated_at": str(data.get("updated_at") or "") or None,
    }


def save_settings(
    repo: ReviewRepository,
    *,
    user_id: int,
    client_id: str | None = None,
    api_key: str | None = None,
) -> dict[str, Any]:
    """Update settings. None/blank api_key keeps previous key. None client_id keeps previous."""
    ensure_ozon_fbs_fines_tables(repo)
    current = get_settings(repo, user_id=user_id)
    next_client = (
        str(client_id).strip()
        if client_id is not None
        else str(current.get("client_id") or "")
    )
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                "SELECT api_key_encrypted FROM ozon_fbs_fines_settings WHERE user_id = ?"
            ),
            (int(user_id),),
        ).fetchone()
        prev_enc = ""
        if row is not None:
            prev_enc = str(
                row["api_key_encrypted"] if hasattr(row, "keys") else row[0] or ""
            )
        if api_key is None or not str(api_key).strip():
            next_enc = prev_enc
        else:
            next_enc = encrypt_secret(str(api_key).strip()) or ""
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_settings (user_id, client_id, api_key_encrypted, updated_at)
                VALUES (?, ?, ?, NOW())
                ON CONFLICT (user_id) DO UPDATE SET
                    client_id = EXCLUDED.client_id,
                    api_key_encrypted = EXCLUDED.api_key_encrypted,
                    updated_at = NOW()
                """
            ),
            (int(user_id), next_client, next_enc or ""),
        )
    return get_settings(repo, user_id=user_id)


def _credentials(repo: ReviewRepository, *, user_id: int) -> tuple[str, str]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
    }
    client_id = str(data.get("client_id") or "").strip()
    api_key = decrypt_secret(str(data.get("api_key_encrypted") or "")) or ""
    if not client_id or not api_key:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    return client_id, api_key


def _store_log_attachment(
    repo: ReviewRepository,
    *,
    user_id: int,
    filename: str,
    file_bytes: bytes,
) -> int | None:
    """Persist residual Excel for sync-log download. Returns attachment id."""
    raw = bytes(file_bytes or b"")
    if not raw:
        return None
    import base64

    name = str(filename or "residual.xlsx").strip() or "residual.xlsx"
    if not name.lower().endswith(".xlsx"):
        name = f"{name}.xlsx"
    b64 = base64.b64encode(raw).decode("ascii")
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_log_files (user_id, filename, content_b64)
                VALUES (?, ?, ?)
                RETURNING id
                """
            ),
            (int(user_id), name[:200], b64),
        ).fetchone()
        # Keep last 40 residual files per user.
        keep = conn.execute(
            repo._sql(
                """
                SELECT id FROM ozon_fbs_fines_log_files
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT 40
                """
            ),
            (int(user_id),),
        ).fetchall()
        keep_ids = [int(r["id"] if hasattr(r, "keys") else r[0]) for r in keep]
        if keep_ids:
            placeholders = ",".join("?" for _ in keep_ids)
            conn.execute(
                repo._sql(
                    f"""
                    DELETE FROM ozon_fbs_fines_log_files
                    WHERE user_id = ?
                      AND id NOT IN ({placeholders})
                    """
                ),
                (int(user_id), *keep_ids),
            )
    if row is None:
        return None
    return int(row["id"] if hasattr(row, "keys") else row[0])


def get_log_attachment(
    repo: ReviewRepository, *, user_id: int, attachment_id: int
) -> tuple[str, bytes] | None:
    ensure_ozon_fbs_fines_tables(repo)
    import base64

    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT filename, content_b64
                FROM ozon_fbs_fines_log_files
                WHERE user_id = ? AND id = ?
                """
            ),
            (int(user_id), int(attachment_id)),
        ).fetchone()
    if row is None:
        return None
    d = dict(row) if hasattr(row, "keys") else {
        "filename": row[0],
        "content_b64": row[1],
    }
    name = str(d.get("filename") or "residual.xlsx").strip() or "residual.xlsx"
    try:
        raw = base64.b64decode(str(d.get("content_b64") or ""), validate=False)
    except Exception:
        return None
    if not raw:
        return None
    return name, raw


def append_sync_log(
    repo: ReviewRepository,
    *,
    user_id: int,
    message: str,
    level: str = "info",
    attachment_id: int | None = None,
) -> int | None:
    ensure_ozon_fbs_fines_tables(repo)
    msg = str(message or "").strip()
    if not msg:
        return None
    lvl = str(level or "info").strip().lower() or "info"
    if lvl not in ("info", "warn", "error", "ok"):
        lvl = "info"
    aid = int(attachment_id) if attachment_id else None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_sync_log (user_id, level, message, attachment_id)
                VALUES (?, ?, ?, ?)
                RETURNING id
                """
            ),
            (int(user_id), lvl, msg[:2000], aid),
        ).fetchone()
        rows = conn.execute(
            repo._sql(
                """
                SELECT id FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), int(_SYNC_LOG_KEEP)),
        ).fetchall()
        keep_ids = [
            int(r["id"] if hasattr(r, "keys") else r[0])
            for r in rows
        ]
        if keep_ids:
            placeholders = ",".join("?" for _ in keep_ids)
            conn.execute(
                repo._sql(
                    f"""
                    DELETE FROM ozon_fbs_fines_sync_log
                    WHERE user_id = ?
                      AND id NOT IN ({placeholders})
                    """
                ),
                (int(user_id), *keep_ids),
            )
    if row is None:
        return None
    return int(row["id"] if hasattr(row, "keys") else row[0])


def list_sync_log(
    repo: ReviewRepository, *, user_id: int, limit: int = 100
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    lim = max(1, min(int(limit or 100), 300))
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT id, created_at, level, message, attachment_id
                FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), lim),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "id": row[0],
            "created_at": row[1],
            "level": row[2],
            "message": row[3],
            "attachment_id": row[4] if len(row) > 4 else None,
        }
        att = d.get("attachment_id")
        try:
            att_i = int(att) if att is not None else None
        except (TypeError, ValueError):
            att_i = None
        item = {
            "id": int(d.get("id") or 0),
            "created_at": str(d.get("created_at") or ""),
            "level": str(d.get("level") or "info"),
            "message": str(d.get("message") or ""),
        }
        if att_i:
            item["attachment_id"] = att_i
            item["download_url"] = f"/api/ozon-fbs/fines/sync-log/file/{att_i}"
        out.append(item)
    out.reverse()
    return out


def _parse_amount(value: Any) -> Decimal:
    if isinstance(value, dict):
        value = value.get("amount")
    try:
        return Decimal(str(value or "0").replace(",", ".").strip() or "0")
    except (InvalidOperation, ValueError):
        return Decimal("0")


def extract_slot_fees(accrual: dict[str, Any]) -> list[Decimal]:
    """Return amounts for type_id=94 found in one accrual (usually one)."""
    amounts: list[Decimal] = []
    seen: set[tuple[str, str]] = set()

    def add(tid: Any, accrued: Any) -> None:
        try:
            type_id = int(tid)
        except (TypeError, ValueError):
            return
        if type_id != SLOT_TYPE_ID:
            return
        amt = _parse_amount(accrued)
        key = (str(type_id), str(amt))
        if key in seen:
            return
        seen.add(key)
        amounts.append(amt)

    nif = accrual.get("non_item_fee")
    if isinstance(nif, dict):
        if nif.get("type_id") is not None:
            add(nif.get("type_id"), nif.get("accrued"))
        for fee in nif.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    item_fees = accrual.get("item_fees") or {}
    if isinstance(item_fees, dict):
        for block in item_fees.get("fees") or []:
            if not isinstance(block, dict):
                continue
            for fee in block.get("fees") or []:
                if isinstance(fee, dict):
                    add(fee.get("type_id"), fee.get("accrued"))

    cf = accrual.get("container_fees")
    if isinstance(cf, dict):
        if cf.get("type_id") is not None:
            add(cf.get("type_id"), cf.get("accrued"))
        for fee in cf.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    return amounts


def upsert_event(
    repo: ReviewRepository,
    *,
    user_id: int,
    accrual_id: int,
    event_date: date,
    unit_number: str,
    amount: Decimal,
    currency: str,
    accrued_category: str,
    raw: dict[str, Any],
) -> bool:
    """Insert or update event. Returns True if newly inserted."""
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        existing = conn.execute(
            repo._sql(
                """
                SELECT 1 FROM ozon_fbs_fines_events
                WHERE user_id = ? AND accrual_id = ?
                """
            ),
            (int(user_id), int(accrual_id)),
        ).fetchone()
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_events (
                    user_id, accrual_id, event_date, unit_number, amount,
                    currency, accrued_category, raw_json, synced_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())
                ON CONFLICT (user_id, accrual_id) DO UPDATE SET
                    event_date = EXCLUDED.event_date,
                    unit_number = EXCLUDED.unit_number,
                    amount = EXCLUDED.amount,
                    currency = EXCLUDED.currency,
                    accrued_category = EXCLUDED.accrued_category,
                    raw_json = EXCLUDED.raw_json,
                    synced_at = NOW()
                """
            ),
            (
                int(user_id),
                int(accrual_id),
                event_date.isoformat(),
                str(unit_number or "").strip(),
                str(amount),
                str(currency or "RUB")[:8],
                str(accrued_category or "")[:64],
                json.dumps(raw, ensure_ascii=False)[:20000],
            ),
        )
    return existing is None


def _fetch_day_accruals(client: OzonFbsClient, day: date, *, max_pages: int = 200) -> list[dict[str, Any]]:
    all_rows: list[dict[str, Any]] = []
    seen_ids: set[int] = set()
    last_id: str | None = None
    for _ in range(max_pages):
        body: dict[str, Any] = {"date": day.isoformat()}
        if last_id:
            body["last_id"] = last_id
        data = client.post_json("/v1/finance/accrual/by-day", body)
        chunk = data.get("accruals") if isinstance(data, dict) else None
        if not isinstance(chunk, list) or not chunk:
            break
        new_count = 0
        for item in chunk:
            if not isinstance(item, dict):
                continue
            try:
                aid = int(item.get("accrual_id") or 0)
            except (TypeError, ValueError):
                aid = 0
            if aid and aid in seen_ids:
                continue
            if aid:
                seen_ids.add(aid)
            all_rows.append(item)
            new_count += 1
        new_last = str(data.get("last_id") or "") if isinstance(data, dict) else ""
        # Stop when cursor does not advance or page brought no new accrual_ids.
        if not new_last or new_last == last_id or new_count == 0:
            break
        last_id = new_last
    return all_rows


def sync_range(
    repo: ReviewRepository,
    *,
    user_id: int,
    date_from: date,
    date_to: date,
) -> dict[str, Any]:
    if date_to < date_from:
        raise ValueError("Дата «по» не может быть раньше даты «с»")
    if (date_to - date_from).days > 92:
        raise ValueError("Интервал синхронизации не больше 92 дней за раз")

    client_id, api_key = _credentials(repo, user_id=user_id)
    client = OzonFbsClient(client_id=client_id, api_key=api_key, timeout=90)

    append_sync_log(
        repo,
        user_id=user_id,
        message=f"Синхронизация {date_from.isoformat()} … {date_to.isoformat()}",
        level="info",
    )

    days_done = 0
    inserted = 0
    updated = 0
    slot_hits = 0
    errors: list[str] = []

    day = date_from
    while day <= date_to:
        try:
            accruals = _fetch_day_accruals(client, day)
            day_new = 0
            day_hits = 0
            for acc in accruals:
                amounts = extract_slot_fees(acc)
                if not amounts:
                    continue
                try:
                    accrual_id = int(acc.get("accrual_id") or 0)
                except (TypeError, ValueError):
                    continue
                if accrual_id <= 0:
                    continue
                unit = str(acc.get("unit_number") or "").strip()
                currency = "RUB"
                total = acc.get("total_amount")
                if isinstance(total, dict):
                    currency = str(total.get("currency") or "RUB")
                category = str(acc.get("accrued_category") or "")
                # One accrual can theoretically carry multiple fee lines; store net of type 94.
                amount = sum(amounts, Decimal("0"))
                is_new = upsert_event(
                    repo,
                    user_id=user_id,
                    accrual_id=accrual_id,
                    event_date=day,
                    unit_number=unit,
                    amount=amount,
                    currency=currency,
                    accrued_category=category,
                    raw=acc,
                )
                day_hits += 1
                slot_hits += 1
                if is_new:
                    inserted += 1
                    day_new += 1
                else:
                    updated += 1
            days_done += 1
            append_sync_log(
                repo,
                user_id=user_id,
                message=(
                    f"{day.isoformat()}: начислений {len(accruals)}, "
                    f"штраф/сторно {day_hits}, новых {day_new}"
                ),
                level="ok" if day_hits else "info",
            )
        except Exception as exc:
            msg = f"{day.isoformat()}: ошибка — {exc}"
            _log.warning("ozon fines sync day failed user=%s day=%s err=%s", user_id, day, exc)
            errors.append(msg)
            append_sync_log(repo, user_id=user_id, message=msg, level="error")
            if _is_fatal_ozon_auth_error(exc):
                abort_msg = (
                    "Синхронизация остановлена: ключ Ozon отклонён (403). "
                    "Проверьте Api-Key в настройках штрафов."
                )
                append_sync_log(repo, user_id=user_id, message=abort_msg, level="error")
                errors.append(abort_msg)
                break
        day += timedelta(days=1)

    summary = (
        f"Готово: дней {days_done}, событий слота {slot_hits}, "
        f"новых {inserted}, обновлено {updated}"
    )
    if errors:
        summary += f", ошибок {len(errors)}"
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="error" if errors and not slot_hits else "ok",
    )
    return {
        "ok": True,
        "days_done": days_done,
        "slot_events": slot_hits,
        "inserted": inserted,
        "updated": updated,
        "errors": errors,
        "summary": summary,
    }


def get_sync_status(*, user_id: int) -> dict[str, Any]:
    with _fines_sync_lock:
        st = dict(_fines_sync_state.get(int(user_id)) or {})
    return {
        "in_progress": bool(st.get("in_progress")),
        "job": str(st.get("job") or ("sync" if st.get("in_progress") else "")),
        "message": str(st.get("message") or ""),
        "error": str(st.get("error") or ""),
        "date_from": str(st.get("date_from") or ""),
        "date_to": str(st.get("date_to") or ""),
        "result": st.get("result"),
    }


def start_sync_thread(
    repo: ReviewRepository,
    *,
    user_id: int,
    date_from: date,
    date_to: date,
) -> tuple[bool, str, dict[str, Any]]:
    """Start background fines sync. Returns (ok, message, status_payload)."""
    if date_to < date_from:
        raise ValueError("Дата «по» не может быть раньше даты «с»")
    if (date_to - date_from).days > 92:
        raise ValueError("Интервал синхронизации не больше 92 дней за раз")
    # Validate credentials early so the HTTP response can surface the error.
    _credentials(repo, user_id=user_id)

    uid = int(user_id)
    with _fines_sync_lock:
        cur = _fines_sync_state.get(uid) or {}
        if cur.get("in_progress"):
            status = {
                "in_progress": True,
                "job": str(cur.get("job") or "sync"),
                "message": str(cur.get("message") or ""),
                "error": str(cur.get("error") or ""),
                "date_from": str(cur.get("date_from") or ""),
                "date_to": str(cur.get("date_to") or ""),
                "result": cur.get("result"),
            }
            return False, "Синхронизация или импорт сторно уже запущены", status
        _fines_sync_state[uid] = {
            "in_progress": True,
            "job": "sync",
            "message": f"Запуск {date_from.isoformat()} … {date_to.isoformat()}",
            "error": "",
            "date_from": date_from.isoformat(),
            "date_to": date_to.isoformat(),
            "result": None,
        }

    try:
        append_sync_log(
            repo,
            user_id=uid,
            message=(
                f"Фоновая синхронизация запущена "
                f"{date_from.isoformat()} … {date_to.isoformat()}"
            ),
            level="info",
        )
    except Exception:
        _log.exception("ozon fines sync start log failed user=%s", uid)

    def _run() -> None:
        try:
            result = sync_range(
                repo,
                user_id=uid,
                date_from=date_from,
                date_to=date_to,
            )
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "job": "sync",
                    "message": str(result.get("summary") or "Готово"),
                    "error": "",
                    "date_from": date_from.isoformat(),
                    "date_to": date_to.isoformat(),
                    "result": result,
                }
        except Exception as exc:
            _log.exception("ozon fines background sync failed user=%s", uid)
            try:
                append_sync_log(
                    repo,
                    user_id=uid,
                    message=f"Сбой синхронизации: {exc}",
                    level="error",
                )
            except Exception:
                pass
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "job": "sync",
                    "message": str(exc),
                    "error": str(exc),
                    "date_from": date_from.isoformat(),
                    "date_to": date_to.isoformat(),
                    "result": None,
                }

    threading.Thread(
        target=_run,
        name=f"ozon-fines-sync-{uid}",
        daemon=True,
    ).start()
    return True, "Синхронизация запущена", get_sync_status(user_id=uid)


def _status_for_net(net: Decimal) -> str:
    if abs(net) <= _EPS:
        return "closed"
    if net < 0:
        return "open"
    return "over"


def list_units(
    repo: ReviewRepository,
    *,
    user_id: int,
    status: str = "open",
    fine_date_from: date | None = None,
    fine_date_to: date | None = None,
    limit: int = 500,
) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    status_key = str(status or "open").strip().lower()
    if status_key not in ("open", "closed", "all", "over"):
        status_key = "open"
    lim = max(1, min(int(limit or 500), 2000))

    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT
                    unit_number,
                    SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS fine_sum,
                    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS storno_sum,
                    SUM(amount) AS net_sum,
                    MIN(CASE WHEN amount < 0 THEN event_date END) AS first_fine_date,
                    MAX(CASE WHEN amount > 0 THEN event_date END) AS last_storno_date,
                    COUNT(*) AS event_count
                FROM ozon_fbs_fines_events
                WHERE user_id = ?
                  AND unit_number <> ''
                GROUP BY unit_number
                ORDER BY MIN(CASE WHEN amount < 0 THEN event_date END) DESC NULLS LAST,
                         unit_number
                """
            ),
            (int(user_id),),
        ).fetchall()

    units: list[dict[str, Any]] = []
    summary = {
        "open_count": 0,
        "closed_count": 0,
        "over_count": 0,
        "open_remainder": "0.00",
    }
    open_rem = Decimal("0")

    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "unit_number": row[0],
            "fine_sum": row[1],
            "storno_sum": row[2],
            "net_sum": row[3],
            "first_fine_date": row[4],
            "last_storno_date": row[5],
            "event_count": row[6],
        }
        unit = str(d.get("unit_number") or "").strip()
        if not unit:
            continue
        fine_sum = _parse_amount(d.get("fine_sum"))
        storno_sum = _parse_amount(d.get("storno_sum"))
        net = _parse_amount(d.get("net_sum"))
        st = _status_for_net(net)
        first_fine = d.get("first_fine_date")
        first_fine_s = str(first_fine)[:10] if first_fine else ""
        last_storno = d.get("last_storno_date")
        last_storno_s = str(last_storno)[:10] if last_storno else ""

        if st == "open":
            summary["open_count"] += 1
            open_rem += net
        elif st == "closed":
            summary["closed_count"] += 1
        else:
            summary["over_count"] += 1

        if fine_date_from and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) < fine_date_from:
                    continue
            except ValueError:
                pass
        if fine_date_to and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) > fine_date_to:
                    continue
            except ValueError:
                pass

        if status_key != "all" and st != status_key:
            continue

        units.append(
            {
                "unit_number": unit,
                "fine_sum": f"{fine_sum:.2f}",
                "storno_sum": f"{storno_sum:.2f}",
                "net_sum": f"{net:.2f}",
                "status": st,
                "first_fine_date": first_fine_s or None,
                "last_storno_date": last_storno_s or None,
                "event_count": int(d.get("event_count") or 0),
            }
        )

    summary["open_remainder"] = f"{open_rem:.2f}"
    return {"units": units[:lim], "summary": summary, "total": len(units)}


def list_unit_events(
    repo: ReviewRepository, *, user_id: int, unit_number: str
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    unit = str(unit_number or "").strip()
    if not unit:
        return []
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT accrual_id, event_date, amount, currency, accrued_category, synced_at
                FROM ozon_fbs_fines_events
                WHERE user_id = ? AND unit_number = ?
                ORDER BY event_date ASC, accrual_id ASC
                """
            ),
            (int(user_id), unit),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "accrual_id": row[0],
            "event_date": row[1],
            "amount": row[2],
            "currency": row[3],
            "accrued_category": row[4],
            "synced_at": row[5],
        }
        amt = _parse_amount(d.get("amount"))
        out.append(
            {
                "accrual_id": int(d.get("accrual_id") or 0),
                "event_date": str(d.get("event_date") or "")[:10],
                "amount": f"{amt:.2f}",
                "currency": str(d.get("currency") or "RUB"),
                "accrued_category": str(d.get("accrued_category") or ""),
                "kind": "storno" if amt > 0 else "fine",
                "synced_at": str(d.get("synced_at") or ""),
            }
        )
    return out


def default_sync_dates() -> tuple[date, date]:
    today = date.today()
    return today - timedelta(days=14), today


# --- Excel «Отчёт по начислениям» import ---------------------------------

EXCEL_FINE_TYPE = "Отгрузка в нерекомендованный слот"
EXCEL_STORNO_TYPE = "Отгрузка в нерекомендованный слот - отмена начисления"


def _excel_synthetic_accrual_id(
    *, unit_number: str, event_date: date, amount: Decimal, kind: str
) -> int:
    """Stable negative id so Excel rows never collide with Ozon API accrual_id."""
    import hashlib

    key = (
        f"excel|{str(unit_number).strip()}|{event_date.isoformat()}|"
        f"{amount:.2f}|{kind}"
    )
    digest = hashlib.sha1(key.encode("utf-8")).digest()
    n = int.from_bytes(digest[:8], "big") & 0x7FFFFFFFFFFFFFFF
    return -n if n else -1


def _parse_excel_date(value: Any) -> date | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = str(value).strip()
    if not text:
        return None
    # 18.09.2026 or 2026-09-18
    for fmt in ("%d.%m.%Y", "%Y-%m-%d", "%d.%m.%y"):
        try:
            return datetime.strptime(text[:10], fmt).date()
        except ValueError:
            continue
    try:
        return date.fromisoformat(text[:10])
    except ValueError:
        return None


def parse_accruals_report_rows(file_bytes: bytes) -> list[dict[str, Any]]:
    """Extract only slot fine/storno rows from Ozon accruals Excel report."""
    import io

    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise ValueError("Для импорта нужен пакет openpyxl") from exc

    wb = load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
    try:
        ws = wb[wb.sheetnames[0]]
        header_idx: dict[str, int] = {}
        out: list[dict[str, Any]] = []
        type_i = id_i = date_i = sum_i = -1
        for row in ws.iter_rows(values_only=True):
            if not row:
                continue
            if not header_idx:
                cells = [str(c or "").strip() for c in row]
                if "Тип начисления" in cells and "ID начисления" in cells:
                    header_idx = {name: idx for idx, name in enumerate(cells) if name}
                    required = (
                        "Тип начисления",
                        "ID начисления",
                        "Дата начисления",
                        "Сумма итого, руб.",
                    )
                    missing = [name for name in required if name not in header_idx]
                    if missing:
                        raise ValueError(
                            "В файле нет нужных колонок (ID / Дата / Тип / Сумма)"
                        )
                    type_i = header_idx["Тип начисления"]
                    id_i = header_idx["ID начисления"]
                    date_i = header_idx["Дата начисления"]
                    sum_i = header_idx["Сумма итого, руб."]
                continue
            if max(type_i, id_i, date_i, sum_i) >= len(row):
                continue
            type_label = str(row[type_i] or "").strip()
            if type_label == EXCEL_FINE_TYPE:
                kind = "fine"
            elif type_label == EXCEL_STORNO_TYPE:
                kind = "storno"
            else:
                continue
            unit = str(row[id_i] or "").strip()
            if not unit:
                continue
            event_date = _parse_excel_date(row[date_i])
            if event_date is None:
                continue
            amount = _parse_amount(row[sum_i])
            if isinstance(row[sum_i], float):
                amount = Decimal(str(round(float(row[sum_i]), 2)))
            try:
                amount = amount.quantize(Decimal("0.01"))
            except InvalidOperation:
                continue
            if abs(amount) <= _EPS:
                continue
            # Normalize sign by kind (report already uses +/- but be safe).
            if kind == "fine" and amount > 0:
                amount = -amount
            if kind == "storno" and amount < 0:
                amount = -amount
            out.append(
                {
                    "unit_number": unit,
                    "event_date": event_date,
                    "amount": amount,
                    "kind": kind,
                    "type_label": type_label,
                    "raw": {
                        "source": "excel_import",
                        "id_nachisleniya": unit,
                        "type": type_label,
                        "date": event_date.isoformat(),
                        "amount": f"{amount:.2f}",
                    },
                }
            )
        if not header_idx:
            raise ValueError("Не найден заголовок листа «Начисления»")
        return out
    finally:
        wb.close()


def _load_existing_amount_keys(
    repo: ReviewRepository, *, user_id: int, units: set[str]
) -> set[tuple[str, str]]:
    """Set of (unit_number, amount_str) already stored for these units."""
    ensure_ozon_fbs_fines_tables(repo)
    clean = sorted({str(u).strip() for u in units if str(u).strip()})
    if not clean:
        return set()
    out: set[tuple[str, str]] = set()
    # Chunk IN lists to keep query size bounded.
    with repo._connect() as conn:
        for i in range(0, len(clean), 500):
            chunk = clean[i : i + 500]
            placeholders = ", ".join(["?"] * len(chunk))
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT unit_number, amount
                    FROM ozon_fbs_fines_events
                    WHERE user_id = ?
                      AND unit_number IN ({placeholders})
                    """
                ),
                (int(user_id), *chunk),
            ).fetchall()
            for row in rows:
                d = dict(row) if hasattr(row, "keys") else {
                    "unit_number": row[0],
                    "amount": row[1],
                }
                unit = str(d.get("unit_number") or "").strip()
                amt = _parse_amount(d.get("amount")).quantize(Decimal("0.01"))
                out.add((unit, f"{amt:.2f}"))
    return out


def import_accruals_report(
    repo: ReviewRepository,
    *,
    user_id: int,
    file_bytes: bytes,
    filename: str = "",
) -> dict[str, Any]:
    """Merge slot fine/storno from Excel without duplicating API sync events.

    Skip when the same unit_number + amount already exists (any date/source).
    New storno against an existing synced fine closes the unit (net≈0 → green).
    """
    rows = parse_accruals_report_rows(file_bytes)
    units = {str(r["unit_number"]) for r in rows}
    existing = _load_existing_amount_keys(repo, user_id=user_id, units=units)

    inserted = 0
    skipped = 0
    fines_new = 0
    storno_new = 0

    for row in rows:
        unit = str(row["unit_number"])
        event_date: date = row["event_date"]
        amount: Decimal = row["amount"]
        kind = str(row["kind"])
        key = (unit, f"{amount:.2f}")
        if key in existing:
            skipped += 1
            continue
        aid = _excel_synthetic_accrual_id(
            unit_number=unit,
            event_date=event_date,
            amount=amount,
            kind=kind,
        )
        is_new = upsert_event(
            repo,
            user_id=user_id,
            accrual_id=aid,
            event_date=event_date,
            unit_number=unit,
            amount=amount,
            currency="RUB",
            accrued_category=str(row.get("type_label") or "")[:64],
            raw=dict(row.get("raw") or {}),
        )
        if is_new:
            inserted += 1
            existing.add(key)
            if kind == "storno":
                storno_new += 1
            else:
                fines_new += 1
        else:
            skipped += 1
            existing.add(key)

    name = str(filename or "отчёт").strip() or "отчёт"
    summary = (
        f"Импорт «{name}»: слот-строк {len(rows)}, "
        f"добавлено {inserted} (штрафов {fines_new}, сторно {storno_new}), "
        f"пропущено как уже есть {skipped}"
    )
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="ok" if inserted or not rows else "warn",
    )
    return {
        "ok": True,
        "rows_slot": len(rows),
        "inserted": inserted,
        "skipped": skipped,
        "fines_new": fines_new,
        "storno_new": storno_new,
        "summary": summary,
    }


# --- Manager storno Excel import (API-verified) ---------------------------

_POSTING_NUM_RE = re.compile(
    r"^\d{5,12}-\d{3,6}-\d{1,4}$"
)
_SHEET_DATE_RE = re.compile(
    r"^(\d{1,2})[.\-/](\d{1,2})(?:[.\-/](\d{2,4}))?\.?$"
)
_RU_MONTH_MAP = {
    "янв": 1,
    "фев": 2,
    "мар": 3,
    "апр": 4,
    "май": 5,
    "мая": 5,
    "июн": 6,
    "июл": 7,
    "авг": 8,
    "сен": 9,
    "окт": 10,
    "ноя": 11,
    "дек": 12,
}


def _looks_like_posting_number(value: Any) -> bool:
    text = str(value or "").strip()
    if not text or " " in text:
        return False
    if _POSTING_NUM_RE.match(text):
        return True
    parts = text.split("-")
    if len(parts) < 3:
        return False
    return all(p.isdigit() for p in parts[:3])


def _parse_sheet_name_date(name: str, *, default_year: int | None = None) -> date | None:
    text = str(name or "").strip()
    if not text:
        return None
    m = _SHEET_DATE_RE.match(text)
    if not m:
        return None
    day_i = int(m.group(1))
    month_i = int(m.group(2))
    year_raw = m.group(3)
    if year_raw:
        year_i = int(year_raw)
        if year_i < 100:
            year_i += 2000
    else:
        year_i = int(default_year or date.today().year)
    try:
        return date(year_i, month_i, day_i)
    except ValueError:
        return None


def _parse_ru_ship_date(value: Any, *, default_year: int | None = None) -> date | None:
    """Parse '28.авг' / '01.сен' / normal dates from manager files."""
    parsed = _parse_excel_date(value)
    if parsed is not None:
        return parsed
    text = str(value or "").strip().lower().replace(" ", "")
    if not text:
        return None
    m = re.match(r"^(\d{1,2})[.\-/]?([а-яё]{3})", text)
    if not m:
        return None
    day_i = int(m.group(1))
    month_i = _RU_MONTH_MAP.get(m.group(2)[:3])
    if not month_i:
        return None
    year_i = int(default_year or date.today().year)
    try:
        return date(year_i, month_i, day_i)
    except ValueError:
        return None


def _guess_default_year_from_sheets(sheet_names: list[str]) -> int:
    years: list[int] = []
    for name in sheet_names:
        m = _SHEET_DATE_RE.match(str(name or "").strip())
        if m and m.group(3):
            y = int(m.group(3))
            years.append(y + 2000 if y < 100 else y)
    if years:
        return max(years)
    return date.today().year


def parse_manager_storno_workbook(file_bytes: bytes) -> dict[str, Any]:
    """Parse manager storno Excel (both formats, all sheets).

    Format A: header «Номер отправления» | «Дата отгрузки» | …
    Format B: bare rows — col0 posting number, col1 often «стронировано».
    """
    import io

    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise ValueError("Для импорта нужен пакет openpyxl") from exc

    wb = load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
    try:
        year_hint = _guess_default_year_from_sheets(list(wb.sheetnames))
        sheets_out: list[dict[str, Any]] = []
        entries: list[dict[str, Any]] = []
        seen_units: set[str] = set()

        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            sheet_date = _parse_sheet_name_date(sheet_name, default_year=year_hint)
            rows_raw: list[tuple[Any, ...]] = []
            for row in ws.iter_rows(values_only=True):
                if row is None:
                    continue
                rows_raw.append(tuple(row))
            if not rows_raw:
                sheets_out.append(
                    {
                        "name": str(sheet_name),
                        "sheet_date": sheet_date.isoformat() if sheet_date else None,
                        "header": None,
                        "format": "empty",
                        "rows": [],
                    }
                )
                continue

            first_cells = [str(c or "").strip() for c in rows_raw[0]]
            has_header = "Номер отправления" in first_cells
            unit_col = 0
            header: list[str] | None = None
            data_rows = rows_raw
            if has_header:
                header = first_cells
                unit_col = first_cells.index("Номер отправления")
                data_rows = rows_raw[1:]
                fmt = "headered"
            else:
                fmt = "bare"

            sheet_rows: list[dict[str, Any]] = []
            for row in data_rows:
                if unit_col >= len(row):
                    continue
                unit = str(row[unit_col] or "").strip()
                if not unit or not _looks_like_posting_number(unit):
                    continue
                ship_date = None
                if has_header and len(row) > 1:
                    ship_date = _parse_ru_ship_date(row[1], default_year=year_hint)
                row_date = ship_date or sheet_date
                cells = [c for c in row]
                # Trim trailing Nones for cleaner residual files.
                while cells and cells[-1] is None:
                    cells.pop()
                item = {
                    "unit_number": unit,
                    "sheet_name": str(sheet_name),
                    "sheet_date": sheet_date.isoformat() if sheet_date else None,
                    "row_date": row_date.isoformat() if row_date else None,
                    "cells": cells,
                }
                sheet_rows.append(item)
                entries.append(item)
                seen_units.add(unit)

            sheets_out.append(
                {
                    "name": str(sheet_name),
                    "sheet_date": sheet_date.isoformat() if sheet_date else None,
                    "header": header,
                    "format": fmt,
                    "rows": sheet_rows,
                }
            )

        if not seen_units:
            raise ValueError(
                "В файле не найдены номера отправлений "
                "(ожидается список сторно по листам)"
            )
        return {
            "sheets": sheets_out,
            "entries": entries,
            "units": sorted(seen_units),
            "unit_count": len(seen_units),
        }
    finally:
        wb.close()


def build_manager_storno_residual_xlsx(
    parsed: dict[str, Any], failed_units: set[str]
) -> bytes:
    """Rebuild Excel in the same sheet/layout, only failed (unconfirmed) units."""
    import io

    try:
        from openpyxl import Workbook
    except ImportError as exc:
        raise ValueError("Для импорта нужен пакет openpyxl") from exc

    failed = {str(u).strip() for u in failed_units if str(u).strip()}
    wb = Workbook()
    # Remove default sheet; recreate from source order.
    default = wb.active
    wb.remove(default)

    for sheet in parsed.get("sheets") or []:
        name = str(sheet.get("name") or "лист")[:31] or "лист"
        ws = wb.create_sheet(title=name)
        header = sheet.get("header")
        row_i = 1
        if header:
            for col_i, val in enumerate(header, start=1):
                ws.cell(row=row_i, column=col_i, value=val if val else None)
            row_i += 1
        for item in sheet.get("rows") or []:
            unit = str(item.get("unit_number") or "").strip()
            if unit not in failed:
                continue
            cells = list(item.get("cells") or [])
            if not cells:
                cells = [unit]
            for col_i, val in enumerate(cells, start=1):
                ws.cell(row=row_i, column=col_i, value=val)
            row_i += 1

    if not wb.sheetnames:
        ws = wb.create_sheet(title="остаток")
        ws.cell(row=1, column=1, value="Номер отправления")

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _storno_scan_window(
    parsed: dict[str, Any],
    *,
    date_from: date | None,
    date_to: date | None,
) -> tuple[date, date]:
    """API scan window: UI dates expanded by sheet dates, +14d after max sheet."""
    sheet_dates: list[date] = []
    for sheet in parsed.get("sheets") or []:
        raw = sheet.get("sheet_date")
        if raw:
            try:
                sheet_dates.append(date.fromisoformat(str(raw)[:10]))
            except ValueError:
                pass
        for item in sheet.get("rows") or []:
            rd = item.get("row_date")
            if rd:
                try:
                    sheet_dates.append(date.fromisoformat(str(rd)[:10]))
                except ValueError:
                    pass

    today = date.today()
    d0 = date_from
    d1 = date_to
    if sheet_dates:
        s_min = min(sheet_dates)
        s_max = max(sheet_dates)
        pad_to = min(s_max + timedelta(days=14), today)
        if d0 is None or s_min < d0:
            d0 = s_min
        if d1 is None or pad_to > d1:
            d1 = max(pad_to, d1 or pad_to)
    if d0 is None or d1 is None:
        fallback0, fallback1 = default_sync_dates()
        d0 = d0 or fallback0
        d1 = d1 or fallback1
    if d1 < d0:
        d0, d1 = d1, d0
    if (d1 - d0).days > 92:
        d0 = d1 - timedelta(days=92)
    return d0, d1


def _units_already_closed(
    repo: ReviewRepository, *, user_id: int, units: set[str]
) -> set[str]:
    """Units whose stored net is already ≈0 with a positive storno."""
    ensure_ozon_fbs_fines_tables(repo)
    clean = sorted({str(u).strip() for u in units if str(u).strip()})
    if not clean:
        return set()
    closed: set[str] = set()
    with repo._connect() as conn:
        for i in range(0, len(clean), 500):
            chunk = clean[i : i + 500]
            placeholders = ", ".join(["?"] * len(chunk))
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT
                        unit_number,
                        SUM(amount) AS net_sum,
                        SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS storno_sum
                    FROM ozon_fbs_fines_events
                    WHERE user_id = ?
                      AND unit_number IN ({placeholders})
                    GROUP BY unit_number
                    """
                ),
                (int(user_id), *chunk),
            ).fetchall()
            for row in rows:
                d = dict(row) if hasattr(row, "keys") else {
                    "unit_number": row[0],
                    "net_sum": row[1],
                    "storno_sum": row[2],
                }
                unit = str(d.get("unit_number") or "").strip()
                net = _parse_amount(d.get("net_sum"))
                storno = _parse_amount(d.get("storno_sum"))
                if unit and storno > _EPS and abs(net) <= _EPS:
                    closed.add(unit)
    return closed


def import_manager_storno(
    repo: ReviewRepository,
    *,
    user_id: int,
    file_bytes: bytes,
    filename: str = "",
    date_from: date | None = None,
    date_to: date | None = None,
) -> dict[str, Any]:
    """Verify manager storno list via Ozon API; close confirmed; residual Excel."""
    parsed = parse_manager_storno_workbook(file_bytes)
    wanted = set(parsed["units"])
    scan_from, scan_to = _storno_scan_window(
        parsed, date_from=date_from, date_to=date_to
    )

    client_id, api_key = _credentials(repo, user_id=user_id)
    client = OzonFbsClient(client_id=client_id, api_key=api_key, timeout=90)

    name = str(filename or "сторно").strip() or "сторно"
    append_sync_log(
        repo,
        user_id=user_id,
        message=(
            f"Импорт сторно «{name}»: отправлений {len(wanted)}, "
            f"проверка API {scan_from.isoformat()} … {scan_to.isoformat()}"
        ),
        level="info",
    )

    confirmed_api: set[str] = set()
    inserted = 0
    updated = 0
    slot_hits = 0
    errors: list[str] = []
    day = scan_from
    while day <= scan_to:
        try:
            accruals = _fetch_day_accruals(client, day)
            day_hits = 0
            for acc in accruals:
                amounts = extract_slot_fees(acc)
                if not amounts:
                    continue
                unit = str(acc.get("unit_number") or "").strip()
                if not unit or unit not in wanted:
                    continue
                try:
                    accrual_id = int(acc.get("accrual_id") or 0)
                except (TypeError, ValueError):
                    continue
                if accrual_id <= 0:
                    continue
                currency = "RUB"
                total = acc.get("total_amount")
                if isinstance(total, dict):
                    currency = str(total.get("currency") or "RUB")
                category = str(acc.get("accrued_category") or "")
                amount = sum(amounts, Decimal("0"))
                is_new = upsert_event(
                    repo,
                    user_id=user_id,
                    accrual_id=accrual_id,
                    event_date=day,
                    unit_number=unit,
                    amount=amount,
                    currency=currency,
                    accrued_category=category,
                    raw=acc,
                )
                day_hits += 1
                slot_hits += 1
                if is_new:
                    inserted += 1
                else:
                    updated += 1
                if amount > _EPS:
                    confirmed_api.add(unit)
            append_sync_log(
                repo,
                user_id=user_id,
                message=(
                    f"Сторно-проверка {day.isoformat()}: "
                    f"начислений {len(accruals)}, слот по списку {day_hits}"
                ),
                level="ok" if day_hits else "info",
            )
        except Exception as exc:
            msg = f"Сторно-проверка {day.isoformat()}: ошибка — {exc}"
            _log.warning(
                "ozon fines storno import day failed user=%s day=%s err=%s",
                user_id,
                day,
                exc,
            )
            errors.append(msg)
            append_sync_log(repo, user_id=user_id, message=msg, level="error")
            if _is_fatal_ozon_auth_error(exc):
                abort_msg = (
                    "Импорт сторно остановлен: ключ Ozon отклонён (403). "
                    "Проверьте Api-Key в настройках штрафов."
                )
                append_sync_log(repo, user_id=user_id, message=abort_msg, level="error")
                errors.append(abort_msg)
                break
        day += timedelta(days=1)

    already = _units_already_closed(repo, user_id=user_id, units=wanted)
    confirmed = set(confirmed_api) | already
    failed = wanted - confirmed

    attachment_id: int | None = None
    residual_name = ""
    if failed:
        residual_bytes = build_manager_storno_residual_xlsx(parsed, failed)
        base = name.rsplit(".", 1)[0] if "." in name else name
        residual_name = f"{base}_не_подтверждено.xlsx"
        attachment_id = _store_log_attachment(
            repo,
            user_id=user_id,
            filename=residual_name,
            file_bytes=residual_bytes,
        )

    summary = (
        f"Импорт сторно «{name}»: в файле {len(wanted)}, "
        f"подтверждено API {len(confirmed_api)}, "
        f"уже закрыты {len(already - confirmed_api)}, "
        f"не подтверждено {len(failed)}, "
        f"событий слота {slot_hits} (новых {inserted})"
    )
    if errors:
        summary += f", ошибок дней {len(errors)}"
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="ok" if confirmed and not failed else ("warn" if failed else "error"),
        attachment_id=attachment_id,
    )
    return {
        "ok": True,
        "units_total": len(wanted),
        "confirmed": len(confirmed),
        "confirmed_api": len(confirmed_api),
        "already_closed": len(already),
        "failed": len(failed),
        "slot_events": slot_hits,
        "inserted": inserted,
        "updated": updated,
        "errors": errors,
        "date_from": scan_from.isoformat(),
        "date_to": scan_to.isoformat(),
        "attachment_id": attachment_id,
        "download_url": (
            f"/api/ozon-fbs/fines/sync-log/file/{attachment_id}"
            if attachment_id
            else None
        ),
        "residual_filename": residual_name or None,
        "summary": summary,
    }


def start_storno_import_thread(
    repo: ReviewRepository,
    *,
    user_id: int,
    file_bytes: bytes,
    filename: str = "",
    date_from: date | None = None,
    date_to: date | None = None,
) -> tuple[bool, str, dict[str, Any]]:
    """Background manager-storno import (API crawl can exceed nginx timeout)."""
    # Parse early so HTTP can surface format errors immediately.
    parsed = parse_manager_storno_workbook(file_bytes)
    scan_from, scan_to = _storno_scan_window(
        parsed, date_from=date_from, date_to=date_to
    )
    _credentials(repo, user_id=user_id)

    uid = int(user_id)
    with _fines_sync_lock:
        cur = _fines_sync_state.get(uid) or {}
        if cur.get("in_progress"):
            status = {
                "in_progress": True,
                "job": str(cur.get("job") or "sync"),
                "message": str(cur.get("message") or ""),
                "error": str(cur.get("error") or ""),
                "date_from": str(cur.get("date_from") or ""),
                "date_to": str(cur.get("date_to") or ""),
                "result": cur.get("result"),
            }
            return False, "Синхронизация или импорт сторно уже запущены", status
        _fines_sync_state[uid] = {
            "in_progress": True,
            "job": "storno_import",
            "message": (
                f"Импорт сторно: {parsed['unit_count']} отпр., "
                f"{scan_from.isoformat()} … {scan_to.isoformat()}"
            ),
            "error": "",
            "date_from": scan_from.isoformat(),
            "date_to": scan_to.isoformat(),
            "result": None,
        }

    try:
        append_sync_log(
            repo,
            user_id=uid,
            message=(
                f"Фоновый импорт сторно «{filename or 'файл'}» запущен "
                f"({parsed['unit_count']} отпр., "
                f"{scan_from.isoformat()} … {scan_to.isoformat()})"
            ),
            level="info",
        )
    except Exception:
        _log.exception("ozon fines storno import start log failed user=%s", uid)

    # Capture bytes for the worker thread.
    payload = bytes(file_bytes)
    fname = str(filename or "")

    def _run() -> None:
        try:
            result = import_manager_storno(
                repo,
                user_id=uid,
                file_bytes=payload,
                filename=fname,
                date_from=date_from,
                date_to=date_to,
            )
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "job": "storno_import",
                    "message": str(result.get("summary") or "Готово"),
                    "error": "",
                    "date_from": scan_from.isoformat(),
                    "date_to": scan_to.isoformat(),
                    "result": result,
                }
        except Exception as exc:
            _log.exception("ozon fines storno import failed user=%s", uid)
            try:
                append_sync_log(
                    repo,
                    user_id=uid,
                    message=f"Сбой импорта сторно: {exc}",
                    level="error",
                )
            except Exception:
                pass
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "job": "storno_import",
                    "message": str(exc),
                    "error": str(exc),
                    "date_from": scan_from.isoformat(),
                    "date_to": scan_to.isoformat(),
                    "result": None,
                }

    threading.Thread(
        target=_run,
        name=f"ozon-fines-storno-{uid}",
        daemon=True,
    ).start()
    return True, "Импорт сторно запущен", get_sync_status(user_id=uid)
