"""Ozon FBS posting scan journal (parity with wb_fbs_return_scans)."""
from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from typing import Any

from . import ozon_fbs as oz
from . import wb_fbs as wb
from .wb_fbs_kiz_restore import normalize_sticker_scan, sticker_number
from .repository import ReviewRepository

_log = logging.getLogger(__name__)

SCAN_ASSEMBLY = "assembly_sticker"
SCAN_KIZ = "kiz"
SCAN_PICK = "pick_barcode"
SCAN_LOOKUP = "lookup"

_POSTING_SCAN_COLS = """
    posting_number, order_id, order_number, supply_id, tab, status,
    offer_id, sku, product_name, marking_codes_json, marking_saved_at,
    pick_verified, pick_barcode, pick_verified_at,
    sticker_barcode, sticker_part_a, sticker_part_b
"""


def ensure_ozon_fbs_scan_tables(repo: ReviewRepository) -> None:
    oz.ensure_ozon_fbs_tables(repo)
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_posting_scans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                scan_type TEXT NOT NULL DEFAULT '',
                scan_raw TEXT NOT NULL DEFAULT '',
                posting_number TEXT NOT NULL DEFAULT '',
                order_id BIGINT,
                order_number TEXT NOT NULL DEFAULT '',
                supply_id TEXT NOT NULL DEFAULT '',
                sticker_barcode TEXT NOT NULL DEFAULT '',
                sticker_part_a TEXT NOT NULL DEFAULT '',
                sticker_part_b TEXT NOT NULL DEFAULT '',
                kiz_code TEXT NOT NULL DEFAULT '',
                pick_barcode TEXT NOT NULL DEFAULT '',
                matched_posting_numbers_json TEXT NOT NULL DEFAULT '[]',
                product_name TEXT NOT NULL DEFAULT '',
                offer_id TEXT NOT NULL DEFAULT '',
                duplicate_of_id BIGINT
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_posting_scans_user_src_time "
                "ON ozon_fbs_posting_scans(user_id, source_id, scanned_at DESC)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_posting_scans_posting "
                "ON ozon_fbs_posting_scans(user_id, source_id, posting_number) "
                "WHERE posting_number <> ''"
            )
        )


def _scan_row_to_api(row: dict[str, Any]) -> dict[str, Any]:
    try:
        matched = json.loads(str(row.get("matched_posting_numbers_json") or "[]"))
    except json.JSONDecodeError:
        matched = []
    if not isinstance(matched, list):
        matched = []
    scanned = row.get("scanned_at")
    return {
        "id": row.get("id"),
        "scanned_at": wb._normalize_kiz_saved_at(scanned) if scanned else "",
        "scan_type": str(row.get("scan_type") or "").strip(),
        "scan_raw": str(row.get("scan_raw") or "").strip(),
        "posting_number": str(row.get("posting_number") or "").strip(),
        "order_id": row.get("order_id"),
        "order_number": str(row.get("order_number") or "").strip(),
        "supply_id": str(row.get("supply_id") or "").strip(),
        "sticker_barcode": str(row.get("sticker_barcode") or "").strip(),
        "sticker_part_a": str(row.get("sticker_part_a") or "").strip(),
        "sticker_part_b": str(row.get("sticker_part_b") or "").strip(),
        "kiz_code": str(row.get("kiz_code") or "").strip(),
        "pick_barcode": str(row.get("pick_barcode") or "").strip(),
        "matched_posting_numbers": [
            str(x).strip() for x in matched if str(x).strip()
        ],
        "product_name": str(row.get("product_name") or "").strip(),
        "offer_id": str(row.get("offer_id") or "").strip(),
    }


def insert_posting_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    payload: dict[str, Any],
) -> dict[str, Any]:
    ensure_ozon_fbs_scan_tables(repo)
    now = datetime.now(UTC).isoformat()
    matched = payload.get("matched_posting_numbers")
    if not isinstance(matched, list):
        matched = []
    with repo._connect() as conn:
        scan_id = repo._insert_and_get_id(
            conn,
            repo._sql(
                """
                INSERT INTO ozon_fbs_posting_scans (
                    user_id, source_id, scanned_at, scan_type, scan_raw,
                    posting_number, order_id, order_number, supply_id,
                    sticker_barcode, sticker_part_a, sticker_part_b,
                    kiz_code, pick_barcode, matched_posting_numbers_json,
                    product_name, offer_id, duplicate_of_id
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """
            ),
            (
                int(user_id),
                int(source_id),
                now,
                str(payload.get("scan_type") or "").strip(),
                str(payload.get("scan_raw") or "").strip(),
                str(payload.get("posting_number") or "").strip(),
                payload.get("order_id"),
                str(payload.get("order_number") or "").strip(),
                str(payload.get("supply_id") or "").strip(),
                str(payload.get("sticker_barcode") or "").strip(),
                str(payload.get("sticker_part_a") or "").strip(),
                str(payload.get("sticker_part_b") or "").strip(),
                str(payload.get("kiz_code") or "").strip(),
                str(payload.get("pick_barcode") or "").strip(),
                json.dumps(matched, ensure_ascii=False),
                str(payload.get("product_name") or "").strip(),
                str(payload.get("offer_id") or "").strip(),
                payload.get("duplicate_of_id"),
            ),
        )
        row = conn.execute(
            repo._sql("SELECT * FROM ozon_fbs_posting_scans WHERE id = ?"),
            (scan_id,),
        ).fetchone()
    return _scan_row_to_api(repo._row_to_dict(row) if row else {})


def list_posting_scans(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    limit: int = 100,
    scan_type: str | None = None,
) -> dict[str, Any]:
    ensure_ozon_fbs_scan_tables(repo)
    lim = min(max(int(limit), 1), 500)
    clauses = ["user_id = ?", "source_id = ?"]
    params: list[Any] = [int(user_id), int(source_id)]
    st = str(scan_type or "").strip()
    if st:
        clauses.append("scan_type = ?")
        params.append(st)
    where = " AND ".join(clauses)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                f"""
                SELECT * FROM ozon_fbs_posting_scans
                WHERE {where}
                ORDER BY scanned_at DESC, id DESC
                LIMIT ?
                """
            ),
            (*params, lim),
        ).fetchall()
    items = [_scan_row_to_api(repo._row_to_dict(r)) for r in rows]
    return {"ok": True, "items": items, "count": len(items)}


def record_posting_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    scan_type: str,
    scan_raw: str,
    posting_row: dict[str, Any] | None = None,
    posting_number: str | None = None,
    kiz_code: str | None = None,
    pick_barcode: str | None = None,
    matched_posting_numbers: list[str] | None = None,
    supply_id: str | None = None,
) -> dict[str, Any] | None:
    """Write one journal row; returns API item or None when scan_raw empty."""
    raw = normalize_sticker_scan(scan_raw)
    if not raw:
        return None
    row = posting_row if isinstance(posting_row, dict) else {}
    pn = str(posting_number or row.get("posting_number") or "").strip()
    sticker = oz.posting_sticker_payload_from_row(row) if row else {}
    if not pn:
        pn = str(sticker.get("posting_number") or "").strip()
    kiz_val = str(kiz_code or "").strip()
    if not kiz_val and row:
        try:
            codes = json.loads(str(row.get("marking_codes_json") or "[]"))
        except json.JSONDecodeError:
            codes = []
        if isinstance(codes, list) and codes:
            kiz_val = wb._kiz_code_clean(codes[0])
    pick_val = str(pick_barcode or "").strip()
    if not pick_val and row and bool(row.get("pick_verified")):
        pick_val = str(row.get("pick_barcode") or "").strip()
    matched = matched_posting_numbers or ([pn] if pn else [])
    supply_val = str(supply_id or row.get("supply_id") or "").strip()
    try:
        item = insert_posting_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            payload={
                "scan_type": scan_type,
                "scan_raw": raw,
                "posting_number": pn,
                "order_id": row.get("order_id") if row else None,
                "order_number": str(row.get("order_number") or sticker.get("order_number") or ""),
                "supply_id": supply_val,
                "sticker_barcode": str(
                    sticker.get("sticker_barcode") or raw
                ).strip(),
                "sticker_part_a": str(sticker.get("sticker_part_a") or "").strip(),
                "sticker_part_b": str(sticker.get("sticker_part_b") or "").strip(),
                "kiz_code": kiz_val,
                "pick_barcode": pick_val,
                "matched_posting_numbers": matched,
                "product_name": str(row.get("product_name") or "").strip(),
                "offer_id": str(row.get("offer_id") or "").strip(),
            },
        )
    except Exception as exc:
        _log.warning("ozon posting scan journal: %s", exc)
        return None
    try:
        from . import ozon_fbs_ops_log as ops_log

        ops_log.log_scan_event(
            repo,
            user_id=user_id,
            source_id=source_id,
            scan_type=str(scan_type or ""),
            scan_raw=raw,
            posting_number=pn,
            supply_id=supply_val,
        )
    except Exception:
        pass
    return item
