"""Local Ozon FBS supplies (Feedpilot-only; no Ozon supply API).

Created after «Собрать все заказы»: postings ship via /v4/posting/fbs/ship,
then are grouped into local supplies on «Ожидают отгрузки» with the same naming
rules as WB FBS «Собрать все МГТ» (date title + uniqueness).
"""
from __future__ import annotations

import base64
import json
import logging
import secrets
import time
from dataclasses import dataclass
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from . import ozon_fbs as oz
from . import ozon_fbs_detail as oz_detail
from . import wb_fbs as wb
from .repository import ReviewRepository

_log = logging.getLogger(__name__)

SUPPLY_ID_PREFIX = "OZ-FBS"
ORPHAN_DELIVERING_SUPPLY_NAME = "Без локальной поставки"

_TAB_SUPPLY_STATUS_LABEL: dict[str, str] = {
    oz.TAB_AWAITING_DELIVER: "Сборка заказов",
    oz.TAB_DELIVERING: "Доставляется",
}


def ensure_ozon_fbs_supply_schema(repo: ReviewRepository) -> None:
    oz.ensure_ozon_fbs_tables(repo)
    with repo._connect() as conn:
        try:
            conn.execute(
                "ALTER TABLE ozon_fbs_postings "
                "ADD COLUMN IF NOT EXISTS supply_id TEXT NOT NULL DEFAULT ''"
            )
        except Exception:
            try:
                conn.execute(
                    "ALTER TABLE ozon_fbs_postings "
                    "ADD COLUMN supply_id TEXT NOT NULL DEFAULT ''"
                )
            except Exception:
                pass
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_supplies (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                supply_id TEXT NOT NULL,
                name TEXT NOT NULL DEFAULT '',
                warehouse_id BIGINT,
                warehouse_name TEXT NOT NULL DEFAULT '',
                done BOOLEAN NOT NULL DEFAULT FALSE,
                posting_numbers_json TEXT NOT NULL DEFAULT '[]',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (user_id, source_id, supply_id)
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_supplies_user_src "
                "ON ozon_fbs_supplies(user_id, source_id, created_at DESC)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_postings_supply "
                "ON ozon_fbs_postings(user_id, source_id, supply_id)"
            )
        )


def _source_display_name(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> str:
    src = repo.get_supply_source_with_key(user_id=user_id, source_id=source_id)
    name = str((src or {}).get("name") or "").strip()
    return name or f"Источник {source_id}"


def default_supply_name(*, source_name: str, when: datetime | None = None) -> str:
    """``Поставка Название источника от ДД.ММ.ГГГГ`` (MSK)."""
    dt = when or datetime.now(ZoneInfo("Europe/Moscow"))
    label = str(source_name or "").strip() or "—"
    return f"Поставка {label} от {dt.strftime('%d.%m.%Y')}"


def _unique_supply_name(base: str, existing_names: set[str]) -> str:
    name = str(base or "").strip() or "Поставка"
    if name not in existing_names:
        return name
    for i in range(2, 100):
        candidate = f"{name} ({i})"
        if candidate not in existing_names:
            return candidate
    return f"{name} · {int(time.time())}"


def _new_supply_id(source_id: int) -> str:
    stamp = datetime.now(ZoneInfo("Europe/Moscow")).strftime("%Y%m%d")
    return f"{SUPPLY_ID_PREFIX}-{int(source_id)}-{stamp}-{secrets.token_hex(3).upper()}"


def _parse_json_list(raw: object) -> list[Any]:
    try:
        data = json.loads(raw or "[]")
    except Exception:
        return []
    return data if isinstance(data, list) else []


def _esc(value: object) -> str:
    return (
        str(value or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def list_open_supplies(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_supply_schema(repo)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT * FROM ozon_fbs_supplies
                WHERE user_id = ? AND source_id = ? AND COALESCE(done, FALSE) = FALSE
                ORDER BY created_at DESC
                """
            ),
            (user_id, source_id),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = repo._row_to_dict(row)
        nums = [
            str(x).strip()
            for x in _parse_json_list(d.get("posting_numbers_json"))
            if str(x).strip()
        ]
        d["posting_numbers"] = nums
        d["order_count"] = len(nums)
        d["is_empty"] = len(nums) == 0
        out.append(d)
    return out


def _supply_ids_with_tab(
    repo: ReviewRepository, *, user_id: int, source_id: int, tab: str
) -> set[str]:
    """Distinct local supply ids that have postings on the given Ozon tab."""
    ensure_ozon_fbs_supply_schema(repo)
    tab_key = str(tab or "").strip()
    if not tab_key:
        return set()
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT DISTINCT supply_id FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND tab = ?
                  AND COALESCE(supply_id, '') != ''
                """
            ),
            (user_id, source_id, tab_key),
        ).fetchall()
    out: set[str] = set()
    for row in rows:
        sid = str(row["supply_id"] if hasattr(row, "keys") else row[0]).strip()
        if sid:
            out.add(sid)
    return out


def list_collect_target_supplies(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> list[dict[str, Any]]:
    """Open supplies eligible for collect/selection → «Ожидают отгрузки».

    «Доставляются» supplies are excluded — orders land there only after sync.
    Empty supplies tied to delivering-only postings are excluded as well.
    """
    open_supplies = list_open_supplies(repo, user_id=user_id, source_id=source_id)
    awaiting_ids = _supply_ids_with_tab(
        repo, user_id=user_id, source_id=source_id, tab=oz.TAB_AWAITING_DELIVER
    )
    delivering_ids = _supply_ids_with_tab(
        repo, user_id=user_id, source_id=source_id, tab=oz.TAB_DELIVERING
    )
    eligible: list[dict[str, Any]] = []
    for s in open_supplies:
        sid = str(s.get("supply_id") or "").strip()
        if not sid:
            continue
        if sid in awaiting_ids:
            eligible.append(s)
        elif s.get("is_empty") and sid not in delivering_ids:
            eligible.append(s)
    return eligible


def _is_collect_target_supply(
    repo: ReviewRepository, *, user_id: int, source_id: int, supply_id: str
) -> bool:
    sid = str(supply_id or "").strip()
    if not sid:
        return False
    return sid in {
        str(s.get("supply_id") or "").strip()
        for s in list_collect_target_supplies(
            repo, user_id=user_id, source_id=source_id
        )
        if str(s.get("supply_id") or "").strip()
    }


def _load_awaiting_packaging_rows(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_supply_schema(repo)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT * FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND tab = ?
                  AND COALESCE(supply_id, '') = ''
                ORDER BY created_at_ozon DESC NULLS LAST, posting_number DESC
                """
            ),
            (user_id, source_id, oz.TAB_AWAITING_PACKAGING),
        ).fetchall()
    return [repo._row_to_dict(r) for r in rows]


def preview_ship_all_collect(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> dict[str, Any]:
    """Plan local supplies for «Собрать все заказы» (group by warehouse)."""
    ensure_ozon_fbs_supply_schema(repo)
    rows = _load_awaiting_packaging_rows(repo, user_id=user_id, source_id=source_id)
    buckets: dict[Any, list[dict[str, Any]]] = {}
    for row in rows:
        wh = row.get("warehouse_id")
        buckets.setdefault(wh, []).append(row)

    all_open = list_open_supplies(repo, user_id=user_id, source_id=source_id)
    open_supplies = list_collect_target_supplies(
        repo, user_id=user_id, source_id=source_id
    )
    existing_names = {
        str(s.get("name") or "").strip()
        for s in all_open
        if str(s.get("name") or "").strip()
    }
    reserved = set(existing_names)
    empties_pool = [s for s in open_supplies if s.get("is_empty")]

    source_name = _source_display_name(repo, user_id=user_id, source_id=source_id)
    groups: list[dict[str, Any]] = []
    for warehouse_id in sorted(buckets.keys(), key=lambda x: (x is None, str(x))):
        bucket = buckets[warehouse_id]
        posting_numbers = [
            str(r.get("posting_number") or "").strip()
            for r in bucket
            if str(r.get("posting_number") or "").strip()
        ]
        wh_name = str(bucket[0].get("warehouse_name") or "").strip() if bucket else ""
        matching = []
        for s in open_supplies:
            if s.get("is_empty"):
                continue
            sw = s.get("warehouse_id")
            if warehouse_id is None and sw is None:
                matching.append(s)
            elif (
                warehouse_id is not None
                and sw is not None
                and int(sw) == int(warehouse_id)
            ):
                matching.append(s)
        base = default_supply_name(source_name=source_name)
        suggested = _unique_supply_name(base, reserved)
        reserved.add(suggested)
        group_key = f"wh{warehouse_id if warehouse_id is not None else 'none'}"
        label = wh_name or (
            f"склад {warehouse_id}" if warehouse_id is not None else "склад —"
        )
        if len(matching) >= 2:
            mode = "choose"
            candidates = list(matching)
            default_supply_id = str(matching[0].get("supply_id") or "")
        elif len(matching) == 1:
            mode = "add_one"
            candidates = list(matching)
            default_supply_id = str(matching[0].get("supply_id") or "")
        elif empties_pool:
            chosen_empty = empties_pool[0]
            mode = "add_one"
            candidates = [chosen_empty]
            default_supply_id = str(chosen_empty.get("supply_id") or "")
            empties_pool = empties_pool[1:]
        else:
            mode = "create"
            candidates = []
            default_supply_id = ""
        compatible = [
            {
                "supply_id": s.get("supply_id"),
                "name": s.get("name") or s.get("supply_id"),
                "is_empty": bool(s.get("is_empty")),
                "orders_count": int(s.get("order_count") or 0),
                "warehouse_name": s.get("warehouse_name") or "",
            }
            for s in candidates
        ]
        groups.append(
            {
                "group_key": group_key,
                "warehouse_id": warehouse_id,
                "warehouse_name": wh_name,
                "label": label,
                "posting_numbers": posting_numbers,
                "order_count": len(posting_numbers),
                "suggested_name": suggested,
                "name_conflict": False,
                "compatible_supplies": compatible,
                "mode": mode,
                "default_supply_id": default_supply_id,
            }
        )

    needs_modal = any(g.get("mode") in ("create", "choose") for g in groups)
    return {
        "ok": True,
        "mgt_count": len(rows),
        "posting_count": len(rows),
        "groups": groups,
        "needs_modal": needs_modal,
        "existing_names": sorted(existing_names),
        "source_name": source_name,
    }


def _create_local_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    name: str,
    warehouse_id: object,
    warehouse_name: str,
    posting_numbers: list[str],
    force_tab: str | None = oz.TAB_AWAITING_DELIVER,
) -> str:
    ensure_ozon_fbs_supply_schema(repo)
    sid = _new_supply_id(source_id)
    nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    try:
        wh_id = int(warehouse_id) if warehouse_id is not None else None
    except (TypeError, ValueError):
        wh_id = None
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_supplies (
                    user_id, source_id, supply_id, name, warehouse_id, warehouse_name,
                    done, posting_numbers_json, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, FALSE, ?, NOW(), NOW())
                """
            ),
            (
                user_id,
                source_id,
                sid,
                str(name or "").strip()
                or default_supply_name(
                    source_name=_source_display_name(
                        repo, user_id=user_id, source_id=source_id
                    )
                ),
                wh_id,
                str(warehouse_name or "").strip(),
                json.dumps(nums, ensure_ascii=False),
            ),
        )
        if nums:
            placeholders = ", ".join("?" for _ in nums)
            if force_tab:
                conn.execute(
                    repo._sql(
                        f"""
                        UPDATE ozon_fbs_postings
                        SET supply_id = ?, tab = ?, status = ?
                        WHERE user_id = ? AND source_id = ?
                          AND posting_number IN ({placeholders})
                        """
                    ),
                    (
                        sid,
                        str(force_tab),
                        str(force_tab),
                        user_id,
                        source_id,
                        *nums,
                    ),
                )
            else:
                conn.execute(
                    repo._sql(
                        f"""
                        UPDATE ozon_fbs_postings
                        SET supply_id = ?
                        WHERE user_id = ? AND source_id = ?
                          AND posting_number IN ({placeholders})
                        """
                    ),
                    (sid, user_id, source_id, *nums),
                )
    return sid


def _add_postings_to_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    posting_numbers: list[str],
) -> None:
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    if not sid or not nums:
        return
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT posting_numbers_json FROM ozon_fbs_supplies
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (user_id, source_id, sid),
        ).fetchone()
        if not row:
            raise RuntimeError(f"Поставка {sid} не найдена")
        raw = row["posting_numbers_json"] if hasattr(row, "keys") else row[0]
        existing = [
            str(x).strip()
            for x in _parse_json_list(raw)
            if str(x).strip()
        ]
        merged = existing[:]
        for n in nums:
            if n not in merged:
                merged.append(n)
        conn.execute(
            repo._sql(
                """
                UPDATE ozon_fbs_supplies
                SET posting_numbers_json = ?, updated_at = NOW()
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (json.dumps(merged, ensure_ascii=False), user_id, source_id, sid),
        )
        placeholders = ", ".join("?" for _ in nums)
        conn.execute(
            repo._sql(
                f"""
                UPDATE ozon_fbs_postings
                SET supply_id = ?, tab = ?, status = ?
                WHERE user_id = ? AND source_id = ?
                  AND posting_number IN ({placeholders})
                """
            ),
            (
                sid,
                oz.TAB_AWAITING_DELIVER,
                oz.TAB_AWAITING_DELIVER,
                user_id,
                source_id,
                *nums,
            ),
        )


def _link_postings_to_supply_only(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    posting_numbers: list[str],
) -> None:
    """Attach postings to a supply without changing their Ozon tab/status."""
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    if not sid or not nums:
        return
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT posting_numbers_json FROM ozon_fbs_supplies
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (user_id, source_id, sid),
        ).fetchone()
        if not row:
            raise RuntimeError(f"Поставка {sid} не найдена")
        raw = row["posting_numbers_json"] if hasattr(row, "keys") else row[0]
        existing = [
            str(x).strip()
            for x in _parse_json_list(raw)
            if str(x).strip()
        ]
        merged = existing[:]
        for n in nums:
            if n not in merged:
                merged.append(n)
        conn.execute(
            repo._sql(
                """
                UPDATE ozon_fbs_supplies
                SET posting_numbers_json = ?, updated_at = NOW()
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (json.dumps(merged, ensure_ascii=False), user_id, source_id, sid),
        )
        placeholders = ", ".join("?" for _ in nums)
        conn.execute(
            repo._sql(
                f"""
                UPDATE ozon_fbs_postings
                SET supply_id = ?
                WHERE user_id = ? AND source_id = ?
                  AND posting_number IN ({placeholders})
                """
            ),
            (sid, user_id, source_id, *nums),
        )


def execute_ship_all_collect(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    client_id: str,
    api_key: str,
    decisions: list[dict[str, Any]],
) -> dict[str, Any]:
    """Ship on Ozon + create/add local supplies from decisions."""
    ensure_ozon_fbs_supply_schema(repo)
    preview = preview_ship_all_collect(repo, user_id=user_id, source_id=source_id)
    groups_by_key = {str(g.get("group_key")): g for g in preview.get("groups") or []}
    if not groups_by_key:
        return {
            "ok": True,
            "total": 0,
            "shipped": 0,
            "failed": 0,
            "created_supplies": [],
            "errors": [],
            "message": "Нет отправлений в «Ожидают сборки»",
            "goto_awaiting_deliver": False,
        }

    client = oz.OzonFbsClient(client_id, api_key)
    shipped: list[str] = []
    errors: list[dict[str, str]] = []
    created: list[dict[str, str]] = []
    group_lines: list[str] = []

    open_names = {
        str(s.get("name") or "").strip()
        for s in list_open_supplies(repo, user_id=user_id, source_id=source_id)
        if str(s.get("name") or "").strip()
    }
    source_name = _source_display_name(repo, user_id=user_id, source_id=source_id)

    for dec in decisions or []:
        if not isinstance(dec, dict):
            continue
        gkey = str(dec.get("group_key") or "").strip()
        group = groups_by_key.get(gkey)
        if not group:
            errors.append({"posting_number": gkey or "?", "error": "Группа не найдена"})
            continue
        action = str(dec.get("action") or group.get("mode") or "create").strip().lower()
        if action == "add_one":
            action = "add"
        posting_numbers = list(group.get("posting_numbers") or [])
        shipped_here: list[str] = []
        for pn in posting_numbers:
            try:
                oz_detail.ship_posting(
                    repo,
                    user_id=user_id,
                    source_id=source_id,
                    posting_number=pn,
                    client_id=client_id,
                    api_key=api_key,
                    client=client,
                )
                shipped.append(pn)
                shipped_here.append(pn)
            except Exception as exc:
                errors.append({"posting_number": pn, "error": str(exc)})
        if not shipped_here:
            continue

        wh_id = group.get("warehouse_id")
        wh_name = str(group.get("warehouse_name") or "")
        try:
            if action == "create":
                name = str(dec.get("name") or group.get("suggested_name") or "").strip()
                name = _unique_supply_name(
                    name or default_supply_name(source_name=source_name),
                    open_names,
                )
                sid = _create_local_supply(
                    repo,
                    user_id=user_id,
                    source_id=source_id,
                    name=name,
                    warehouse_id=wh_id,
                    warehouse_name=wh_name,
                    posting_numbers=shipped_here,
                )
                open_names.add(name)
                created.append({"supply_id": sid, "name": name})
                group_lines.append(f"{name}: {len(shipped_here)} отпр.")
            else:
                sid = str(
                    dec.get("supply_id") or group.get("default_supply_id") or ""
                ).strip()
                if not sid:
                    raise RuntimeError("Не выбрана поставка")
                if not _is_collect_target_supply(
                    repo, user_id=user_id, source_id=source_id, supply_id=sid
                ):
                    raise RuntimeError(
                        "Поставка «Доставляются» недоступна для ручного сбора"
                    )
                _add_postings_to_supply(
                    repo,
                    user_id=user_id,
                    source_id=source_id,
                    supply_id=sid,
                    posting_numbers=shipped_here,
                )
                sname = next(
                    (
                        str(c.get("name") or sid)
                        for c in (group.get("compatible_supplies") or [])
                        if str(c.get("supply_id")) == sid
                    ),
                    sid,
                )
                group_lines.append(f"{sname}: +{len(shipped_here)} отпр.")
        except Exception as exc:
            errors.append({"posting_number": gkey, "error": str(exc)})

    shipped_n = len(shipped)
    failed_n = len(errors)
    ok = shipped_n > 0 and failed_n == 0
    if shipped_n and not failed_n:
        message = f"Собрано {shipped_n} отправлений → «Ожидают отгрузки»"
    elif shipped_n:
        message = f"Собрано {shipped_n}, ошибок {failed_n}"
    else:
        message = f"Не удалось собрать отправления ({failed_n})"
    return {
        "ok": ok,
        "total": int(preview.get("posting_count") or 0),
        "shipped": shipped_n,
        "failed": failed_n,
        "shipped_numbers": shipped,
        "created_supplies": created,
        "group_lines": group_lines,
        "errors": errors,
        "message": message,
        "goto_awaiting_deliver": shipped_n > 0,
    }


def _load_postings_by_numbers(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    posting_numbers: list[str],
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_supply_schema(repo)
    wanted = [str(x).strip() for x in posting_numbers if str(x).strip()]
    if not wanted:
        return []
    placeholders = ", ".join("?" for _ in wanted)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                f"""
                SELECT * FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ?
                  AND posting_number IN ({placeholders})
                """
            ),
            (user_id, source_id, *wanted),
        ).fetchall()
    by_num = {str(repo._row_to_dict(r).get("posting_number") or ""): repo._row_to_dict(r) for r in rows}
    # Preserve request order.
    return [by_num[n] for n in wanted if n in by_num]


def _selection_mix_errors(rows: list[dict[str, Any]]) -> list[str]:
    """Ozon FBS: one supply = one warehouse (same idea as WB warehouse rule)."""
    if not rows:
        return ["Не выбраны отправления"]
    warehouses: set[object] = set()
    for o in rows:
        wh = o.get("warehouse_id")
        if wh is None or str(wh).strip() == "":
            warehouses.add(None)
            continue
        try:
            warehouses.add(int(wh))
        except (TypeError, ValueError):
            warehouses.add(None)
    if None in warehouses and len(warehouses) > 1:
        return [
            "У части отправлений не указан склад, а у других указан. "
            "В одну поставку можно добавить только отправления одного склада."
        ]
    if len(warehouses) > 1:
        return [
            "Выбраны отправления с разных складов Ozon. "
            "В одну локальную поставку можно объединить только один склад."
        ]
    return []


def _selection_traits(rows: list[dict[str, Any]]) -> dict[str, Any]:
    if not rows:
        return {"warehouse_id": None, "warehouse_name": ""}
    wh = rows[0].get("warehouse_id")
    try:
        wh_id = int(wh) if wh is not None and str(wh).strip() != "" else None
    except (TypeError, ValueError):
        wh_id = None
    return {
        "warehouse_id": wh_id,
        "warehouse_name": str(rows[0].get("warehouse_name") or "").strip(),
    }


def _compatible_supplies_for_warehouse(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    warehouse_id: object,
) -> list[dict[str, Any]]:
    open_supplies = list_collect_target_supplies(
        repo, user_id=user_id, source_id=source_id
    )
    out: list[dict[str, Any]] = []
    for s in open_supplies:
        sw = s.get("warehouse_id")
        if s.get("is_empty"):
            out.append(
                {
                    "supply_id": s.get("supply_id"),
                    "name": s.get("name") or s.get("supply_id"),
                    "is_empty": True,
                    "orders_count": int(s.get("order_count") or 0),
                    "warehouse_id": sw,
                    "warehouse_name": s.get("warehouse_name") or "",
                }
            )
            continue
        if warehouse_id is None and sw is None:
            match = True
        elif warehouse_id is not None and sw is not None:
            try:
                match = int(sw) == int(warehouse_id)
            except (TypeError, ValueError):
                match = False
        else:
            match = False
        if match:
            out.append(
                {
                    "supply_id": s.get("supply_id"),
                    "name": s.get("name") or s.get("supply_id"),
                    "is_empty": False,
                    "orders_count": int(s.get("order_count") or 0),
                    "warehouse_id": sw,
                    "warehouse_name": s.get("warehouse_name") or "",
                }
            )
    return out


def preview_selection_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    posting_numbers: list[str],
) -> dict[str, Any]:
    """Validate selected «Ожидают сборки» postings + compatible open supplies."""
    ensure_ozon_fbs_supply_schema(repo)
    wanted = [str(x).strip() for x in posting_numbers if str(x).strip()]
    rows = _load_postings_by_numbers(
        repo, user_id=user_id, source_id=source_id, posting_numbers=wanted
    )
    found = {str(r.get("posting_number") or "").strip() for r in rows}
    errors: list[str] = []
    missing = [n for n in wanted if n not in found]
    if missing:
        errors.append(
            "Не найдены отправления: "
            + ", ".join(missing[:10])
            + ("…" if len(missing) > 10 else "")
        )
    usable: list[dict[str, Any]] = []
    for r in rows:
        pn = str(r.get("posting_number") or "").strip()
        tab = str(r.get("tab") or "")
        if tab != oz.TAB_AWAITING_PACKAGING:
            errors.append(
                f"Отправление {pn} не во вкладке «Ожидают сборки» "
                f"(сейчас: {tab or '—'})"
            )
            continue
        if str(r.get("supply_id") or "").strip():
            errors.append(f"Отправление {pn} уже в локальной поставке")
            continue
        usable.append(r)
    mix = _selection_mix_errors(usable) if usable else (
        ["Нет подходящих отправлений"] if not errors else []
    )
    errors.extend(mix)
    seen: set[str] = set()
    uniq: list[str] = []
    for e in errors:
        if e in seen:
            continue
        seen.add(e)
        uniq.append(e)

    traits = _selection_traits(usable) if usable and not mix else {
        "warehouse_id": None,
        "warehouse_name": "",
    }
    all_open = list_open_supplies(repo, user_id=user_id, source_id=source_id)
    collect_targets = list_collect_target_supplies(
        repo, user_id=user_id, source_id=source_id
    )
    existing_names = sorted(
        {
            str(s.get("name") or "").strip()
            for s in all_open
            if str(s.get("name") or "").strip()
        }
    )
    compatible: list[dict[str, Any]] = []
    if usable and not mix:
        compatible = _compatible_supplies_for_warehouse(
            repo,
            user_id=user_id,
            source_id=source_id,
            warehouse_id=traits.get("warehouse_id"),
        )
    source_name = _source_display_name(repo, user_id=user_id, source_id=source_id)
    suggested = _unique_supply_name(
        default_supply_name(source_name=source_name), set(existing_names)
    )
    return {
        "ok": not uniq,
        "errors": uniq,
        "posting_numbers": [
            str(r.get("posting_number") or "").strip() for r in usable
        ],
        "order_count": len(usable),
        "traits": traits,
        "suggested_name": suggested,
        "name_conflict": False,
        "existing_names": existing_names,
        "compatible_supplies": compatible,
        "has_open_supplies": bool(collect_targets),
    }


def _ship_selected_postings(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    client_id: str,
    api_key: str,
    posting_numbers: list[str],
) -> tuple[list[str], list[dict[str, str]]]:
    client = oz.OzonFbsClient(client_id, api_key)
    shipped: list[str] = []
    errors: list[dict[str, str]] = []
    for pn in posting_numbers:
        try:
            oz_detail.ship_posting(
                repo,
                user_id=user_id,
                source_id=source_id,
                posting_number=pn,
                client_id=client_id,
                api_key=api_key,
                client=client,
            )
            shipped.append(pn)
        except Exception as exc:
            errors.append({"posting_number": pn, "error": str(exc)})
    return shipped, errors


def create_supply_from_selection(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    client_id: str,
    api_key: str,
    posting_numbers: list[str],
    name: str,
) -> dict[str, Any]:
    preview = preview_selection_supply(
        repo,
        user_id=user_id,
        source_id=source_id,
        posting_numbers=posting_numbers,
    )
    if not preview.get("ok"):
        return {
            "ok": False,
            "added": 0,
            "errors": list(preview.get("errors") or []),
            "message": "Нельзя создать поставку из выбранных отправлений",
            "goto_awaiting_deliver": False,
        }
    nums = list(preview.get("posting_numbers") or [])
    traits = preview.get("traits") or {}
    open_names = set(preview.get("existing_names") or [])
    supply_name = _unique_supply_name(
        str(name or "").strip() or str(preview.get("suggested_name") or ""),
        open_names,
    )
    shipped, ship_errors = _ship_selected_postings(
        repo,
        user_id=user_id,
        source_id=source_id,
        client_id=client_id,
        api_key=api_key,
        posting_numbers=nums,
    )
    if not shipped:
        return {
            "ok": False,
            "added": 0,
            "errors": [
                f"{e['posting_number']}: {e['error']}" for e in ship_errors
            ],
            "message": "Не удалось собрать отправления",
            "goto_awaiting_deliver": False,
        }
    sid = _create_local_supply(
        repo,
        user_id=user_id,
        source_id=source_id,
        name=supply_name,
        warehouse_id=traits.get("warehouse_id"),
        warehouse_name=str(traits.get("warehouse_name") or ""),
        posting_numbers=shipped,
    )
    err_lines = [f"{e['posting_number']}: {e['error']}" for e in ship_errors]
    ok = not ship_errors
    return {
        "ok": ok,
        "added": len(shipped),
        "supply_id": sid,
        "name": supply_name,
        "created_supplies": [{"supply_id": sid, "name": supply_name}],
        "errors": err_lines,
        "message": (
            f"Создана поставка «{supply_name}»: {len(shipped)} отпр."
            + (f", ошибок {len(ship_errors)}" if ship_errors else "")
        ),
        "goto_awaiting_deliver": True,
    }


def add_selection_to_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    client_id: str,
    api_key: str,
    posting_numbers: list[str],
    supply_id: str,
) -> dict[str, Any]:
    preview = preview_selection_supply(
        repo,
        user_id=user_id,
        source_id=source_id,
        posting_numbers=posting_numbers,
    )
    if not preview.get("ok"):
        return {
            "ok": False,
            "added": 0,
            "errors": list(preview.get("errors") or []),
            "message": "Нельзя добавить выбранные отправления в поставку",
            "goto_awaiting_deliver": False,
        }
    sid = str(supply_id or "").strip()
    compatible_ids = {
        str(s.get("supply_id") or "").strip()
        for s in (preview.get("compatible_supplies") or [])
    }
    if sid not in compatible_ids:
        return {
            "ok": False,
            "added": 0,
            "errors": ["Выбранная поставка не совместима со складом отправлений"],
            "message": "Поставка не подходит",
            "goto_awaiting_deliver": False,
        }
    nums = list(preview.get("posting_numbers") or [])
    shipped, ship_errors = _ship_selected_postings(
        repo,
        user_id=user_id,
        source_id=source_id,
        client_id=client_id,
        api_key=api_key,
        posting_numbers=nums,
    )
    if not shipped:
        return {
            "ok": False,
            "added": 0,
            "errors": [
                f"{e['posting_number']}: {e['error']}" for e in ship_errors
            ],
            "message": "Не удалось собрать отправления",
            "goto_awaiting_deliver": False,
        }
    _add_postings_to_supply(
        repo,
        user_id=user_id,
        source_id=source_id,
        supply_id=sid,
        posting_numbers=shipped,
    )
    sname = next(
        (
            str(s.get("name") or sid)
            for s in (preview.get("compatible_supplies") or [])
            if str(s.get("supply_id")) == sid
        ),
        sid,
    )
    err_lines = [f"{e['posting_number']}: {e['error']}" for e in ship_errors]
    return {
        "ok": not ship_errors,
        "added": len(shipped),
        "supply_id": sid,
        "name": sname,
        "errors": err_lines,
        "message": (
            f"Добавлено в «{sname}»: {len(shipped)} отпр."
            + (f", ошибок {len(ship_errors)}" if ship_errors else "")
        ),
        "goto_awaiting_deliver": True,
    }


def count_open_supplies(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> int:
    return len(list_open_supplies(repo, user_id=user_id, source_id=source_id))


def _load_orphan_tab_rows(
    repo: ReviewRepository, *, user_id: int, source_id: int, tab: str
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_supply_schema(repo)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT * FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND tab = ?
                  AND COALESCE(supply_id, '') = ''
                ORDER BY created_at_ozon DESC NULLS LAST, posting_number DESC
                """
            ),
            (user_id, source_id, str(tab)),
        ).fetchall()
    return [repo._row_to_dict(r) for r in rows]


def _load_orphan_awaiting_deliver_rows(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> list[dict[str, Any]]:
    """Postings already on Ozon «Ожидают отгрузки» but without a local supply.

    Typical after legacy ``POST /ship-all`` (ship without creating Feedpilot supply).
    """
    return _load_orphan_tab_rows(
        repo, user_id=user_id, source_id=source_id, tab=oz.TAB_AWAITING_DELIVER
    )


def adopt_orphan_awaiting_deliver_postings(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> dict[str, Any]:
    """Wrap orphan awaiting_deliver postings into local supplies (WB-like rules).

    - Same warehouse as an open non-empty supply → add there
    - Else create ``Поставка источник от ДД.ММ.ГГГГ`` (+ uniqueness)
    Does not call Ozon API — postings are already shipped.
    """
    ensure_ozon_fbs_supply_schema(repo)
    rows = _load_orphan_awaiting_deliver_rows(
        repo, user_id=user_id, source_id=source_id
    )
    if not rows:
        return {"ok": True, "adopted": 0, "created_supplies": [], "group_lines": []}

    buckets: dict[Any, list[dict[str, Any]]] = {}
    for row in rows:
        wh = row.get("warehouse_id")
        buckets.setdefault(wh, []).append(row)

    open_supplies = list_open_supplies(repo, user_id=user_id, source_id=source_id)
    open_names = {
        str(s.get("name") or "").strip()
        for s in open_supplies
        if str(s.get("name") or "").strip()
    }
    source_name = _source_display_name(repo, user_id=user_id, source_id=source_id)
    created: list[dict[str, str]] = []
    group_lines: list[str] = []
    adopted = 0

    for warehouse_id in sorted(buckets.keys(), key=lambda x: (x is None, str(x))):
        bucket = buckets[warehouse_id]
        posting_numbers = [
            str(r.get("posting_number") or "").strip()
            for r in bucket
            if str(r.get("posting_number") or "").strip()
        ]
        if not posting_numbers:
            continue
        wh_name = str(bucket[0].get("warehouse_name") or "").strip() if bucket else ""

        matching = []
        for s in open_supplies:
            if s.get("is_empty"):
                continue
            sw = s.get("warehouse_id")
            if warehouse_id is None and sw is None:
                matching.append(s)
            elif (
                warehouse_id is not None
                and sw is not None
                and int(sw) == int(warehouse_id)
            ):
                matching.append(s)

        if len(matching) == 1:
            sid = str(matching[0].get("supply_id") or "").strip()
            _add_postings_to_supply(
                repo,
                user_id=user_id,
                source_id=source_id,
                supply_id=sid,
                posting_numbers=posting_numbers,
            )
            # Keep in-memory open list in sync for later buckets.
            matching[0]["posting_numbers"] = list(matching[0].get("posting_numbers") or []) + [
                n for n in posting_numbers if n not in (matching[0].get("posting_numbers") or [])
            ]
            matching[0]["order_count"] = len(matching[0]["posting_numbers"])
            matching[0]["is_empty"] = False
            sname = str(matching[0].get("name") or sid)
            group_lines.append(f"{sname}: +{len(posting_numbers)} отпр. (осиротевшие)")
            adopted += len(posting_numbers)
            continue

        if len(matching) > 1:
            # Prefer the newest open supply for this warehouse.
            sid = str(matching[0].get("supply_id") or "").strip()
            _add_postings_to_supply(
                repo,
                user_id=user_id,
                source_id=source_id,
                supply_id=sid,
                posting_numbers=posting_numbers,
            )
            sname = str(matching[0].get("name") or sid)
            group_lines.append(f"{sname}: +{len(posting_numbers)} отпр. (осиротевшие)")
            adopted += len(posting_numbers)
            continue

        name = _unique_supply_name(
            default_supply_name(source_name=source_name), open_names
        )
        sid = _create_local_supply(
            repo,
            user_id=user_id,
            source_id=source_id,
            name=name,
            warehouse_id=warehouse_id,
            warehouse_name=wh_name,
            posting_numbers=posting_numbers,
        )
        open_names.add(name)
        open_supplies.append(
            {
                "supply_id": sid,
                "name": name,
                "warehouse_id": warehouse_id,
                "warehouse_name": wh_name,
                "is_empty": False,
                "order_count": len(posting_numbers),
                "posting_numbers": list(posting_numbers),
            }
        )
        created.append({"supply_id": sid, "name": name})
        group_lines.append(f"{name}: {len(posting_numbers)} отпр. (осиротевшие)")
        adopted += len(posting_numbers)

    return {
        "ok": True,
        "adopted": adopted,
        "created_supplies": created,
        "group_lines": group_lines,
    }


    return {
        "ok": True,
        "adopted": adopted,
        "created_supplies": created,
        "group_lines": group_lines,
    }


def _find_supply_by_name(
    repo: ReviewRepository, *, user_id: int, source_id: int, name: str
) -> dict[str, Any] | None:
    ensure_ozon_fbs_supply_schema(repo)
    target = str(name or "").strip()
    if not target:
        return None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM ozon_fbs_supplies
                WHERE user_id = ? AND source_id = ? AND name = ?
                  AND COALESCE(done, FALSE) = FALSE
                ORDER BY created_at DESC
                LIMIT 1
                """
            ),
            (user_id, source_id, target),
        ).fetchone()
    return repo._row_to_dict(row) if row else None


def adopt_orphan_delivering_postings(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> dict[str, Any]:
    """Wrap orphan delivering postings into «Без локальной поставки»."""
    ensure_ozon_fbs_supply_schema(repo)
    rows = _load_orphan_tab_rows(
        repo, user_id=user_id, source_id=source_id, tab=oz.TAB_DELIVERING
    )
    if not rows:
        return {"ok": True, "adopted": 0, "created_supplies": [], "group_lines": []}

    posting_numbers = [
        str(r.get("posting_number") or "").strip()
        for r in rows
        if str(r.get("posting_number") or "").strip()
    ]
    if not posting_numbers:
        return {"ok": True, "adopted": 0, "created_supplies": [], "group_lines": []}

    wh_name = str(rows[0].get("warehouse_name") or "").strip()
    wh_id = rows[0].get("warehouse_id")
    existing = _find_supply_by_name(
        repo,
        user_id=user_id,
        source_id=source_id,
        name=ORPHAN_DELIVERING_SUPPLY_NAME,
    )
    created: list[dict[str, str]] = []
    if existing:
        sid = str(existing.get("supply_id") or "").strip()
        _link_postings_to_supply_only(
            repo,
            user_id=user_id,
            source_id=source_id,
            supply_id=sid,
            posting_numbers=posting_numbers,
        )
        group_line = (
            f"{ORPHAN_DELIVERING_SUPPLY_NAME}: +{len(posting_numbers)} отпр. (осиротевшие)"
        )
    else:
        open_names = {
            str(s.get("name") or "").strip()
            for s in list_open_supplies(repo, user_id=user_id, source_id=source_id)
            if str(s.get("name") or "").strip()
        }
        name = _unique_supply_name(ORPHAN_DELIVERING_SUPPLY_NAME, open_names)
        sid = _create_local_supply(
            repo,
            user_id=user_id,
            source_id=source_id,
            name=name,
            warehouse_id=wh_id,
            warehouse_name=wh_name,
            posting_numbers=posting_numbers,
            force_tab=None,
        )
        created.append({"supply_id": sid, "name": name})
        group_line = f"{name}: {len(posting_numbers)} отпр. (осиротевшие)"

    return {
        "ok": True,
        "adopted": len(posting_numbers),
        "created_supplies": created,
        "group_lines": [group_line],
    }


def _build_supply_items_for_tab(
    repo: ReviewRepository, *, user_id: int, source_id: int, tab: str
) -> list[dict[str, Any]]:
    """Supply cards grouped by ``ozon_fbs_postings.supply_id`` for the given tab."""
    ensure_ozon_fbs_supply_schema(repo)
    tab_key = str(tab or "").strip()
    if not tab_key:
        return []
    with repo._connect() as conn:
        groups = conn.execute(
            repo._sql(
                """
                SELECT supply_id,
                       COUNT(*) AS order_count,
                       MAX(warehouse_name) AS warehouse_name,
                       MAX(warehouse_id) AS warehouse_id,
                       MAX(created_at_ozon) AS last_posting_at
                FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND tab = ?
                  AND COALESCE(supply_id, '') != ''
                GROUP BY supply_id
                ORDER BY last_posting_at DESC NULLS LAST, supply_id DESC
                """
            ),
            (user_id, source_id, tab_key),
        ).fetchall()

    if not groups:
        return []

    supply_ids = [
        str(g["supply_id"] if hasattr(g, "keys") else g[0]).strip()
        for g in groups
        if str(g["supply_id"] if hasattr(g, "keys") else g[0]).strip()
    ]
    meta: dict[str, dict[str, Any]] = {}
    if supply_ids:
        placeholders = ", ".join("?" for _ in supply_ids)
        with repo._connect() as conn:
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT supply_id, name, warehouse_name, warehouse_id, created_at
                    FROM ozon_fbs_supplies
                    WHERE user_id = ? AND source_id = ?
                      AND supply_id IN ({placeholders})
                    """
                ),
                (user_id, source_id, *supply_ids),
            ).fetchall()
        for row in rows:
            d = repo._row_to_dict(row)
            sid = str(d.get("supply_id") or "").strip()
            if sid:
                meta[sid] = d

    status_label = _TAB_SUPPLY_STATUS_LABEL.get(tab_key, tab_key)
    items: list[dict[str, Any]] = []
    for g in groups:
        d = repo._row_to_dict(g)
        sid = str(d.get("supply_id") or "").strip()
        if not sid:
            continue
        try:
            order_count = int(d.get("order_count") or 0)
        except (TypeError, ValueError):
            order_count = 0
        if order_count <= 0:
            continue
        sm = meta.get(sid) or {}
        items.append(
            {
                "supply_id": sid,
                "name": sm.get("name") or sid,
                "order_count": order_count,
                "warehouse_label": sm.get("warehouse_name")
                or d.get("warehouse_name")
                or "—",
                "warehouse_id": sm.get("warehouse_id") if sm else d.get("warehouse_id"),
                "status_label": status_label,
                "created_at": sm.get("created_at") or d.get("last_posting_at"),
            }
        )
    return items


def _list_supplies_tab_response(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    tab: str,
    adopt_info: dict[str, Any],
) -> dict[str, Any]:
    items = _build_supply_items_for_tab(
        repo, user_id=user_id, source_id=source_id, tab=tab
    )
    return {
        "items": items,
        "total": len(items),
        "counts": oz._tab_counts(repo, user_id=user_id, source_id=source_id),
        "adopted_orphans": int(adopt_info.get("adopted") or 0),
        "adopt_created_supplies": adopt_info.get("created_supplies") or [],
    }


def list_awaiting_deliver_supplies(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> dict[str, Any]:
    """Supplies shown on «Ожидают отгрузки».

    Auto-adopts orphan postings (shipped before local supplies existed).
    """
    ensure_ozon_fbs_supply_schema(repo)
    adopt_info = adopt_orphan_awaiting_deliver_postings(
        repo, user_id=user_id, source_id=source_id
    )
    return _list_supplies_tab_response(
        repo,
        user_id=user_id,
        source_id=source_id,
        tab=oz.TAB_AWAITING_DELIVER,
        adopt_info=adopt_info,
    )


def list_delivering_supplies(
    repo: ReviewRepository, *, user_id: int, source_id: int
) -> dict[str, Any]:
    """Supplies shown on «Доставляются» (read-only drill-down in UI)."""
    ensure_ozon_fbs_supply_schema(repo)
    adopt_info = adopt_orphan_delivering_postings(
        repo, user_id=user_id, source_id=source_id
    )
    return _list_supplies_tab_response(
        repo,
        user_id=user_id,
        source_id=source_id,
        tab=oz.TAB_DELIVERING,
        adopt_info=adopt_info,
    )


def get_supply(
    repo: ReviewRepository, *, user_id: int, source_id: int, supply_id: str
) -> dict[str, Any] | None:
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    if not sid:
        return None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM ozon_fbs_supplies
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (user_id, source_id, sid),
        ).fetchone()
    if not row:
        return None
    d = repo._row_to_dict(row)
    nums = [
        str(x).strip()
        for x in _parse_json_list(d.get("posting_numbers_json"))
        if str(x).strip()
    ]
    d["posting_numbers"] = nums
    d["order_count"] = len(nums)
    return d


def rename_local_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    name: str,
) -> dict[str, Any]:
    """Rename a local Ozon FBS supply. Name is kept when postings move to delivering."""
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    new_name = str(name or "").strip()
    if not sid:
        raise ValueError("Не указан ID поставки")
    if not new_name:
        raise ValueError("Укажите название поставки")
    if len(new_name) > 128:
        raise ValueError("Название не длиннее 128 символов")

    supply = get_supply(repo, user_id=user_id, source_id=source_id, supply_id=sid)
    if not supply:
        raise RuntimeError("Поставка не найдена")
    if bool(supply.get("done")):
        raise RuntimeError("Нельзя переименовать закрытую поставку")

    open_names = {
        str(s.get("name") or "").strip()
        for s in list_open_supplies(repo, user_id=user_id, source_id=source_id)
        if str(s.get("supply_id") or "").strip() != sid
        and str(s.get("name") or "").strip()
    }
    if new_name in open_names:
        raise ValueError(f"Поставка «{new_name}» уже есть — выберите другое название")

    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                UPDATE ozon_fbs_supplies
                SET name = ?, updated_at = NOW()
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                """
            ),
            (new_name, user_id, source_id, sid),
        )
    updated = get_supply(repo, user_id=user_id, source_id=source_id, supply_id=sid)
    if not updated:
        raise RuntimeError("Поставка не найдена после переименования")
    return {
        "ok": True,
        "supply_id": sid,
        "name": str(updated.get("name") or new_name).strip(),
    }


def _assembly_posting_numbers_for_supply_tab(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    tab: str,
) -> list[str]:
    """Posting numbers for a supply limited to one Ozon tab."""
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    tab_key = str(tab or "").strip()
    if not sid or not tab_key:
        return []
    nums: list[str] = []
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT posting_number FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND supply_id = ? AND tab = ?
                ORDER BY posting_number ASC
                """
            ),
            (user_id, source_id, sid, tab_key),
        ).fetchall()
    for row in rows:
        pn = str(row["posting_number"] if hasattr(row, "keys") else row[0]).strip()
        if pn:
            nums.append(pn)
    return nums


def _assembly_posting_numbers_for_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
) -> list[str]:
    """Posting numbers linked to a supply in ``ozon_fbs_postings`` (assembly truth)."""
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    if not sid:
        return []
    nums: list[str] = []
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT posting_number FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                ORDER BY posting_number ASC
                """
            ),
            (user_id, source_id, sid),
        ).fetchall()
    for row in rows:
        pn = str(row["posting_number"] if hasattr(row, "keys") else row[0]).strip()
        if pn:
            nums.append(pn)
    return nums


def print_posting_numbers_mismatch_message(
    *, supply_count: int, assembly_count: int
) -> str:
    """User-facing block reason when supply JSON composition ≠ assembly links."""
    return (
        "Количество заказов в листе подбора / стикерах не совпадает с заказами "
        f"на сборке (в поставке: {int(supply_count)}, на сборке: {int(assembly_count)}). "
        "Печать заблокирована. Выполните синхронизацию и сбор заказов, затем снова "
        "откройте поставку."
    )


def ensure_supply_ready_for_print(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    kind: str = "print",
) -> list[str]:
    """Require supply JSON posting list to match assembly links before print.

    Returns posting numbers in supply-record order when sets match.
    Raises ``ValueError`` when sets differ — callers must not print.
    """
    sid = str(supply_id or "").strip()
    if not sid:
        raise ValueError("Укажите supply_id")
    kind_label = str(kind or "print").strip() or "print"

    supply = get_supply(repo, user_id=user_id, source_id=source_id, supply_id=sid)
    if not supply:
        raise ValueError("Поставка не найдена")
    supply_nums = [
        str(x).strip()
        for x in (supply.get("posting_numbers") or [])
        if str(x).strip()
    ]
    assembly_nums = _assembly_posting_numbers_for_supply(
        repo, user_id=user_id, source_id=source_id, supply_id=sid
    )
    supply_set = set(supply_nums)
    assembly_set = set(assembly_nums)
    if supply_set == assembly_set:
        _log.info(
            "ozon print ok supply=%s source=%s kind=%s supply=%s assembly=%s",
            sid,
            source_id,
            kind_label,
            len(supply_set),
            len(assembly_set),
        )
        return supply_nums

    _log.warning(
        "ozon print blocked supply=%s source=%s kind=%s supply=%s assembly=%s "
        "missing_on_supply=%s extra_on_supply=%s",
        sid,
        source_id,
        kind_label,
        len(supply_set),
        len(assembly_set),
        len(assembly_set - supply_set),
        len(supply_set - assembly_set),
    )
    raise ValueError(
        print_posting_numbers_mismatch_message(
            supply_count=len(supply_set),
            assembly_count=len(assembly_set),
        )
    )


def get_supply_detail_for_print(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    kind: str = "print",
) -> dict[str, Any]:
    """Detail for print: verify supply↔assembly composition, then load orders."""
    sid = str(supply_id or "").strip()
    verified = ensure_supply_ready_for_print(
        repo,
        user_id=user_id,
        source_id=source_id,
        supply_id=sid,
        kind=kind,
    )
    return get_supply_detail(
        repo,
        user_id=user_id,
        source_id=source_id,
        supply_id=sid,
        posting_numbers=verified,
    )



def delivery_method_for_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
) -> dict[str, Any] | None:
    """Resolve Ozon delivery method {id, name} from the first posting in supply."""
    ensure_ozon_fbs_supply_schema(repo)
    sid = str(supply_id or "").strip()
    if not sid:
        return None
    nums = _assembly_posting_numbers_for_supply(
        repo, user_id=user_id, source_id=source_id, supply_id=sid
    )
    if not nums:
        return None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT raw_json FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND posting_number = ?
                """
            ),
            (user_id, source_id, nums[0]),
        ).fetchone()
    if not row:
        return None
    raw = row["raw_json"] if hasattr(row, "keys") else row[0]
    try:
        posting = json.loads(str(raw or "{}"))
    except json.JSONDecodeError:
        return None
    if not isinstance(posting, dict):
        return None
    dm = posting.get("delivery_method")
    if isinstance(dm, dict):
        try:
            mid = int(dm.get("id") or dm.get("delivery_method_id") or 0)
        except (TypeError, ValueError):
            mid = 0
        name = str(
            dm.get("name")
            or dm.get("delivery_method_name")
            or posting.get("tpl_provider_name")
            or ""
        ).strip()
        if mid > 0:
            return {"id": mid, "name": name or f"Метод {mid}"}
    return None


def delivery_method_id_for_supply(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
) -> int | None:
    """Resolve Ozon delivery_method.id from the first posting linked to the supply."""
    info = delivery_method_for_supply(
        repo, user_id=user_id, source_id=source_id, supply_id=supply_id
    )
    if not info:
        return None
    try:
        mid = int(info.get("id") or 0)
        return mid if mid > 0 else None
    except (TypeError, ValueError):
        return None


def refresh_supply_postings_from_ozon(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    posting_numbers: list[str],
    client_id: str,
    api_key: str,
) -> None:
    """Full live Ozon refresh (get_posting) — use sparingly (?refresh=1 on detail)."""
    nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    if not nums or not str(client_id or "").strip() or not str(api_key or "").strip():
        return
    client = oz.OzonFbsClient(str(client_id).strip(), str(api_key).strip())
    for i, pn in enumerate(nums):
        try:
            remote = client.get_posting(pn)
            if isinstance(remote, dict):
                remote = oz.enrich_posting_marking_flags(client, remote)
                oz.upsert_posting(
                    repo,
                    user_id=user_id,
                    source_id=source_id,
                    posting=remote,
                )
        except Exception as exc:
            _log.warning("ozon supply detail refresh %s: %s", pn, exc)
        if i + 1 < len(nums):
            time.sleep(0.05)




def refresh_supply_marking_flags_from_ozon(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    posting_numbers: list[str],
    client_id: str,
    api_key: str,
) -> int:
    """Light Ozon refresh: mandatory-mark/is-required only (no get_posting, no create-or-get)."""
    nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    if not nums or not str(client_id or "").strip() or not str(api_key or "").strip():
        return 0
    client = oz.OzonFbsClient(str(client_id).strip(), str(api_key).strip())
    placeholders = ", ".join("?" for _ in nums)
    updated = 0
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                f"""
                SELECT * FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ?
                  AND posting_number IN ({placeholders})
                """
            ),
            (user_id, source_id, *nums),
        ).fetchall()
    by_pn = {
        str(repo._row_to_dict(row).get("posting_number") or "").strip(): repo._row_to_dict(row)
        for row in rows
    }
    for i, pn in enumerate(nums):
        row = by_pn.get(pn)
        if not row:
            continue
        posting = oz._posting_payload_from_row(row)
        if not posting or oz.posting_marking_flags_resolved(posting):
            continue
        try:
            enriched = oz.enrich_posting_marking_flags_light(client, posting)
            oz.upsert_posting(
                repo,
                user_id=user_id,
                source_id=source_id,
                posting=enriched,
            )
            updated += 1
        except Exception as exc:
            _log.warning("ozon supply marking enrich %s: %s", pn, exc)
        if i + 1 < len(nums):
            time.sleep(0.05)
    return updated


def resolve_supply_kiz_flags_from_ozon(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    client_id: str,
    api_key: str,
    posting_tab: str | None = None,
) -> int:
    """Resolve КИЗ flags for all non-cancelled supply postings (marking modal)."""
    sid = str(supply_id or "").strip()
    if not sid:
        return 0
    tab_key = str(posting_tab or "").strip() or None
    if tab_key:
        nums = _assembly_posting_numbers_for_supply_tab(
            repo,
            user_id=user_id,
            source_id=source_id,
            supply_id=sid,
            tab=tab_key,
        )
    else:
        nums = _assembly_posting_numbers_for_supply(
            repo, user_id=user_id, source_id=source_id, supply_id=sid
        )
    if not nums:
        return 0
    detail = get_supply_detail(
        repo,
        user_id=user_id,
        source_id=source_id,
        supply_id=sid,
        posting_tab=tab_key,
    )
    active: list[str] = []
    for o in detail.get("orders") or []:
        if not isinstance(o, dict) or oz.posting_row_is_cancelled(o):
            continue
        pn = str(o.get("posting_number") or "").strip()
        if pn:
            active.append(pn)
    if not active:
        active = list(nums)
    return refresh_supply_marking_flags_from_ozon(
        repo,
        user_id=user_id,
        source_id=source_id,
        posting_numbers=active,
        client_id=client_id,
        api_key=api_key,
    )


def _supply_stub_from_assembly(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    tab: str | None = None,
) -> dict[str, Any] | None:
    """Build minimal supply dict from assembly links when ozon_fbs_supplies row is missing."""
    sid = str(supply_id or "").strip()
    if not sid:
        return None
    tab_key = str(tab or "").strip() or None
    if tab_key:
        nums = _assembly_posting_numbers_for_supply_tab(
            repo,
            user_id=user_id,
            source_id=source_id,
            supply_id=sid,
            tab=tab_key,
        )
    else:
        nums = _assembly_posting_numbers_for_supply(
            repo, user_id=user_id, source_id=source_id, supply_id=sid
        )
    if not nums:
        return None
    wh_name = ""
    wh_id = None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT warehouse_name, warehouse_id
                FROM ozon_fbs_postings
                WHERE user_id = ? AND source_id = ? AND supply_id = ?
                LIMIT 1
                """
            ),
            (user_id, source_id, sid),
        ).fetchone()
    if row:
        d = repo._row_to_dict(row)
        wh_name = str(d.get("warehouse_name") or "").strip()
        wh_id = d.get("warehouse_id")
    return {
        "supply_id": sid,
        "name": sid,
        "warehouse_name": wh_name,
        "warehouse_id": wh_id,
        "posting_numbers": nums,
        "order_count": len(nums),
    }


def get_supply_detail(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    posting_numbers: list[str] | None = None,
    posting_tab: str | None = None,
    client_id: str | None = None,
    api_key: str | None = None,
    refresh_from_ozon: bool = False,
) -> dict[str, Any]:
    tab_filter = str(posting_tab or "").strip() or None
    supply = get_supply(repo, user_id=user_id, source_id=source_id, supply_id=supply_id)
    if not supply:
        supply = _supply_stub_from_assembly(
            repo,
            user_id=user_id,
            source_id=source_id,
            supply_id=str(supply_id),
            tab=tab_filter,
        )
    if not supply:
        raise RuntimeError("Поставка не найдена")
    if posting_numbers is not None:
        nums = [str(x).strip() for x in posting_numbers if str(x).strip()]
    elif tab_filter:
        nums = _assembly_posting_numbers_for_supply_tab(
            repo,
            user_id=user_id,
            source_id=source_id,
            supply_id=str(supply_id),
            tab=tab_filter,
        )
    else:
        nums = _assembly_posting_numbers_for_supply(
            repo, user_id=user_id, source_id=source_id, supply_id=str(supply_id)
        )
        if not nums:
            nums = list(supply.get("posting_numbers") or [])
    read_only = tab_filter == oz.TAB_DELIVERING
    if (
        refresh_from_ozon
        and not read_only
        and nums
        and client_id
        and api_key
    ):
        refresh_supply_postings_from_ozon(
            repo,
            user_id=user_id,
            source_id=source_id,
            posting_numbers=nums,
            client_id=str(client_id),
            api_key=str(api_key),
        )
    name_map = repo.get_product_name_by_article(user_id=user_id)
    ozon_sku_map = repo.get_product_name_by_ozon_sku(user_id=user_id)
    barcode_map = repo.get_product_barcodes_map(user_id=user_id)
    photo_map = repo.get_product_photo_map(user_id=user_id)
    orders: list[dict[str, Any]] = []
    if nums:
        placeholders = ", ".join("?" for _ in nums)
        with repo._connect() as conn:
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT * FROM ozon_fbs_postings
                    WHERE user_id = ? AND source_id = ?
                      AND posting_number IN ({placeholders})
                    ORDER BY posting_number
                    """
                ),
                (user_id, source_id, *nums),
            ).fetchall()
        for row in rows:
            d = repo._row_to_dict(row)
            article = str(d.get("offer_id") or "").strip()
            sku = str(d.get("sku") or "").strip()
            d["product_name"] = oz.resolve_product_display_name(
                offer_id=article,
                sku=sku,
                name_by_article=name_map,
                name_by_ozon_sku=ozon_sku_map,
            )
            d["barcodes"] = oz.resolve_product_barcodes(
                offer_id=article,
                sku=sku,
                barcode_map=barcode_map,
                fallback=_parse_json_list(d.get("barcodes_json")),
            )
            d["product_photo"] = photo_map.get(article) or photo_map.get(sku) or ""
            d["warehouse_label"] = d.get("warehouse_name") or "—"
            cancel_label = oz.cancel_reason_label_from_row(d)
            d["cancel_reason_label"] = cancel_label
            d["cancelled"] = bool(cancel_label)
            d["kiz_required"] = oz.posting_requires_marking(d) and not d["cancelled"]
            d["kiz_quantity"] = oz.posting_marking_quantity(d) if d["kiz_required"] else 0
            if d["kiz_required"]:
                try:
                    parsed_codes = json.loads(str(d.get("marking_codes_json") or "[]"))
                except json.JSONDecodeError:
                    parsed_codes = []
                if not isinstance(parsed_codes, list):
                    parsed_codes = []
                codes_clean = [
                    wb._kiz_code_clean(x) for x in parsed_codes if wb._kiz_code_clean(x)
                ]
                req_qty = int(d["kiz_quantity"] or 1)
                if len(codes_clean) >= req_qty:
                    d["kiz_status"] = "ok"
                elif codes_clean:
                    d["kiz_status"] = "pending"
                else:
                    d["kiz_status"] = "empty"
            else:
                d["kiz_status"] = "empty"
            sticker = oz.posting_sticker_payload_from_row(d)
            d.update(sticker)
            orders.append(d)
    return {
        "supply_id": supply.get("supply_id"),
        "name": supply.get("name"),
        "warehouse_label": supply.get("warehouse_name") or "—",
        "order_count": len(orders),
        "orders": orders,
        "source_id": source_id,
        "read_only": read_only,
        "posting_tab": tab_filter,
    }


def _fmt_posting_date(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return "—"
    if "T" in text:
        return text.split("T", 1)[0]
    return text[:10] if len(text) >= 10 else text


def _posting_row_payload(row: dict[str, Any]) -> dict[str, Any]:
    pn = str(row.get("posting_number") or "").strip()
    created = row.get("created_at_ozon") or row.get("in_process_at")
    return {
        "posting_number": pn,
        "created_date": _fmt_posting_date(created),
        "product_name": str(row.get("product_name") or row.get("offer_id") or ""),
        "product_photo": str(row.get("product_photo") or ""),
        "offer_id": str(row.get("offer_id") or ""),
        "sku": row.get("sku"),
        "barcodes": list(row.get("barcodes") or []),
        "status": str(row.get("status") or ""),
        "tab": str(row.get("tab") or ""),
        "cancelled": True,
        "cancel_reason_label": str(row.get("cancel_reason_label") or "Отменено"),
    }


def list_supply_cancelled_postings(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    client_id: str,
    api_key: str,
) -> dict[str, Any]:
    """Live Ozon get_posting check for cancelled postings still in a local supply."""
    sid = str(supply_id or "").strip()
    if not sid:
        raise ValueError("Укажите supply_id")
    if not client_id or not api_key:
        raise ValueError("Нет API-ключей источника Ozon")

    supply = get_supply(repo, user_id=user_id, source_id=source_id, supply_id=sid)
    if not supply:
        raise RuntimeError("Поставка не найдена")
    posting_numbers = [
        str(x).strip()
        for x in (supply.get("posting_numbers") or [])
        if str(x).strip()
    ]
    if not posting_numbers:
        return {
            "ok": True,
            "supply_id": sid,
            "source_id": int(source_id),
            "posting_count": 0,
            "cancelled_count": 0,
            "rows": [],
        }

    detail = get_supply_detail(
        repo, user_id=user_id, source_id=source_id, supply_id=sid
    )
    local_by_pn: dict[str, dict[str, Any]] = {}
    for o in detail.get("orders") or []:
        if not isinstance(o, dict):
            continue
        pn = str(o.get("posting_number") or "").strip()
        if pn:
            local_by_pn[pn] = o

    client = oz.OzonFbsClient(client_id, api_key)
    refreshed: dict[str, dict[str, Any]] = {}
    fetch_errors: list[str] = []
    for pn in posting_numbers:
        try:
            remote = client.get_posting(pn)
            if isinstance(remote, dict):
                refreshed[pn] = remote
                try:
                    oz.upsert_posting(
                        repo,
                        user_id=user_id,
                        source_id=source_id,
                        posting=remote,
                    )
                except Exception as exc:
                    _log.debug("cancelled persist %s: %s", pn, exc)
        except Exception as exc:
            fetch_errors.append(f"{pn}: {exc}")
            _log.warning("ozon cancelled check get_posting %s: %s", pn, exc)
        if len(posting_numbers) > 1:
            time.sleep(0.05)

    if fetch_errors and len(refreshed) == 0 and not local_by_pn:
        raise RuntimeError(
            "Не удалось проверить статусы отправлений на Ozon: "
            + "; ".join(fetch_errors[:3])
        )

    rows: list[dict[str, Any]] = []
    for pn in posting_numbers:
        remote = refreshed.get(pn) or {}
        local = dict(local_by_pn.get(pn) or {})
        if remote:
            label = oz.cancel_reason_label_from_posting(remote)
            status = str(remote.get("status") or "").strip().lower()
            tab = oz.compute_tab(status)
            cancelled = oz.is_cancelled_posting(status=status, tab=tab)
        else:
            label = oz.cancel_reason_label_from_row(local)
            cancelled = bool(label) or oz.is_cancelled_posting(
                status=local.get("status"), tab=local.get("tab")
            )
            if cancelled and not label:
                label = "Отменено"
        if not cancelled:
            continue
        if remote:
            local["status"] = str(remote.get("status") or local.get("status") or "")
            local["tab"] = oz.compute_tab(local.get("status"))
        local["cancel_reason_label"] = label or "Отменено"
        local["cancelled"] = True
        rows.append(_posting_row_payload(local))

    return {
        "ok": True,
        "supply_id": sid,
        "source_id": int(source_id),
        "posting_count": len(posting_numbers),
        "cancelled_count": len(rows),
        "rows": rows,
        "warnings": fetch_errors[:5] if fetch_errors else [],
    }


def _orders_excluding_cancelled(orders: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Fulfillment lists (picking, stickers) skip cancelled postings."""
    return [
        o
        for o in (orders or [])
        if isinstance(o, dict) and not oz.posting_row_is_cancelled(o)
    ]


def _group_postings_by_article(orders: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, dict[str, Any]] = {}
    order_list: list[str] = []
    for o in orders:
        article = str(o.get("offer_id") or "").strip() or "—"
        if article not in groups:
            order_list.append(article)
            groups[article] = {
                "article": article,
                "product_name": o.get("product_name") or article,
                "nm_id": o.get("sku") or "—",
                "barcodes": list(o.get("barcodes") or []),
                "orders": [],
                "qty": 0,
            }
        g = groups[article]
        g["orders"].append(o)
        g["qty"] = len(g["orders"])
        if not g.get("product_name"):
            g["product_name"] = o.get("product_name") or article
        if not g.get("barcodes") and o.get("barcodes"):
            g["barcodes"] = list(o.get("barcodes") or [])
    return [groups[k] for k in order_list]


def render_picking_list_html(detail: dict[str, Any]) -> str:
    active_orders = _orders_excluding_cancelled(list(detail.get("orders") or []))
    groups = _group_postings_by_article(active_orders)
    total = sum(int(g.get("qty") or 0) for g in groups)
    sid = _esc(detail.get("supply_id"))
    name = _esc(detail.get("name") or sid)
    rows = []
    for g in groups:
        pname = _esc(g.get("product_name") or g.get("article") or "—")
        qty = int(g.get("qty") or 0)
        rows.append(
            f'<tr class="summary-row"><td class="main">{pname} — {qty} шт.</td>'
            f'<td class="check"><span class="box"></span></td></tr>'
        )
    body = "\n".join(rows) if rows else '<tr><td colspan="2">Нет заказов</td></tr>'
    return f"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"/>
<title>Лист подбора {name}</title>
<style>
  @page {{ size: A4; margin: 12mm; }}
  body {{ font-family: Arial, sans-serif; color: #0f172a; font-size: 14px; }}
  h1 {{ font-size: 18px; margin: 0 0 8px; }}
  .meta {{ color: #64748b; margin-bottom: 16px; }}
  table.picking {{ width: 100%; border-collapse: collapse; }}
  table.picking th, table.picking td {{
    border-bottom: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; vertical-align: middle;
  }}
  table.picking .check {{ width: 88px; text-align: center; }}
  .box {{
    display: inline-block; width: 16px; height: 16px; border: 1.5px solid #94a3b8; border-radius: 3px;
  }}
  .totals-row th {{ background: #f8fafc; font-weight: 700; }}
  .toolbar {{ margin-bottom: 12px; }}
  @media print {{ .toolbar {{ display: none !important; }} }}
</style></head><body>
  <div class="toolbar"><button onclick="window.print()">Печать</button></div>
  <h1>Лист подбора — {name}</h1>
  <div class="meta">Поставка {sid} · склад {_esc(detail.get("warehouse_label"))}</div>
  <table class="picking summary">
    <tbody>
      <tr class="totals-row"><th class="main">Всего {total} отпр.</th><th class="check">Собрано</th></tr>
      {body}
    </tbody>
  </table>
  <script>window.addEventListener('load',function(){{ setTimeout(function(){{ window.print(); }}, 200); }});</script>
</body></html>"""


_OZON_LABEL_BATCH = 20
_PRINTABLE_LABEL_TABS = frozenset(
    {
        oz.TAB_AWAITING_PACKAGING,
        oz.TAB_AWAITING_DELIVER,
        oz.TAB_DELIVERING,
    }
)


def _is_pymupdf_setup_error(exc: BaseException) -> bool:
    if isinstance(exc, ImportError):
        return True
    return "pymupdf" in str(exc).casefold()


def _fetch_label_pages_for_posting(
    client: oz.OzonFbsClient, posting_number: str
) -> list[str]:
    pn = str(posting_number or "").strip()
    if not pn:
        return []
    try:
        pdf = client.package_label_pdf([pn])
        return _pdf_pages_to_png_b64(pdf)
    except Exception as exc:
        if _is_pymupdf_setup_error(exc):
            raise
        _log.warning("ozon package-label %s: %s", pn, exc)
        return []


def _pdf_pages_to_png_b64(pdf_bytes: bytes) -> list[str]:
    try:
        import pymupdf
    except ImportError as exc:
        raise RuntimeError(
            "Для печати стикеров Ozon нужен пакет pymupdf "
            "(pip install pymupdf). Сейчас он не установлен на сервере."
        ) from exc

    doc = pymupdf.open(stream=pdf_bytes, filetype="pdf")
    out: list[str] = []
    try:
        for page in doc:
            pix = page.get_pixmap(matrix=pymupdf.Matrix(2, 2), alpha=False)
            out.append(base64.b64encode(pix.tobytes("png")).decode("ascii"))
    finally:
        doc.close()
    return out


def _fetch_label_images(
    client: oz.OzonFbsClient, posting_numbers: list[str]
) -> dict[str, list[str]]:
    """Rasterize Ozon «Этикетка отправления» PDF pages (batch ≤20)."""
    result: dict[str, list[str]] = {pn: [] for pn in posting_numbers}
    for i in range(0, len(posting_numbers), _OZON_LABEL_BATCH):
        batch = posting_numbers[i : i + _OZON_LABEL_BATCH]
        if not batch:
            continue
        try:
            pdf = client.package_label_pdf(batch)
            pages = _pdf_pages_to_png_b64(pdf)
        except Exception as exc:
            if _is_pymupdf_setup_error(exc):
                raise
            _log.warning("ozon package-label batch failed (%s): %s", len(batch), exc)
            for pn in batch:
                result[pn] = _fetch_label_pages_for_posting(client, pn)
            continue
        # Ozon returns pages in request order; typically 1 page per posting.
        if len(pages) == len(batch):
            for pn, page in zip(batch, pages):
                result[pn] = [page]
        elif len(pages) == 0:
            for pn in batch:
                result[pn] = []
        else:
            # Uneven page count — assign sequentially, leftover pages on last.
            idx = 0
            for bi, pn in enumerate(batch):
                remaining_postings = len(batch) - bi
                remaining_pages = len(pages) - idx
                take = max(1, remaining_pages // remaining_postings) if remaining_pages else 0
                chunk = pages[idx : idx + take]
                idx += take
                result[pn] = chunk
            if idx < len(pages) and batch:
                result[batch[-1]] = (result.get(batch[-1]) or []) + pages[idx:]
    return result


def render_stickers_print_html(
    detail: dict[str, Any],
    *,
    source_name: str,
    label_images: dict[str, list[str]],
    order_ids_filter: list[str] | None = None,
    missing_posting_numbers: list[str] | None = None,
) -> str:
    orders = list(detail.get("orders") or [])
    if order_ids_filter is not None:
        allowed = {str(x).strip() for x in order_ids_filter if str(x).strip()}
        orders = [o for o in orders if str(o.get("posting_number") or "").strip() in allowed]
    groups = _group_postings_by_article(orders)
    supply_name = str(detail.get("name") or detail.get("supply_id") or "Поставка").strip()
    sticker_count = 0
    for g in groups:
        for o in g.get("orders") or []:
            pn = str(o.get("posting_number") or "").strip()
            imgs = label_images.get(pn) or []
            sticker_count += len(imgs) if imgs else 1

    pages: list[str] = []
    page_no = 0
    if groups:
        page_no += 1
        src_line = (
            f'<div class="cover-source">{_esc(source_name)}</div>' if source_name else ""
        )
        pages.append(
            f"""
            <section class="label cover">
              <div class="cover-label">Поставка</div>
              <div class="cover-name">{_esc(supply_name)}</div>
              {src_line}
              <div class="cover-qty">{sticker_count} стик.</div>
            </section>
            """
        )
    for g in groups:
        qty = int(g.get("qty") or 0)
        article = str(g.get("article") or "")
        pname = str(g.get("product_name") or "").strip() or "—"
        barcodes = g.get("barcodes") or []
        barcode = str(barcodes[0] if barcodes else "")
        nm = g.get("nm_id") or "—"
        page_no += 1
        pages.append(
            f"""
            <section class="label separator">
              <div class="qty">{qty} шт.</div>
              <div class="title">{_esc(pname)}</div>
              <div class="line">SKU Ozon: {_esc(nm)}</div>
              <div class="line">Баркод: {_esc(barcode or "—")}</div>
              <div class="line">Артикул: {_esc(article)}</div>
              <div class="hint">
                <span>Артикул для подбора · Не нужно клеить</span>
                <span class="page">{page_no}</span>
              </div>
            </section>
            """
        )
        for o in g.get("orders") or []:
            pn = str(o.get("posting_number") or "").strip()
            imgs = label_images.get(pn) or []
            if not imgs:
                page_no += 1
                pages.append(
                    f"""
                    <section class="label missing">
                      <div>Нет этикетки</div>
                      <div>{_esc(pn)}</div>
                    </section>
                    """
                )
                continue
            for b64 in imgs:
                page_no += 1
                pages.append(
                    f"""
                    <section class="label sticker">
                      <img src="data:image/png;base64,{b64}" alt="sticker {_esc(pn)}" />
                    </section>
                    """
                )
    missing = [
        str(x).strip()
        for x in (missing_posting_numbers or [])
        if str(x).strip()
    ]
    warn_html = ""
    if missing:
        preview = ", ".join(missing[:8])
        if len(missing) > 8:
            preview += f" … (+{len(missing) - 8})"
        warn_html = (
            f'<div class="warn-banner" role="alert">'
            f"Не загружено {len(missing)} этик.: {_esc(preview)}. "
            f"Дождитесь 1–2 мин после сборки и повторите печать стикеров."
            f"</div>"
        )
    return f"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"/>
<title>Стикеры {_esc(supply_name)}</title>
<style>
  @page {{ size: 58mm 40mm; margin: 0; }}
  * {{ box-sizing: border-box; }}
  html, body {{ margin: 0; padding: 0; }}
  body {{ font-family: Arial, sans-serif; color: #0f172a; }}
  .label {{
    width: 58mm; height: 40mm; page-break-after: always;
    overflow: hidden; position: relative;
  }}
  .label:last-child {{ page-break-after: auto; }}
  .label.cover {{
    padding: 3mm; background: #fff; border: 0.3mm solid #0f172a;
    display: flex; flex-direction: column; justify-content: center;
    align-items: center; text-align: center; gap: 1.5mm;
  }}
  .label.cover .cover-label {{ font-size: 9px; font-weight: 700; color: #64748b; text-transform: uppercase; }}
  .label.cover .cover-name {{ font-size: 14px; font-weight: 800; line-height: 1.2; max-height: 14mm; overflow: hidden; word-break: break-word; }}
  .label.cover .cover-source {{ font-size: 10px; font-weight: 700; color: #334155; }}
  .label.cover .cover-qty {{ margin-top: 1mm; font-size: 16px; font-weight: 800; }}
  .label.separator {{
    padding: 2.5mm 3mm; background: #fff; border: 0.3mm dashed #94a3b8;
    display: flex; flex-direction: column; gap: 0.6mm;
  }}
  .label.separator .qty {{ font-size: 16px; font-weight: 800; }}
  .label.separator .title {{ font-size: 12px; font-weight: 800; line-height: 1.2; max-height: 14mm; overflow: hidden; }}
  .label.separator .line {{ font-size: 8px; line-height: 1.25; }}
  .label.separator .hint {{
    margin-top: auto; font-size: 7px; color: #64748b; font-weight: 600;
    display: flex; justify-content: space-between; gap: 2mm;
  }}
  .label.separator .hint .page {{ font-size: 9px; font-weight: 800; color: #0f172a; }}
  .label.sticker {{ display: flex; align-items: center; justify-content: center; }}
  .label.sticker img {{ width: 58mm; height: 40mm; object-fit: contain; }}
  .label.missing {{
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    font-size: 10px; color: #b91c1c; gap: 4px;
  }}
  .toolbar {{ padding: 8px 12px; }}
  .warn-banner {{
    margin: 0 12px 8px; padding: 8px 12px; border: 1px solid #fecaca;
    background: #fef2f2; color: #991b1b; font-size: 13px; line-height: 1.35;
    border-radius: 8px;
  }}
  @media print {{ .toolbar, .warn-banner {{ display: none !important; }} }}
</style></head><body>
  <div class="toolbar"><button onclick="window.print()">Печать</button>
    <span style="margin-left:8px;color:#64748b;font-size:13px">58×40 · Этикетка отправления Ozon</span>
  </div>
  {warn_html}
  {''.join(pages) if pages else '<p style="padding:12px">Нет стикеров для печати.</p>'}
  <script>window.addEventListener('load',function(){{ setTimeout(function(){{ window.print(); }}, 300); }});</script>
</body></html>"""


@dataclass
class StickersPrintResult:
    html: str
    expected_count: int
    loaded_count: int
    missing_posting_numbers: list[str]


def list_sticker_groups(detail: dict[str, Any]) -> dict[str, Any]:
    groups = _group_postings_by_article(
        _orders_excluding_cancelled(list(detail.get("orders") or []))
    )
    out = []
    for g in groups:
        nums = [
            str(o.get("posting_number") or "").strip()
            for o in (g.get("orders") or [])
            if str(o.get("posting_number") or "").strip()
        ]
        out.append(
            {
                "group_key": str(g.get("article") or ""),
                "product_name": g.get("product_name") or g.get("article"),
                "article": g.get("article"),
                "qty": int(g.get("qty") or len(nums)),
                "order_ids": nums,
                "posting_numbers": nums,
            }
        )
    return {"groups": out, "supply_id": detail.get("supply_id")}


def build_stickers_print(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    supply_id: str,
    client_id: str,
    api_key: str,
    source_name: str = "",
    posting_numbers_filter: list[str] | None = None,
) -> StickersPrintResult:
    detail = get_supply_detail_for_print(
        repo,
        user_id=user_id,
        source_id=source_id,
        supply_id=supply_id,
        kind=(
            "stickers_selected"
            if posting_numbers_filter is not None
            else "stickers"
        ),
    )
    orders = _orders_excluding_cancelled(list(detail.get("orders") or []))
    if posting_numbers_filter is not None:
        allowed = {str(x).strip() for x in posting_numbers_filter if str(x).strip()}
        orders = [o for o in orders if str(o.get("posting_number") or "").strip() in allowed]
        detail = dict(detail)
        detail["orders"] = orders
        detail["order_count"] = len(orders)
    orders = [
        o
        for o in orders
        if str(o.get("tab") or "") in _PRINTABLE_LABEL_TABS
    ]
    nums = [
        str(o.get("posting_number") or "").strip()
        for o in orders
        if str(o.get("posting_number") or "").strip()
    ]
    if not nums:
        raise RuntimeError(
            "Нет отправлений для печати этикеток. "
            "Этикетки доступны после сборки (ship) отправлений."
        )
    client = oz.OzonFbsClient(client_id, api_key)
    images = _fetch_label_images(client, nums)
    missing = [pn for pn in nums if not (images.get(pn) or [])]
    loaded = sum(1 for pn in nums if (images.get(pn) or []))
    if missing:
        _log.warning(
            "ozon stickers partial supply=%s source=%s expected=%s loaded=%s missing=%s",
            supply_id,
            source_id,
            len(nums),
            loaded,
            len(missing),
        )
    detail = dict(detail)
    detail["orders"] = orders
    detail["order_count"] = len(orders)
    html = render_stickers_print_html(
        detail,
        source_name=source_name,
        label_images=images,
        order_ids_filter=posting_numbers_filter,
        missing_posting_numbers=missing,
    )
    return StickersPrintResult(
        html=html,
        expected_count=len(nums),
        loaded_count=loaded,
        missing_posting_numbers=missing,
    )
