"""Ozon FBS slot fines («Отгрузка в нерекомендованный слот», type_id=94).

Persists accrual events by accrual_id and aggregates by unit_number so late
storno (same type_id, positive amount) can close older fines without re-syncing
full history every time.
"""
from __future__ import annotations

import json
import logging
import threading
from datetime import date, datetime, timedelta
from decimal import Decimal, InvalidOperation
from typing import Any

from .ozon_fbs import OzonFbsClient
from .repository import ReviewRepository
from .security import decrypt_secret, encrypt_secret, mask_secret

_log = logging.getLogger(__name__)

SLOT_TYPE_ID = 94
SLOT_TYPE_NAME = "DefectFineShipmentDelayRate"
SLOT_TYPE_LABEL = "Отгрузка в нерекомендованный слот"
_EPS = Decimal("0.01")
_SYNC_LOG_KEEP = 300

# In-memory job state — nginx ~60s proxy timeout cannot wait for multi-day
# accrual sync; POST returns immediately and UI polls /sync/status.
_fines_sync_lock = threading.Lock()
_fines_sync_state: dict[int, dict[str, Any]] = {}


def _is_fatal_ozon_auth_error(exc: BaseException) -> bool:
    """True when further day retries are pointless (bad/deactivated key)."""
    msg = str(exc or "").lower()
    if "api-key is deactivated" in msg or "api-key is missing a required role" in msg:
        return True
    if "ozon http 403" in msg and ("deactivated" in msg or "required role" in msg):
        return True
    return False


def ensure_ozon_fbs_fines_tables(repo: ReviewRepository) -> None:
    """Create fines tables; ignore concurrent CREATE type races on Postgres."""
    try:
        _ensure_ozon_fbs_fines_tables_inner(repo)
    except Exception as exc:
        # Concurrent CREATE TABLE IF NOT EXISTS can still race on pg_type.
        text = str(exc)
        if (
            "pg_type_typname_nsp_index" in text
            or "already exists" in text.lower()
            or type(exc).__name__ == "UniqueViolation"
        ):
            _log.info("ozon fines tables ensure race ignored: %s", text[:200])
            return
        raise


def _ensure_ozon_fbs_fines_tables_inner(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_settings (
                user_id BIGINT PRIMARY KEY,
                client_id TEXT NOT NULL DEFAULT '',
                api_key_encrypted TEXT NOT NULL DEFAULT '',
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_events (
                user_id BIGINT NOT NULL,
                accrual_id BIGINT NOT NULL,
                event_date DATE NOT NULL,
                unit_number TEXT NOT NULL DEFAULT '',
                amount NUMERIC(18, 2) NOT NULL,
                currency TEXT NOT NULL DEFAULT 'RUB',
                accrued_category TEXT NOT NULL DEFAULT '',
                raw_json TEXT NOT NULL DEFAULT '{}',
                synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (user_id, accrual_id)
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_unit "
                "ON ozon_fbs_fines_events(user_id, unit_number, event_date)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_events_date "
                "ON ozon_fbs_fines_events(user_id, event_date)"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ozon_fbs_fines_sync_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                level TEXT NOT NULL DEFAULT 'info',
                message TEXT NOT NULL DEFAULT ''
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_ozon_fbs_fines_sync_log_user "
                "ON ozon_fbs_fines_sync_log(user_id, id DESC)"
            )
        )


def get_settings(repo: ReviewRepository, *, user_id: int) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted, updated_at
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        return {
            "client_id": "",
            "api_key_masked": "",
            "has_api_key": False,
            "updated_at": None,
        }
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
        "updated_at": row[2],
    }
    enc = str(data.get("api_key_encrypted") or "")
    plain = decrypt_secret(enc) if enc else None
    return {
        "client_id": str(data.get("client_id") or ""),
        "api_key_masked": mask_secret(plain) if plain else "",
        "has_api_key": bool(plain),
        "updated_at": str(data.get("updated_at") or "") or None,
    }


def save_settings(
    repo: ReviewRepository,
    *,
    user_id: int,
    client_id: str | None = None,
    api_key: str | None = None,
) -> dict[str, Any]:
    """Update settings. None/blank api_key keeps previous key. None client_id keeps previous."""
    ensure_ozon_fbs_fines_tables(repo)
    current = get_settings(repo, user_id=user_id)
    next_client = (
        str(client_id).strip()
        if client_id is not None
        else str(current.get("client_id") or "")
    )
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                "SELECT api_key_encrypted FROM ozon_fbs_fines_settings WHERE user_id = ?"
            ),
            (int(user_id),),
        ).fetchone()
        prev_enc = ""
        if row is not None:
            prev_enc = str(
                row["api_key_encrypted"] if hasattr(row, "keys") else row[0] or ""
            )
        if api_key is None or not str(api_key).strip():
            next_enc = prev_enc
        else:
            next_enc = encrypt_secret(str(api_key).strip()) or ""
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_settings (user_id, client_id, api_key_encrypted, updated_at)
                VALUES (?, ?, ?, NOW())
                ON CONFLICT (user_id) DO UPDATE SET
                    client_id = EXCLUDED.client_id,
                    api_key_encrypted = EXCLUDED.api_key_encrypted,
                    updated_at = NOW()
                """
            ),
            (int(user_id), next_client, next_enc or ""),
        )
    return get_settings(repo, user_id=user_id)


def _credentials(repo: ReviewRepository, *, user_id: int) -> tuple[str, str]:
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT client_id, api_key_encrypted
                FROM ozon_fbs_fines_settings
                WHERE user_id = ?
                """
            ),
            (int(user_id),),
        ).fetchone()
    if row is None:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    data = dict(row) if hasattr(row, "keys") else {
        "client_id": row[0],
        "api_key_encrypted": row[1],
    }
    client_id = str(data.get("client_id") or "").strip()
    api_key = decrypt_secret(str(data.get("api_key_encrypted") or "")) or ""
    if not client_id or not api_key:
        raise ValueError("Сначала укажите Client-Id и Api-Key в настройках штрафов")
    return client_id, api_key


def append_sync_log(
    repo: ReviewRepository, *, user_id: int, message: str, level: str = "info"
) -> None:
    ensure_ozon_fbs_fines_tables(repo)
    msg = str(message or "").strip()
    if not msg:
        return
    lvl = str(level or "info").strip().lower() or "info"
    if lvl not in ("info", "warn", "error", "ok"):
        lvl = "info"
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_sync_log (user_id, level, message)
                VALUES (?, ?, ?)
                """
            ),
            (int(user_id), lvl, msg[:2000]),
        )
        rows = conn.execute(
            repo._sql(
                """
                SELECT id FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), int(_SYNC_LOG_KEEP)),
        ).fetchall()
        keep_ids = [
            int(r["id"] if hasattr(r, "keys") else r[0])
            for r in rows
        ]
        if keep_ids:
            placeholders = ",".join("?" for _ in keep_ids)
            conn.execute(
                repo._sql(
                    f"""
                    DELETE FROM ozon_fbs_fines_sync_log
                    WHERE user_id = ?
                      AND id NOT IN ({placeholders})
                    """
                ),
                (int(user_id), *keep_ids),
            )


def list_sync_log(
    repo: ReviewRepository, *, user_id: int, limit: int = 100
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    lim = max(1, min(int(limit or 100), 300))
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT id, created_at, level, message
                FROM ozon_fbs_fines_sync_log
                WHERE user_id = ?
                ORDER BY id DESC
                LIMIT ?
                """
            ),
            (int(user_id), lim),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "id": row[0],
            "created_at": row[1],
            "level": row[2],
            "message": row[3],
        }
        out.append(
            {
                "id": int(d.get("id") or 0),
                "created_at": str(d.get("created_at") or ""),
                "level": str(d.get("level") or "info"),
                "message": str(d.get("message") or ""),
            }
        )
    out.reverse()
    return out


def _parse_amount(value: Any) -> Decimal:
    if isinstance(value, dict):
        value = value.get("amount")
    try:
        return Decimal(str(value or "0").replace(",", ".").strip() or "0")
    except (InvalidOperation, ValueError):
        return Decimal("0")


def extract_slot_fees(accrual: dict[str, Any]) -> list[Decimal]:
    """Return amounts for type_id=94 found in one accrual (usually one)."""
    amounts: list[Decimal] = []
    seen: set[tuple[str, str]] = set()

    def add(tid: Any, accrued: Any) -> None:
        try:
            type_id = int(tid)
        except (TypeError, ValueError):
            return
        if type_id != SLOT_TYPE_ID:
            return
        amt = _parse_amount(accrued)
        key = (str(type_id), str(amt))
        if key in seen:
            return
        seen.add(key)
        amounts.append(amt)

    nif = accrual.get("non_item_fee")
    if isinstance(nif, dict):
        if nif.get("type_id") is not None:
            add(nif.get("type_id"), nif.get("accrued"))
        for fee in nif.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    item_fees = accrual.get("item_fees") or {}
    if isinstance(item_fees, dict):
        for block in item_fees.get("fees") or []:
            if not isinstance(block, dict):
                continue
            for fee in block.get("fees") or []:
                if isinstance(fee, dict):
                    add(fee.get("type_id"), fee.get("accrued"))

    cf = accrual.get("container_fees")
    if isinstance(cf, dict):
        if cf.get("type_id") is not None:
            add(cf.get("type_id"), cf.get("accrued"))
        for fee in cf.get("fees") or []:
            if isinstance(fee, dict):
                add(fee.get("type_id"), fee.get("accrued"))

    return amounts


def upsert_event(
    repo: ReviewRepository,
    *,
    user_id: int,
    accrual_id: int,
    event_date: date,
    unit_number: str,
    amount: Decimal,
    currency: str,
    accrued_category: str,
    raw: dict[str, Any],
) -> bool:
    """Insert or update event. Returns True if newly inserted."""
    ensure_ozon_fbs_fines_tables(repo)
    with repo._connect() as conn:
        existing = conn.execute(
            repo._sql(
                """
                SELECT 1 FROM ozon_fbs_fines_events
                WHERE user_id = ? AND accrual_id = ?
                """
            ),
            (int(user_id), int(accrual_id)),
        ).fetchone()
        conn.execute(
            repo._sql(
                """
                INSERT INTO ozon_fbs_fines_events (
                    user_id, accrual_id, event_date, unit_number, amount,
                    currency, accrued_category, raw_json, synced_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())
                ON CONFLICT (user_id, accrual_id) DO UPDATE SET
                    event_date = EXCLUDED.event_date,
                    unit_number = EXCLUDED.unit_number,
                    amount = EXCLUDED.amount,
                    currency = EXCLUDED.currency,
                    accrued_category = EXCLUDED.accrued_category,
                    raw_json = EXCLUDED.raw_json,
                    synced_at = NOW()
                """
            ),
            (
                int(user_id),
                int(accrual_id),
                event_date.isoformat(),
                str(unit_number or "").strip(),
                str(amount),
                str(currency or "RUB")[:8],
                str(accrued_category or "")[:64],
                json.dumps(raw, ensure_ascii=False)[:20000],
            ),
        )
    return existing is None


def _fetch_day_accruals(client: OzonFbsClient, day: date, *, max_pages: int = 200) -> list[dict[str, Any]]:
    all_rows: list[dict[str, Any]] = []
    seen_ids: set[int] = set()
    last_id: str | None = None
    for _ in range(max_pages):
        body: dict[str, Any] = {"date": day.isoformat()}
        if last_id:
            body["last_id"] = last_id
        data = client.post_json("/v1/finance/accrual/by-day", body)
        chunk = data.get("accruals") if isinstance(data, dict) else None
        if not isinstance(chunk, list) or not chunk:
            break
        new_count = 0
        for item in chunk:
            if not isinstance(item, dict):
                continue
            try:
                aid = int(item.get("accrual_id") or 0)
            except (TypeError, ValueError):
                aid = 0
            if aid and aid in seen_ids:
                continue
            if aid:
                seen_ids.add(aid)
            all_rows.append(item)
            new_count += 1
        new_last = str(data.get("last_id") or "") if isinstance(data, dict) else ""
        # Stop when cursor does not advance or page brought no new accrual_ids.
        if not new_last or new_last == last_id or new_count == 0:
            break
        last_id = new_last
    return all_rows


def sync_range(
    repo: ReviewRepository,
    *,
    user_id: int,
    date_from: date,
    date_to: date,
) -> dict[str, Any]:
    if date_to < date_from:
        raise ValueError("Дата «по» не может быть раньше даты «с»")
    if (date_to - date_from).days > 92:
        raise ValueError("Интервал синхронизации не больше 92 дней за раз")

    client_id, api_key = _credentials(repo, user_id=user_id)
    client = OzonFbsClient(client_id=client_id, api_key=api_key, timeout=90)

    append_sync_log(
        repo,
        user_id=user_id,
        message=f"Синхронизация {date_from.isoformat()} … {date_to.isoformat()}",
        level="info",
    )

    days_done = 0
    inserted = 0
    updated = 0
    slot_hits = 0
    errors: list[str] = []

    day = date_from
    while day <= date_to:
        try:
            accruals = _fetch_day_accruals(client, day)
            day_new = 0
            day_hits = 0
            for acc in accruals:
                amounts = extract_slot_fees(acc)
                if not amounts:
                    continue
                try:
                    accrual_id = int(acc.get("accrual_id") or 0)
                except (TypeError, ValueError):
                    continue
                if accrual_id <= 0:
                    continue
                unit = str(acc.get("unit_number") or "").strip()
                currency = "RUB"
                total = acc.get("total_amount")
                if isinstance(total, dict):
                    currency = str(total.get("currency") or "RUB")
                category = str(acc.get("accrued_category") or "")
                # One accrual can theoretically carry multiple fee lines; store net of type 94.
                amount = sum(amounts, Decimal("0"))
                is_new = upsert_event(
                    repo,
                    user_id=user_id,
                    accrual_id=accrual_id,
                    event_date=day,
                    unit_number=unit,
                    amount=amount,
                    currency=currency,
                    accrued_category=category,
                    raw=acc,
                )
                day_hits += 1
                slot_hits += 1
                if is_new:
                    inserted += 1
                    day_new += 1
                else:
                    updated += 1
            days_done += 1
            append_sync_log(
                repo,
                user_id=user_id,
                message=(
                    f"{day.isoformat()}: начислений {len(accruals)}, "
                    f"штраф/сторно {day_hits}, новых {day_new}"
                ),
                level="ok" if day_hits else "info",
            )
        except Exception as exc:
            msg = f"{day.isoformat()}: ошибка — {exc}"
            _log.warning("ozon fines sync day failed user=%s day=%s err=%s", user_id, day, exc)
            errors.append(msg)
            append_sync_log(repo, user_id=user_id, message=msg, level="error")
            if _is_fatal_ozon_auth_error(exc):
                abort_msg = (
                    "Синхронизация остановлена: ключ Ozon отклонён (403). "
                    "Проверьте Api-Key в настройках штрафов."
                )
                append_sync_log(repo, user_id=user_id, message=abort_msg, level="error")
                errors.append(abort_msg)
                break
        day += timedelta(days=1)

    summary = (
        f"Готово: дней {days_done}, событий слота {slot_hits}, "
        f"новых {inserted}, обновлено {updated}"
    )
    if errors:
        summary += f", ошибок {len(errors)}"
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="error" if errors and not slot_hits else "ok",
    )
    return {
        "ok": True,
        "days_done": days_done,
        "slot_events": slot_hits,
        "inserted": inserted,
        "updated": updated,
        "errors": errors,
        "summary": summary,
    }


def get_sync_status(*, user_id: int) -> dict[str, Any]:
    with _fines_sync_lock:
        st = dict(_fines_sync_state.get(int(user_id)) or {})
    return {
        "in_progress": bool(st.get("in_progress")),
        "message": str(st.get("message") or ""),
        "error": str(st.get("error") or ""),
        "date_from": str(st.get("date_from") or ""),
        "date_to": str(st.get("date_to") or ""),
        "result": st.get("result"),
    }


def start_sync_thread(
    repo: ReviewRepository,
    *,
    user_id: int,
    date_from: date,
    date_to: date,
) -> tuple[bool, str, dict[str, Any]]:
    """Start background fines sync. Returns (ok, message, status_payload)."""
    if date_to < date_from:
        raise ValueError("Дата «по» не может быть раньше даты «с»")
    if (date_to - date_from).days > 92:
        raise ValueError("Интервал синхронизации не больше 92 дней за раз")
    # Validate credentials early so the HTTP response can surface the error.
    _credentials(repo, user_id=user_id)

    uid = int(user_id)
    with _fines_sync_lock:
        cur = _fines_sync_state.get(uid) or {}
        if cur.get("in_progress"):
            status = {
                "in_progress": True,
                "message": str(cur.get("message") or ""),
                "error": str(cur.get("error") or ""),
                "date_from": str(cur.get("date_from") or ""),
                "date_to": str(cur.get("date_to") or ""),
                "result": cur.get("result"),
            }
            return False, "Синхронизация штрафов уже запущена", status
        _fines_sync_state[uid] = {
            "in_progress": True,
            "message": f"Запуск {date_from.isoformat()} … {date_to.isoformat()}",
            "error": "",
            "date_from": date_from.isoformat(),
            "date_to": date_to.isoformat(),
            "result": None,
        }

    try:
        append_sync_log(
            repo,
            user_id=uid,
            message=(
                f"Фоновая синхронизация запущена "
                f"{date_from.isoformat()} … {date_to.isoformat()}"
            ),
            level="info",
        )
    except Exception:
        _log.exception("ozon fines sync start log failed user=%s", uid)

    def _run() -> None:
        try:
            result = sync_range(
                repo,
                user_id=uid,
                date_from=date_from,
                date_to=date_to,
            )
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "message": str(result.get("summary") or "Готово"),
                    "error": "",
                    "date_from": date_from.isoformat(),
                    "date_to": date_to.isoformat(),
                    "result": result,
                }
        except Exception as exc:
            _log.exception("ozon fines background sync failed user=%s", uid)
            try:
                append_sync_log(
                    repo,
                    user_id=uid,
                    message=f"Сбой синхронизации: {exc}",
                    level="error",
                )
            except Exception:
                pass
            with _fines_sync_lock:
                _fines_sync_state[uid] = {
                    "in_progress": False,
                    "message": str(exc),
                    "error": str(exc),
                    "date_from": date_from.isoformat(),
                    "date_to": date_to.isoformat(),
                    "result": None,
                }

    threading.Thread(
        target=_run,
        name=f"ozon-fines-sync-{uid}",
        daemon=True,
    ).start()
    return True, "Синхронизация запущена", get_sync_status(user_id=uid)


def _status_for_net(net: Decimal) -> str:
    if abs(net) <= _EPS:
        return "closed"
    if net < 0:
        return "open"
    return "over"


def list_units(
    repo: ReviewRepository,
    *,
    user_id: int,
    status: str = "open",
    fine_date_from: date | None = None,
    fine_date_to: date | None = None,
    limit: int = 500,
) -> dict[str, Any]:
    ensure_ozon_fbs_fines_tables(repo)
    status_key = str(status or "open").strip().lower()
    if status_key not in ("open", "closed", "all", "over"):
        status_key = "open"
    lim = max(1, min(int(limit or 500), 2000))

    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT
                    unit_number,
                    SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS fine_sum,
                    SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS storno_sum,
                    SUM(amount) AS net_sum,
                    MIN(CASE WHEN amount < 0 THEN event_date END) AS first_fine_date,
                    MAX(CASE WHEN amount > 0 THEN event_date END) AS last_storno_date,
                    COUNT(*) AS event_count
                FROM ozon_fbs_fines_events
                WHERE user_id = ?
                  AND unit_number <> ''
                GROUP BY unit_number
                ORDER BY MIN(CASE WHEN amount < 0 THEN event_date END) DESC NULLS LAST,
                         unit_number
                """
            ),
            (int(user_id),),
        ).fetchall()

    units: list[dict[str, Any]] = []
    summary = {
        "open_count": 0,
        "closed_count": 0,
        "over_count": 0,
        "open_remainder": "0.00",
    }
    open_rem = Decimal("0")

    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "unit_number": row[0],
            "fine_sum": row[1],
            "storno_sum": row[2],
            "net_sum": row[3],
            "first_fine_date": row[4],
            "last_storno_date": row[5],
            "event_count": row[6],
        }
        unit = str(d.get("unit_number") or "").strip()
        if not unit:
            continue
        fine_sum = _parse_amount(d.get("fine_sum"))
        storno_sum = _parse_amount(d.get("storno_sum"))
        net = _parse_amount(d.get("net_sum"))
        st = _status_for_net(net)
        first_fine = d.get("first_fine_date")
        first_fine_s = str(first_fine)[:10] if first_fine else ""
        last_storno = d.get("last_storno_date")
        last_storno_s = str(last_storno)[:10] if last_storno else ""

        if st == "open":
            summary["open_count"] += 1
            open_rem += net
        elif st == "closed":
            summary["closed_count"] += 1
        else:
            summary["over_count"] += 1

        if fine_date_from and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) < fine_date_from:
                    continue
            except ValueError:
                pass
        if fine_date_to and first_fine_s:
            try:
                if date.fromisoformat(first_fine_s) > fine_date_to:
                    continue
            except ValueError:
                pass

        if status_key != "all" and st != status_key:
            continue

        units.append(
            {
                "unit_number": unit,
                "fine_sum": f"{fine_sum:.2f}",
                "storno_sum": f"{storno_sum:.2f}",
                "net_sum": f"{net:.2f}",
                "status": st,
                "first_fine_date": first_fine_s or None,
                "last_storno_date": last_storno_s or None,
                "event_count": int(d.get("event_count") or 0),
            }
        )

    summary["open_remainder"] = f"{open_rem:.2f}"
    return {"units": units[:lim], "summary": summary, "total": len(units)}


def list_unit_events(
    repo: ReviewRepository, *, user_id: int, unit_number: str
) -> list[dict[str, Any]]:
    ensure_ozon_fbs_fines_tables(repo)
    unit = str(unit_number or "").strip()
    if not unit:
        return []
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT accrual_id, event_date, amount, currency, accrued_category, synced_at
                FROM ozon_fbs_fines_events
                WHERE user_id = ? AND unit_number = ?
                ORDER BY event_date ASC, accrual_id ASC
                """
            ),
            (int(user_id), unit),
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        d = dict(row) if hasattr(row, "keys") else {
            "accrual_id": row[0],
            "event_date": row[1],
            "amount": row[2],
            "currency": row[3],
            "accrued_category": row[4],
            "synced_at": row[5],
        }
        amt = _parse_amount(d.get("amount"))
        out.append(
            {
                "accrual_id": int(d.get("accrual_id") or 0),
                "event_date": str(d.get("event_date") or "")[:10],
                "amount": f"{amt:.2f}",
                "currency": str(d.get("currency") or "RUB"),
                "accrued_category": str(d.get("accrued_category") or ""),
                "kind": "storno" if amt > 0 else "fine",
                "synced_at": str(d.get("synced_at") or ""),
            }
        )
    return out


def default_sync_dates() -> tuple[date, date]:
    today = date.today()
    return today - timedelta(days=14), today


# --- Excel «Отчёт по начислениям» import ---------------------------------

EXCEL_FINE_TYPE = "Отгрузка в нерекомендованный слот"
EXCEL_STORNO_TYPE = "Отгрузка в нерекомендованный слот - отмена начисления"


def _excel_synthetic_accrual_id(
    *, unit_number: str, event_date: date, amount: Decimal, kind: str
) -> int:
    """Stable negative id so Excel rows never collide with Ozon API accrual_id."""
    import hashlib

    key = (
        f"excel|{str(unit_number).strip()}|{event_date.isoformat()}|"
        f"{amount:.2f}|{kind}"
    )
    digest = hashlib.sha1(key.encode("utf-8")).digest()
    n = int.from_bytes(digest[:8], "big") & 0x7FFFFFFFFFFFFFFF
    return -n if n else -1


def _parse_excel_date(value: Any) -> date | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    text = str(value).strip()
    if not text:
        return None
    # 18.09.2026 or 2026-09-18
    for fmt in ("%d.%m.%Y", "%Y-%m-%d", "%d.%m.%y"):
        try:
            return datetime.strptime(text[:10], fmt).date()
        except ValueError:
            continue
    try:
        return date.fromisoformat(text[:10])
    except ValueError:
        return None


def parse_accruals_report_rows(file_bytes: bytes) -> list[dict[str, Any]]:
    """Extract only slot fine/storno rows from Ozon accruals Excel report."""
    import io

    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise ValueError("Для импорта нужен пакет openpyxl") from exc

    wb = load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
    try:
        ws = wb[wb.sheetnames[0]]
        header_idx: dict[str, int] = {}
        out: list[dict[str, Any]] = []
        type_i = id_i = date_i = sum_i = -1
        for row in ws.iter_rows(values_only=True):
            if not row:
                continue
            if not header_idx:
                cells = [str(c or "").strip() for c in row]
                if "Тип начисления" in cells and "ID начисления" in cells:
                    header_idx = {name: idx for idx, name in enumerate(cells) if name}
                    required = (
                        "Тип начисления",
                        "ID начисления",
                        "Дата начисления",
                        "Сумма итого, руб.",
                    )
                    missing = [name for name in required if name not in header_idx]
                    if missing:
                        raise ValueError(
                            "В файле нет нужных колонок (ID / Дата / Тип / Сумма)"
                        )
                    type_i = header_idx["Тип начисления"]
                    id_i = header_idx["ID начисления"]
                    date_i = header_idx["Дата начисления"]
                    sum_i = header_idx["Сумма итого, руб."]
                continue
            if max(type_i, id_i, date_i, sum_i) >= len(row):
                continue
            type_label = str(row[type_i] or "").strip()
            if type_label == EXCEL_FINE_TYPE:
                kind = "fine"
            elif type_label == EXCEL_STORNO_TYPE:
                kind = "storno"
            else:
                continue
            unit = str(row[id_i] or "").strip()
            if not unit:
                continue
            event_date = _parse_excel_date(row[date_i])
            if event_date is None:
                continue
            amount = _parse_amount(row[sum_i])
            if isinstance(row[sum_i], float):
                amount = Decimal(str(round(float(row[sum_i]), 2)))
            try:
                amount = amount.quantize(Decimal("0.01"))
            except InvalidOperation:
                continue
            if abs(amount) <= _EPS:
                continue
            # Normalize sign by kind (report already uses +/- but be safe).
            if kind == "fine" and amount > 0:
                amount = -amount
            if kind == "storno" and amount < 0:
                amount = -amount
            out.append(
                {
                    "unit_number": unit,
                    "event_date": event_date,
                    "amount": amount,
                    "kind": kind,
                    "type_label": type_label,
                    "raw": {
                        "source": "excel_import",
                        "id_nachisleniya": unit,
                        "type": type_label,
                        "date": event_date.isoformat(),
                        "amount": f"{amount:.2f}",
                    },
                }
            )
        if not header_idx:
            raise ValueError("Не найден заголовок листа «Начисления»")
        return out
    finally:
        wb.close()


def _load_existing_amount_keys(
    repo: ReviewRepository, *, user_id: int, units: set[str]
) -> set[tuple[str, str]]:
    """Set of (unit_number, amount_str) already stored for these units."""
    ensure_ozon_fbs_fines_tables(repo)
    clean = sorted({str(u).strip() for u in units if str(u).strip()})
    if not clean:
        return set()
    out: set[tuple[str, str]] = set()
    # Chunk IN lists to keep query size bounded.
    with repo._connect() as conn:
        for i in range(0, len(clean), 500):
            chunk = clean[i : i + 500]
            placeholders = ", ".join(["?"] * len(chunk))
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT unit_number, amount
                    FROM ozon_fbs_fines_events
                    WHERE user_id = ?
                      AND unit_number IN ({placeholders})
                    """
                ),
                (int(user_id), *chunk),
            ).fetchall()
            for row in rows:
                d = dict(row) if hasattr(row, "keys") else {
                    "unit_number": row[0],
                    "amount": row[1],
                }
                unit = str(d.get("unit_number") or "").strip()
                amt = _parse_amount(d.get("amount")).quantize(Decimal("0.01"))
                out.add((unit, f"{amt:.2f}"))
    return out


def import_accruals_report(
    repo: ReviewRepository,
    *,
    user_id: int,
    file_bytes: bytes,
    filename: str = "",
) -> dict[str, Any]:
    """Merge slot fine/storno from Excel without duplicating API sync events.

    Skip when the same unit_number + amount already exists (any date/source).
    New storno against an existing synced fine closes the unit (net≈0 → green).
    """
    rows = parse_accruals_report_rows(file_bytes)
    units = {str(r["unit_number"]) for r in rows}
    existing = _load_existing_amount_keys(repo, user_id=user_id, units=units)

    inserted = 0
    skipped = 0
    fines_new = 0
    storno_new = 0

    for row in rows:
        unit = str(row["unit_number"])
        event_date: date = row["event_date"]
        amount: Decimal = row["amount"]
        kind = str(row["kind"])
        key = (unit, f"{amount:.2f}")
        if key in existing:
            skipped += 1
            continue
        aid = _excel_synthetic_accrual_id(
            unit_number=unit,
            event_date=event_date,
            amount=amount,
            kind=kind,
        )
        is_new = upsert_event(
            repo,
            user_id=user_id,
            accrual_id=aid,
            event_date=event_date,
            unit_number=unit,
            amount=amount,
            currency="RUB",
            accrued_category=str(row.get("type_label") or "")[:64],
            raw=dict(row.get("raw") or {}),
        )
        if is_new:
            inserted += 1
            existing.add(key)
            if kind == "storno":
                storno_new += 1
            else:
                fines_new += 1
        else:
            skipped += 1
            existing.add(key)

    name = str(filename or "отчёт").strip() or "отчёт"
    summary = (
        f"Импорт «{name}»: слот-строк {len(rows)}, "
        f"добавлено {inserted} (штрафов {fines_new}, сторно {storno_new}), "
        f"пропущено как уже есть {skipped}"
    )
    append_sync_log(
        repo,
        user_id=user_id,
        message=summary,
        level="ok" if inserted or not rows else "warn",
    )
    return {
        "ok": True,
        "rows_slot": len(rows),
        "inserted": inserted,
        "skipped": skipped,
        "fines_new": fines_new,
        "storno_new": storno_new,
        "summary": summary,
    }
