"""Cabinet-wide Chestny Znak codes for Настройки → Маркировка и ГТД.

Export uses True API ``POST /cises/search`` (emission period, all statuses),
the same auth / background-run / log pattern as «Работа с ЧЗ» on a GTD.
"""

from __future__ import annotations

import logging
import re
import threading
from datetime import datetime, timedelta, timezone
from typing import Any
from zoneinfo import ZoneInfo

from .chz_true_api import ChzTrueApiClient, ChzTrueApiError, build_lk_receipt_document, build_lp_return_document
from .repository import ReviewRepository
from . import supply_gtd as gtd_mod
from . import supply_gtd_chz as gtd_chz
from . import wb_kiz_circulation as kiz_circ

_log = logging.getLogger(__name__)

PAGE_SIZE = 1000
MAX_PAGES = 400
CIS_CHUNK = int(getattr(gtd_chz, "CIS_CHUNK", 100) or 100)
DOC_PRODUCTS_LIMIT = int(getattr(gtd_chz, "DOC_PRODUCTS_LIMIT", 100) or 100)
OP_WITHDRAW = "withdraw"
OP_RETURN = "return"


def ensure_supply_chz_cabinet_tables(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_chz_cabinet_kiz (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    kiz_short TEXT NOT NULL,
                    gtin TEXT NOT NULL DEFAULT '',
                    product_name TEXT NOT NULL DEFAULT '',
                    emission_date TEXT NOT NULL DEFAULT '',
                    cis_status TEXT NOT NULL DEFAULT '',
                    cis_status_kind TEXT NOT NULL DEFAULT '',
                    cis_status_label TEXT NOT NULL DEFAULT '',
                    cis_owner_inn TEXT NOT NULL DEFAULT '',
                    cis_status_error TEXT NOT NULL DEFAULT '',
                    cis_checked_at TIMESTAMPTZ,
                    last_op TEXT NOT NULL DEFAULT '',
                    last_doc_id TEXT NOT NULL DEFAULT '',
                    last_doc_type TEXT NOT NULL DEFAULT '',
                    last_op_status TEXT NOT NULL DEFAULT '',
                    last_op_error TEXT NOT NULL DEFAULT '',
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, kiz_short)
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_chz_cabinet_kiz_user
                ON supply_chz_cabinet_kiz (user_id, id)
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_chz_cabinet_runs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    op TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'running',
                    requested INTEGER NOT NULL DEFAULT 0,
                    ok_count INTEGER NOT NULL DEFAULT 0,
                    err_count INTEGER NOT NULL DEFAULT 0,
                    log_text TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    finished_at TIMESTAMPTZ
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_chz_cabinet_runs_user
                ON supply_chz_cabinet_runs (user_id, id DESC)
                """
            )
        )


def emission_period_bounds(date_from: str, date_to: str) -> tuple[str, str]:
    """``YYYY-MM-DD`` → True API ``emissionDatePeriod`` ISO bounds (inclusive day)."""
    a = str(date_from or "").strip()
    b = str(date_to or "").strip()
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", a) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", b):
        raise ValueError("Укажите даты «с» и «по» в формате ГГГГ-ММ-ДД")
    if a > b:
        raise ValueError("Дата «с» позже даты «по»")
    return (f"{a}T00:00:00.000Z", f"{b}T23:59:59.000Z")


def initial_search_cursor(date_to_iso: str) -> tuple[str, str]:
    """Cursor for the first ``/cises/search`` page.

    The API starts the page *after* ``lastEmissionDate``. Passing the period
    end itself skips that day, and an empty ``sgtin`` is rejected. Working
    clients send the next calendar day and a zero sgtin.
    """
    day = str(date_to_iso or "")[:10]
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
        raise ValueError("Некорректная дата курсора выгрузки")
    nxt = datetime.strptime(day, "%Y-%m-%d") + timedelta(days=1)
    return (nxt.strftime("%Y-%m-%dT00:00:00.000Z"), "0")


def product_groups_from_settings(settings: dict[str, Any] | None) -> list[str]:
    raw = str((settings or {}).get("product_group") or "")
    return [part.strip() for part in raw.split(",") if part.strip()]


def kiz_from_search_row(row: dict[str, Any]) -> tuple[str, str, str, str]:
    """Return ``(kiz_short, gtin, product_name, emission_date)``."""
    if not isinstance(row, dict):
        return "", "", "", ""
    gtin = str(row.get("gtin") or "").strip()
    name = str(row.get("productName") or row.get("product_name") or "").strip()
    emission = str(row.get("emissionDate") or row.get("emission_date") or "").strip()
    cis = str(row.get("cis") or "").strip()
    sgtin = str(row.get("sgtin") or "").strip()
    short = gtd_mod.kiz_short_from_raw(cis) if cis else ""
    if not short and sgtin:
        short = gtd_mod.kiz_short_from_raw(sgtin)
    if not short and gtin and sgtin.startswith(gtin):
        serial = sgtin[len(gtin) :]
        gtin14 = gtin if len(gtin) == 14 else gtin.zfill(14)
        short = gtd_mod.kiz_short_from_raw(f"01{gtin14}21{serial}")
    if not short:
        short = cis or sgtin
    if not gtin and short:
        gtin = gtd_chz._gtin_from_kiz_short(short)
    return short[:200], gtin[:32], name[:500], emission[:40]


def _start_run(repo: ReviewRepository, *, user_id: int, op: str, requested: int) -> int:
    with repo._connect() as conn:
        cur = conn.execute(
            repo._sql(
                """
                INSERT INTO supply_chz_cabinet_runs (
                    user_id, op, status, requested, log_text, created_at
                ) VALUES (?, ?, 'running', ?, '', NOW())
                RETURNING id
                """
            ),
            (user_id, op, int(requested)),
        )
        row = cur.fetchone()
    return int(repo._row_to_dict(row).get("id") or 0)


def _update_run(
    repo: ReviewRepository,
    *,
    run_id: int,
    log_text: str,
    ok_count: int = 0,
    err_count: int = 0,
) -> None:
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                UPDATE supply_chz_cabinet_runs
                SET log_text = ?, ok_count = ?, err_count = ?
                WHERE id = ? AND status = 'running'
                """
            ),
            (str(log_text or "")[:200000], int(ok_count), int(err_count), int(run_id)),
        )


def _finish_run(
    repo: ReviewRepository,
    *,
    run_id: int,
    status: str,
    ok_count: int = 0,
    err_count: int = 0,
    log_text: str = "",
) -> None:
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                UPDATE supply_chz_cabinet_runs
                SET status = ?, ok_count = ?, err_count = ?, log_text = ?,
                    finished_at = NOW()
                WHERE id = ?
                """
            ),
            (
                str(status or "error")[:40],
                int(ok_count),
                int(err_count),
                str(log_text or "")[:200000],
                int(run_id),
            ),
        )


def get_run(repo: ReviewRepository, *, user_id: int, run_id: int) -> dict[str, Any] | None:
    ensure_supply_chz_cabinet_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM supply_chz_cabinet_runs
                WHERE user_id = ? AND id = ?
                """
            ),
            (user_id, int(run_id)),
        ).fetchone()
    if not row:
        return None
    d = repo._row_to_dict(row)
    return {
        "id": int(d.get("id") or 0),
        "op": str(d.get("op") or ""),
        "status": str(d.get("status") or ""),
        "requested": int(d.get("requested") or 0),
        "ok_count": int(d.get("ok_count") or 0),
        "err_count": int(d.get("err_count") or 0),
        "log_text": str(d.get("log_text") or ""),
    }


def _upsert_search_row(
    repo: ReviewRepository,
    *,
    user_id: int,
    participant_inn: str,
    row: dict[str, Any],
) -> bool:
    short, gtin, name, emission = kiz_from_search_row(row)
    if not short:
        return False
    status = str(row.get("status") or "").strip()
    owner = str(row.get("ownerInn") or row.get("ownerINN") or row.get("owner_inn") or "").strip()
    label, kind = gtd_chz._display_kind(
        status=status,
        owner_inn=owner,
        participant_inn=participant_inn,
        error="",
    )
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO supply_chz_cabinet_kiz (
                    user_id, kiz_short, gtin, product_name, emission_date,
                    cis_status, cis_status_kind, cis_status_label, cis_owner_inn,
                    cis_status_error, cis_checked_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, '', NOW(), NOW())
                ON CONFLICT (user_id, kiz_short) DO UPDATE SET
                    gtin = CASE WHEN excluded.gtin <> '' THEN excluded.gtin ELSE supply_chz_cabinet_kiz.gtin END,
                    product_name = CASE WHEN excluded.product_name <> '' THEN excluded.product_name
                                        ELSE supply_chz_cabinet_kiz.product_name END,
                    emission_date = CASE WHEN excluded.emission_date <> '' THEN excluded.emission_date
                                         ELSE supply_chz_cabinet_kiz.emission_date END,
                    cis_status = excluded.cis_status,
                    cis_status_kind = excluded.cis_status_kind,
                    cis_status_label = excluded.cis_status_label,
                    cis_owner_inn = excluded.cis_owner_inn,
                    cis_status_error = '',
                    cis_checked_at = NOW(),
                    updated_at = NOW()
                """
            ),
            (
                user_id,
                short,
                gtin,
                name,
                emission,
                status[:80],
                kind[:40],
                label[:80],
                owner[:20],
            ),
        )
    return True


def _run_export(
    repo: ReviewRepository,
    *,
    user_id: int,
    run_id: int,
    client: ChzTrueApiClient,
    date_from_iso: str,
    date_to_iso: str,
    participant_inn: str,
    product_groups: list[str],
    log: list[str],
) -> None:
    saved = errors = pages = 0
    last_dt, last_sgtin = initial_search_cursor(date_to_iso)
    seen_cursor = ""
    groups = [str(g or "").strip() for g in (product_groups or []) if str(g or "").strip()]
    try:
        for page_no in range(1, MAX_PAGES + 1):
            pages = page_no
            gtd_chz._append_log(
                log,
                f"Страница {page_no}: запрос кодов "
                f"({date_from_iso[:10]}…{date_to_iso[:10]}, все статусы, "
                f"группа {', '.join(groups) or '—'})…",
            )
            _update_run(repo, run_id=run_id, log_text="\n".join(log), ok_count=saved, err_count=errors)
            payload = client.cises_search(
                date_from=date_from_iso,
                date_to=date_to_iso,
                per_page=PAGE_SIZE,
                last_emission_date=last_dt,
                sgtin=last_sgtin,
                product_groups=groups or None,
            )
            rows = list(payload.get("result") or [])
            if not rows:
                gtd_chz._append_log(log, f"Страница {page_no}: пусто — стоп")
                break
            page_saved = 0
            for row in rows:
                try:
                    if _upsert_search_row(
                        repo, user_id=user_id, participant_inn=participant_inn, row=row
                    ):
                        saved += 1
                        page_saved += 1
                except Exception as exc:
                    errors += 1
                    gtd_chz._append_log(log, f"Строка не сохранена: {exc}")
            last = rows[-1]
            last_dt = str(last.get("emissionDate") or last.get("emission_date") or "").strip()
            last_sgtin = str(last.get("sgtin") or last.get("cis") or "").strip()
            gtd_chz._append_log(
                log,
                f"Страница {page_no}: получено {len(rows)}, сохранено {page_saved}, "
                f"всего {saved}",
            )
            _update_run(repo, run_id=run_id, log_text="\n".join(log), ok_count=saved, err_count=errors)
            cursor = f"{last_dt}|{last_sgtin}"
            if payload.get("isLastPage"):
                gtd_chz._append_log(log, "Последняя страница")
                break
            if not last_dt or not last_sgtin or cursor == seen_cursor:
                gtd_chz._append_log(log, "Нет курсора пагинации — стоп")
                break
            seen_cursor = cursor
        gtd_chz._append_log(
            log, f"Готово: страниц {pages}, кодов {saved}, ошибок {errors}"
        )
        _finish_run(
            repo,
            run_id=run_id,
            status="ok",
            ok_count=saved,
            err_count=errors,
            log_text="\n".join(log),
        )
    except Exception as exc:
        gtd_chz._append_log(log, f"Сбой: {exc}")
        _finish_run(
            repo,
            run_id=run_id,
            status="error",
            ok_count=saved,
            err_count=errors + 1,
            log_text="\n".join(log),
        )
        raise


def start_cabinet_export(
    repo: ReviewRepository,
    *,
    user_id: int,
    token: str,
    date_from: str,
    date_to: str,
) -> dict[str, Any]:
    ensure_supply_chz_cabinet_tables(repo)
    settings = gtd_chz._chz_settings_ready(repo, user_id=user_id)
    token_s = str(token or "").strip()
    if not token_s:
        raise ValueError("Нужен токен ЧЗ (подпишите УКЭП)")
    iso_from, iso_to = emission_period_bounds(date_from, date_to)
    client = kiz_circ.chz_client_from_settings(settings)
    client.set_token(token_s)
    inn = str(settings.get("participant_inn") or "").strip()
    groups = product_groups_from_settings(settings)
    run_id = _start_run(repo, user_id=user_id, op="export", requested=0)
    log = [
        f"Выгрузка кодов маркировки {date_from}…{date_to}, все статусы",
        f"Товарная группа: {', '.join(groups) or '—'}",
        "Запущено в фоне — смотрите лог, не закрывайте вкладку",
    ]
    _update_run(repo, run_id=run_id, log_text="\n".join(log))

    def _worker() -> None:
        try:
            _run_export(
                repo,
                user_id=user_id,
                run_id=run_id,
                client=client,
                date_from_iso=iso_from,
                date_to_iso=iso_to,
                participant_inn=inn,
                product_groups=groups,
                log=list(log),
            )
        except Exception:
            _log.exception("cabinet chz export failed run_id=%s", run_id)

    threading.Thread(
        target=_worker, name=f"chz-cabinet-export-{run_id}", daemon=True
    ).start()
    return {
        "ok": True,
        "async": True,
        "run_id": run_id,
        "log_text": "\n".join(log),
    }


def list_cabinet_kiz(
    repo: ReviewRepository,
    *,
    user_id: int,
    offset: int = 0,
    limit: int = 20000,
    status_kind: str = "",
    kiz: str = "",
) -> dict[str, Any]:
    ensure_supply_chz_cabinet_tables(repo)
    name_by_gtin = gtd_chz._load_product_name_by_gtin(repo, user_id=user_id)
    off = max(0, int(offset or 0))
    lim = max(1, min(int(limit or 2000), 20000))
    kind_filter = str(status_kind or "").strip()
    kind_expr = (
        "CASE WHEN cis_status_kind IS NULL OR TRIM(cis_status_kind) = '' "
        f"THEN '{gtd_chz.KIND_EMPTY}' ELSE cis_status_kind END"
    )
    where = "WHERE user_id = ?"
    params: list[Any] = [user_id]
    kiz_exact = str(kiz or "").strip()
    if kiz_exact:
        where += " AND kiz_short = ?"
        params.append(kiz_exact[:200])
    filter_sql = ""
    if kind_filter:
        filter_sql = f" AND ({kind_expr}) = ?"
        params_f = params + [kind_filter]
    else:
        params_f = list(params)

    with repo._connect() as conn:
        total = int(
            repo._row_to_dict(
                conn.execute(
                    repo._sql(f"SELECT COUNT(*) AS n FROM supply_chz_cabinet_kiz {where}"),
                    tuple(params),
                ).fetchone()
            ).get("n")
            or 0
        )
        kind_rows = conn.execute(
            repo._sql(
                f"""
                SELECT {kind_expr} AS kind, COUNT(*) AS n
                FROM supply_chz_cabinet_kiz {where}
                GROUP BY 1
                """
            ),
            tuple(params),
        ).fetchall()
        kind_counts: dict[str, int] = {}
        for r in kind_rows:
            d = repo._row_to_dict(r)
            k = str(d.get("kind") or "").strip() or gtd_chz.KIND_EMPTY
            kind_counts[k] = int(d.get("n") or 0)
        filtered_total = int(
            repo._row_to_dict(
                conn.execute(
                    repo._sql(
                        f"SELECT COUNT(*) AS n FROM supply_chz_cabinet_kiz {where} {filter_sql}"
                    ),
                    tuple(params_f),
                ).fetchone()
            ).get("n")
            or 0
        )
        rows = conn.execute(
            repo._sql(
                f"""
                SELECT id, kiz_short, gtin, product_name, emission_date,
                       cis_status, ({kind_expr}) AS cis_status_kind, cis_status_label,
                       cis_owner_inn, cis_status_error, cis_checked_at,
                       last_op, last_doc_id, last_doc_type, last_op_status, last_op_error
                FROM supply_chz_cabinet_kiz
                {where} {filter_sql}
                ORDER BY id ASC
                LIMIT ? OFFSET ?
                """
            ),
            tuple(params_f + [lim, off]),
        ).fetchall()

    items: list[dict[str, Any]] = []
    for r in rows:
        d = repo._row_to_dict(r)
        kind = str(d.get("cis_status_kind") or "").strip() or gtd_chz.KIND_EMPTY
        label = str(d.get("cis_status_label") or "").strip() or (
            "Не проверен" if kind == gtd_chz.KIND_EMPTY else ""
        )
        kiz_short = str(d.get("kiz_short") or "")
        gtin = str(d.get("gtin") or "").strip() or gtd_chz._gtin_from_kiz_short(kiz_short)
        stored_name = str(d.get("product_name") or "").strip()
        catalog_name = gtd_chz._resolve_product_name(
            name_by_gtin, gtin=gtin, kiz_short=kiz_short
        )
        items.append(
            {
                "kiz_id": int(d.get("id") or 0),
                "kiz_short": kiz_short,
                "gtin": gtin,
                "product_name": stored_name or catalog_name,
                "emission_date": str(d.get("emission_date") or ""),
                "cis_status": str(d.get("cis_status") or ""),
                "cis_status_kind": kind,
                "cis_status_label": label,
                "cis_owner_inn": str(d.get("cis_owner_inn") or ""),
                "cis_status_error": str(d.get("cis_status_error") or ""),
                "cis_checked_at": str(d.get("cis_checked_at") or ""),
                "last_op": str(d.get("last_op") or ""),
                "last_doc_id": str(d.get("last_doc_id") or ""),
                "last_doc_type": str(d.get("last_doc_type") or ""),
                "last_op_status": str(d.get("last_op_status") or ""),
                "last_op_error": str(d.get("last_op_error") or ""),
            }
        )
    return {
        "ok": True,
        "total": total,
        "filtered_total": filtered_total,
        "offset": off,
        "limit": lim,
        "has_more": off + lim < filtered_total,
        "kind_counts": kind_counts,
        "items": items,
    }


def lookup_cabinet_kiz(
    repo: ReviewRepository,
    *,
    user_id: int,
    kiz_scan: str,
) -> dict[str, Any] | None:
    """Find one stored cabinet code by a scanned or pasted КИЗ.

    Tries the normalized short code first, then the raw scan, so a code
    saved from ``/cises/search`` is found later from Маркировка и ГТД.
    """
    scan = str(kiz_scan or "").strip()
    if not scan:
        return None
    keys: list[str] = []
    short = gtd_mod.kiz_short_from_raw(scan)
    if short:
        keys.append(short)
    compact = "".join(scan.split())
    head = compact.split("\x1d", 1)[0].split("\u001d", 1)[0]
    for candidate in (scan, compact, head):
        text = str(candidate or "").strip()[:200]
        if text and text not in keys:
            keys.append(text)
    for key in keys:
        found = list_cabinet_kiz(
            repo, user_id=user_id, offset=0, limit=1, status_kind="", kiz=key
        )
        items = found.get("items") or []
        if items:
            return items[0]
    return None


def _load_codes(
    repo: ReviewRepository, *, user_id: int, kiz_shorts: list[str] | None
) -> list[str]:
    if kiz_shorts:
        out = []
        seen = set()
        for raw in kiz_shorts:
            ks = str(raw or "").strip()
            if ks and ks not in seen:
                seen.add(ks)
                out.append(ks)
        return out
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT kiz_short FROM supply_chz_cabinet_kiz
                WHERE user_id = ? ORDER BY id ASC
                """
            ),
            (user_id,),
        ).fetchall()
    return [str(repo._row_to_dict(r).get("kiz_short") or "").strip() for r in rows if r]


def _upsert_status(
    repo: ReviewRepository,
    *,
    user_id: int,
    kiz_short: str,
    cis_status: str = "",
    cis_owner_inn: str = "",
    cis_status_error: str = "",
    participant_inn: str = "",
) -> None:
    label, kind = gtd_chz._display_kind(
        status=cis_status,
        owner_inn=cis_owner_inn,
        participant_inn=participant_inn,
        error=cis_status_error,
    )
    gtin = gtd_chz._gtin_from_kiz_short(kiz_short)
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO supply_chz_cabinet_kiz (
                    user_id, kiz_short, gtin, cis_status, cis_status_kind,
                    cis_status_label, cis_owner_inn, cis_status_error,
                    cis_checked_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
                ON CONFLICT (user_id, kiz_short) DO UPDATE SET
                    cis_status = excluded.cis_status,
                    cis_status_kind = excluded.cis_status_kind,
                    cis_status_label = excluded.cis_status_label,
                    cis_owner_inn = excluded.cis_owner_inn,
                    cis_status_error = excluded.cis_status_error,
                    cis_checked_at = NOW(),
                    updated_at = NOW()
                """
            ),
            (
                user_id,
                kiz_short,
                gtin,
                cis_status[:80],
                kind[:40],
                label[:80],
                cis_owner_inn[:20],
                cis_status_error[:500],
            ),
        )


def refresh_cabinet_cis_statuses(
    repo: ReviewRepository,
    *,
    user_id: int,
    token: str,
    kiz_shorts: list[str] | None = None,
) -> dict[str, Any]:
    """Chunked ``/cises/info`` — same idea as GTD «Выгрузить статусы из ЧЗ»."""
    ensure_supply_chz_cabinet_tables(repo)
    settings = gtd_chz._chz_settings_ready(repo, user_id=user_id)
    codes = _load_codes(repo, user_id=user_id, kiz_shorts=kiz_shorts)
    if not codes:
        raise ValueError("Нет КИЗ для проверки")
    token_s = str(token or "").strip()
    if not token_s:
        raise ValueError("Нужен токен ЧЗ (подпишите УКЭП)")
    client = kiz_circ.chz_client_from_settings(settings)
    client.set_token(token_s)
    pg = str(settings.get("product_group") or "").strip()
    inn = str(settings.get("participant_inn") or "").strip()
    run_id = _start_run(repo, user_id=user_id, op="cis_status", requested=len(codes))
    log = [f"Выгрузка статусов ЧЗ: кодов {len(codes)}"]
    found = missing = errors = 0
    try:
        total_chunks = max(1, (len(codes) + CIS_CHUNK - 1) // CIS_CHUNK)
        for i in range(0, len(codes), CIS_CHUNK):
            part = codes[i : i + CIS_CHUNK]
            chunk_no = i // CIS_CHUNK + 1
            try:
                rows_api = client.cises_info(part, product_group=pg)
                parsed = [
                    kiz_circ.parse_cises_info_item(x if isinstance(x, dict) else None)
                    for x in rows_api
                ]
                nf = sum(
                    1
                    for p in parsed
                    if "не найден" in str(p.get("error") or "").lower()
                    or p.get("error_code") == "404"
                )
                if pg and parsed and nf == len(parsed) == len(part):
                    gtd_chz._append_log(log, f"pg={pg}: все «не найден» — повтор без pg")
                    rows_api = client.cises_info(part, product_group="")
                    parsed = [
                        kiz_circ.parse_cises_info_item(x if isinstance(x, dict) else None)
                        for x in rows_api
                    ]
            except ChzTrueApiError as exc:
                errors += len(part)
                gtd_chz._append_log(log, f"Ошибка API: {exc}")
                for ks in part:
                    _upsert_status(
                        repo,
                        user_id=user_id,
                        kiz_short=ks,
                        cis_status_error=str(exc)[:500],
                        participant_inn=inn,
                    )
                _update_run(
                    repo, run_id=run_id, log_text="\n".join(log), ok_count=found, err_count=errors
                )
                continue
            by_key: dict[str, dict[str, str]] = {}
            for idx, p in enumerate(parsed):
                req = part[idx] if idx < len(part) else ""
                keys = {req, str(p.get("cis") or "").strip()}
                for k in list(keys):
                    if k:
                        keys.add(k.split("\x1d", 1)[0])
                for k in keys:
                    if k and k not in by_key:
                        by_key[k] = p
            for ks in part:
                hit = by_key.get(ks)
                if not hit:
                    for k, p in by_key.items():
                        if k.startswith(ks) or ks.startswith(k):
                            hit = p
                            break
                if not hit:
                    missing += 1
                    _upsert_status(
                        repo,
                        user_id=user_id,
                        kiz_short=ks,
                        cis_status_error="КИЗ не найден в ответе ЧЗ",
                        participant_inn=inn,
                    )
                    continue
                err = str(hit.get("error") or "").strip()
                status = str(hit.get("status") or "").strip()
                owner = str(hit.get("owner_inn") or "").strip()
                if err and not status:
                    errors += 1
                elif status:
                    found += 1
                else:
                    missing += 1
                _upsert_status(
                    repo,
                    user_id=user_id,
                    kiz_short=ks,
                    cis_status=status,
                    cis_owner_inn=owner,
                    cis_status_error=err,
                    participant_inn=inn,
                )
            gtd_chz._append_log(
                log,
                f"Чанк {chunk_no}/{total_chunks}: {len(part)} код. "
                f"(найдено {found}, ошибок {errors + missing})",
            )
            _update_run(
                repo, run_id=run_id, log_text="\n".join(log), ok_count=found, err_count=errors + missing
            )
        gtd_chz._append_log(
            log, f"Готово: найдено {found}, нет данных {missing}, ошибок {errors}"
        )
        _finish_run(
            repo,
            run_id=run_id,
            status="ok",
            ok_count=found,
            err_count=errors + missing,
            log_text="\n".join(log),
        )
    except Exception as exc:
        gtd_chz._append_log(log, f"Сбой: {exc}")
        _finish_run(
            repo,
            run_id=run_id,
            status="error",
            ok_count=found,
            err_count=errors + 1,
            log_text="\n".join(log),
        )
        raise
    return {
        "ok": True,
        "run_id": run_id,
        "found": found,
        "missing": missing,
        "errors": errors,
        "log_text": "\n".join(log),
        "async": False,
    }


def _states_by_kiz(
    repo: ReviewRepository, *, user_id: int, kiz_shorts: list[str]
) -> dict[str, dict[str, Any]]:
    if not kiz_shorts:
        return {}
    out: dict[str, dict[str, Any]] = {}
    chunk = 500
    for i in range(0, len(kiz_shorts), chunk):
        part = kiz_shorts[i : i + chunk]
        placeholders = ", ".join("?" for _ in part)
        with repo._connect() as conn:
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT kiz_short, cis_status_kind, last_op, last_op_status
                    FROM supply_chz_cabinet_kiz
                    WHERE user_id = ? AND kiz_short IN ({placeholders})
                    """
                ),
                (user_id, *part),
            ).fetchall()
        for r in rows:
            d = repo._row_to_dict(r)
            ks = str(d.get("kiz_short") or "")
            if ks:
                out[ks] = d
    return out


def prepare_cabinet_documents(
    repo: ReviewRepository,
    *,
    user_id: int,
    op: str,
    kiz_shorts: list[str],
) -> dict[str, Any]:
    ensure_supply_chz_cabinet_tables(repo)
    settings = gtd_chz._chz_settings_ready(repo, user_id=user_id)
    op_s = str(op or "").strip().lower()
    if op_s not in {OP_WITHDRAW, OP_RETURN}:
        raise ValueError("op: withdraw или return")
    codes = _load_codes(repo, user_id=user_id, kiz_shorts=kiz_shorts)
    if not codes:
        raise ValueError("Выберите КИЗ")
    states = _states_by_kiz(repo, user_id=user_id, kiz_shorts=codes)
    eligible: list[str] = []
    skipped: list[dict[str, str]] = []
    for ks in codes:
        st = states.get(ks) or {}
        kind = str(st.get("cis_status_kind") or "").strip() or gtd_chz.KIND_EMPTY
        last_op = str(st.get("last_op") or "").strip()
        last_op_status = str(st.get("last_op_status") or "").strip()
        if last_op_status == "submitted" and last_op == op_s:
            skipped.append({"kiz_short": ks, "reason": "Уже отправлено в ЧЗ — сначала выгрузите статусы"})
            continue
        if op_s == OP_WITHDRAW:
            if kind != gtd_chz.KIND_IN:
                skipped.append({"kiz_short": ks, "reason": "Вывод доступен только для статуса «В обороте»"})
                continue
        else:
            if kind == gtd_chz.KIND_TRANSFERRED:
                skipped.append({"kiz_short": ks, "reason": "Код передан другому ИНН — ввод недоступен"})
                continue
            if kind != gtd_chz.KIND_OUT:
                skipped.append({"kiz_short": ks, "reason": "Ввод доступен для статуса «Выведен»"})
                continue
        eligible.append(ks)
    if not eligible:
        raise ValueError("Нет подходящих КИЗ для операции. Сначала выгрузите статусы из ЧЗ.")

    inn = str(settings.get("participant_inn") or "").strip()
    pg = str(settings.get("product_group") or "").strip()
    kpp = str(settings.get("kpp") or "").strip()
    fias_id = str(settings.get("fias_id") or "").strip()
    if not kpp or not fias_id:
        place = kiz_circ.resolve_chz_place_details(repo, user_id=user_id, participant_inn=inn)
        if not kpp:
            kpp = str(place.get("kpp") or "").strip()
        if not fias_id:
            fias_id = str(place.get("fias_id") or "").strip()
    if len(re.sub(r"\D", "", inn)) == 12:
        kpp = ""
    if op_s == OP_WITHDRAW:
        if not fias_id or (len(re.sub(r"\D", "", inn)) == 10 and not kpp):
            raise ValueError("Для вывода DISTANCE укажите КПП (ООО) и ФИАС МОД в Настройки → ЧЗ")

    try:
        doc_date = datetime.now(ZoneInfo("Europe/Moscow")).strftime("%Y-%m-%d")
    except Exception:
        doc_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    documents: list[dict[str, Any]] = []
    for part_idx, start in enumerate(range(0, len(eligible), DOC_PRODUCTS_LIMIT), start=1):
        part = eligible[start : start + DOC_PRODUCTS_LIMIT]
        if op_s == OP_WITHDRAW:
            products = [{"cis": ks, "product_cost": 0} for ks in part]
            doc_number = f"CAB-{doc_date.replace('-', '')}-{part_idx}"
            body = build_lk_receipt_document(
                inn=inn,
                action="DISTANCE",
                document_number=doc_number,
                document_date=doc_date,
                primary_document_type="OTHER",
                primary_document_custom_name="Кабинет ЧЗ"[:255],
                products=products,
                kpp=kpp,
                fias_id=fias_id,
            )
            documents.append(
                {
                    "doc_type": "LK_RECEIPT",
                    "product_group": pg,
                    "title": f"Вывод · кабинет ЧЗ · часть {part_idx}",
                    "kiz_shorts": part,
                    "sign_payload_b64": gtd_chz._b64_json(body),
                }
            )
        else:
            products = [{"ki": ks} for ks in part]
            ret_type = str(settings.get("return_type") or "REMOTE_SALE_RETURN").strip()
            body = build_lp_return_document(
                inn=inn,
                return_type=ret_type or "REMOTE_SALE_RETURN",
                products=products,
                paid=False,
            )
            documents.append(
                {
                    "doc_type": "LP_RETURN",
                    "product_group": pg,
                    "title": f"Ввод · кабинет ЧЗ · часть {part_idx}",
                    "kiz_shorts": part,
                    "sign_payload_b64": gtd_chz._b64_json(body),
                }
            )
    return {
        "ok": True,
        "op": op_s,
        "documents": documents,
        "eligible": len(eligible),
        "skipped": skipped,
        "settings": {
            "cert_thumbprint": str(settings.get("cert_thumbprint") or ""),
            "participant_inn": inn,
            "product_group": pg,
        },
    }


def _mark_op(
    repo: ReviewRepository,
    *,
    user_id: int,
    kiz_shorts: list[str],
    op: str,
    doc_id: str = "",
    doc_type: str = "",
    op_status: str = "",
    op_error: str = "",
) -> None:
    if not kiz_shorts:
        return
    with repo._connect() as conn:
        for ks in kiz_shorts:
            conn.execute(
                repo._sql(
                    """
                    UPDATE supply_chz_cabinet_kiz SET
                        last_op = ?, last_doc_id = ?, last_doc_type = ?,
                        last_op_status = ?, last_op_error = ?, updated_at = NOW()
                    WHERE user_id = ? AND kiz_short = ?
                    """
                ),
                (
                    op[:40],
                    doc_id[:80],
                    doc_type[:40],
                    op_status[:40],
                    op_error[:2000],
                    user_id,
                    ks,
                ),
            )


def submit_cabinet_documents(
    repo: ReviewRepository,
    *,
    user_id: int,
    token: str,
    op: str,
    documents: list[dict[str, Any]],
) -> dict[str, Any]:
    ensure_supply_chz_cabinet_tables(repo)
    settings = gtd_chz._chz_settings_ready(repo, user_id=user_id)
    op_s = str(op or "").strip().lower()
    if op_s not in {OP_WITHDRAW, OP_RETURN}:
        raise ValueError("op: withdraw или return")
    token_s = str(token or "").strip()
    if not token_s:
        raise ValueError("Нужен токен ЧЗ (подпишите УКЭП)")
    docs = [d for d in (documents or []) if isinstance(d, dict)]
    if not docs:
        raise ValueError("Нет документов для отправки")
    client: ChzTrueApiClient = kiz_circ.chz_client_from_settings(settings)
    client.set_token(token_s)
    pg_default = str(settings.get("product_group") or "").strip()
    requested = sum(len(d.get("kiz_shorts") or []) for d in docs)
    run_id = _start_run(repo, user_id=user_id, op=op_s, requested=requested)
    log: list[str] = []
    label = "вывод" if op_s == OP_WITHDRAW else "ввод"
    gtd_chz._append_log(log, f"Отправка в ЧЗ ({label}): док. {len(docs)}")
    submitted = failed = 0
    try:
        for i, doc in enumerate(docs, start=1):
            doc_type = str(doc.get("doc_type") or "").strip()
            pg = str(doc.get("product_group") or pg_default).strip()
            sig = str(doc.get("signature_base64") or doc.get("signature_b64") or "").strip()
            payload_b64 = str(
                doc.get("product_document_b64") or doc.get("sign_payload_b64") or ""
            ).strip()
            kiz_list = [
                str(x).strip() for x in (doc.get("kiz_shorts") or []) if str(x or "").strip()
            ]
            title = str(doc.get("title") or doc_type)
            if not doc_type or not sig or not payload_b64:
                failed += 1
                gtd_chz._append_log(log, f"{i}. {title}: нет подписи/payload")
                _mark_op(
                    repo,
                    user_id=user_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_type=doc_type,
                    op_status="error",
                    op_error="Нет подписи или payload",
                )
                continue
            try:
                doc_id = client.create_document(
                    doc_type=doc_type,
                    product_group=pg,
                    signature_b64=sig,
                    product_document_b64=payload_b64,
                )
                submitted += 1
                gtd_chz._append_log(log, f"{i}. {title}: OK id={doc_id} ({len(kiz_list)} КИЗ)")
                _mark_op(
                    repo,
                    user_id=user_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_id=str(doc_id),
                    doc_type=doc_type,
                    op_status="submitted",
                )
            except ChzTrueApiError as exc:
                failed += 1
                gtd_chz._append_log(log, f"{i}. {title}: ошибка {exc}")
                _mark_op(
                    repo,
                    user_id=user_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_type=doc_type,
                    op_status="error",
                    op_error=str(exc)[:2000],
                )
        status = "ok" if failed == 0 else ("error" if submitted == 0 else "partial")
        _finish_run(
            repo,
            run_id=run_id,
            status=status,
            ok_count=submitted,
            err_count=failed,
            log_text="\n".join(log),
        )
    except Exception as exc:
        gtd_chz._append_log(log, f"Сбой: {exc}")
        _finish_run(
            repo,
            run_id=run_id,
            status="error",
            ok_count=submitted,
            err_count=failed + 1,
            log_text="\n".join(log),
        )
        raise
    return {
        "ok": failed == 0,
        "run_id": run_id,
        "submitted": submitted,
        "failed": failed,
        "log_text": "\n".join(log),
    }
