"""Supply settings → ГТД: import customs declaration PDF and store KIZ map.

Parses text PDFs of «Декларация на товары» / «Дополнение к ДТ»:
- GTD number ``NNNNNNNN/DDMMYY/NNNNNNN``
- Identification marks from box 31 (short CHZ unit codes ``01``+GTIN14+``21``+serial)

No overwrite: existing GTD number is rejected; existing KIZ rows are kept
and reported as already-in-db (same or other GTD).
"""
from __future__ import annotations

import logging
import re
from typing import Any

from .repository import ReviewRepository
from .wb_fbs_kiz_restore import normalize_kiz_mark

_log = logging.getLogger(__name__)

# GS1 CSET 82 (AI 21 serial) — same set as CHZ circulation helpers.
_CSET82 = frozenset(
    "!\"%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"
)

_GTD_RE = re.compile(r"\b(\d{8}/\d{6}/\d{7})\b")
# Short unit KIZ as printed in DT box 31 (no crypto tail).
_KIZ_FIND_RE = re.compile(
    r"01(\d{14})21([!\"%&'()*+,\-./0-9:;<=>?A-Z_a-z]{6,20})"
)
_QTY_SHT_RE = re.compile(
    r"(\d+(?:[.,]\d+)?)\s*ШТ",
    re.IGNORECASE,
)

_MAX_PDF_BYTES = 80 * 1024 * 1024  # 80 MB
_INSERT_BATCH = 1500


def ensure_supply_gtd_tables(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_gtd_documents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    gtd_number TEXT NOT NULL,
                    note TEXT NOT NULL DEFAULT '',
                    source_filename TEXT NOT NULL DEFAULT '',
                    page_count INTEGER NOT NULL DEFAULT 0,
                    kiz_parsed INTEGER NOT NULL DEFAULT 0,
                    kiz_inserted INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, gtd_number)
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_gtd_kiz (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    gtd_id BIGINT NOT NULL REFERENCES supply_gtd_documents(id)
                        ON DELETE CASCADE,
                    gtd_number TEXT NOT NULL,
                    kiz_short TEXT NOT NULL,
                    gtin TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, kiz_short)
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_gtd_docs_user
                ON supply_gtd_documents (user_id, created_at DESC)
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_gtd_kiz_user_gtd
                ON supply_gtd_kiz (user_id, gtd_number)
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_gtd_kiz_user_short
                ON supply_gtd_kiz (user_id, kiz_short)
                """
            )
        )


def normalize_gtd_number(value: object) -> str:
    text = str(value or "").strip()
    m = _GTD_RE.search(text)
    if m:
        return m.group(1)
    compact = text.replace(" ", "")
    m2 = _GTD_RE.search(compact)
    return m2.group(1) if m2 else ""


def gtin14_checksum_ok(gtin: str) -> bool:
    if not re.fullmatch(r"\d{14}", gtin or ""):
        return False
    digits = [int(c) for c in gtin]
    check = digits[-1]
    body = digits[:-1]
    total = 0
    for i, d in enumerate(reversed(body)):
        total += d * (3 if i % 2 == 0 else 1)
    calc = (10 - (total % 10)) % 10
    return calc == check


def kiz_short_from_raw(raw: object) -> str:
    """Return validated short unit code ``01+GTIN+21+serial`` or empty."""
    text = normalize_kiz_mark(raw)
    if not text:
        return ""
    # Prefer unit before crypto AIs.
    for sep in ("\u001d", "\x1d"):
        if sep in text:
            head = text.split(sep, 1)[0]
            if head.startswith("01") and "21" in head:
                text = head
                break
    m = re.match(r"^01(\d{14})21(.+)$", text)
    if not m:
        return ""
    gtin, serial = m.group(1), m.group(2)
    # Cut crypto glued without GS (…2191… / …2192…).
    for ai in ("91", "92", "93"):
        idx = serial.find(ai)
        if idx > 0:
            serial = serial[:idx]
            break
    serial = "".join(ch for ch in serial if ch in _CSET82)
    if not (6 <= len(serial) <= 20):
        return ""
    if not gtin14_checksum_ok(gtin):
        return ""
    return f"01{gtin}21{serial}"


def _extract_pdf_text(pdf_bytes: bytes) -> tuple[str, int]:
    try:
        import pymupdf
    except ImportError as exc:
        raise RuntimeError(
            "Для разбора PDF ГТД нужен пакет pymupdf (pip install pymupdf)."
        ) from exc
    doc = pymupdf.open(stream=pdf_bytes, filetype="pdf")
    try:
        parts: list[str] = []
        for page in doc:
            parts.append(page.get_text("text") or "")
        return "\n".join(parts), int(doc.page_count or 0)
    finally:
        doc.close()


def parse_gtd_pdf(pdf_bytes: bytes) -> dict[str, Any]:
    """Parse DT/supplement PDF → gtd candidates + validated unique KIZ shorts."""
    if not pdf_bytes:
        raise ValueError("Пустой PDF")
    if len(pdf_bytes) > _MAX_PDF_BYTES:
        raise ValueError("PDF слишком большой (макс. 80 МБ)")
    text, page_count = _extract_pdf_text(pdf_bytes)
    if not str(text or "").strip():
        raise ValueError(
            "В PDF нет текстового слоя. Нужен текстовый PDF из таможенной программы, не скан-картинка."
        )

    gtd_hits = _GTD_RE.findall(text)
    gtd_preferred = ""
    # Prefer number after «К ДТ N» / in header; else first hit.
    m_dt = re.search(
        r"(?:К\s*ДТ\s*N|ДТ\s*N|ДЕКЛАРАЦИЯ[^\n]{0,40})\s*[^\d]{0,12}(\d{8}/\d{6}/\d{7})",
        text,
        re.IGNORECASE,
    )
    if m_dt:
        gtd_preferred = m_dt.group(1)
    elif gtd_hits:
        # Most common number in file usually is the declaration id.
        counts: dict[str, int] = {}
        for g in gtd_hits:
            counts[g] = counts.get(g, 0) + 1
        gtd_preferred = max(counts.items(), key=lambda kv: kv[1])[0]

    found: dict[str, str] = {}
    rejected = 0
    for m in _KIZ_FIND_RE.finditer(text):
        candidate = f"01{m.group(1)}21{m.group(2)}"
        short = kiz_short_from_raw(candidate)
        if not short:
            rejected += 1
            continue
        found.setdefault(short, short)

    qty_hint = 0
    for qm in _QTY_SHT_RE.finditer(text):
        try:
            qty_hint += int(float(str(qm.group(1)).replace(",", ".")))
        except (TypeError, ValueError):
            continue

    return {
        "gtd_number": gtd_preferred,
        "gtd_candidates": sorted(set(gtd_hits)),
        "page_count": page_count,
        "kiz_list": sorted(found.keys()),
        "kiz_parsed": len(found),
        "kiz_rejected": rejected,
        "qty_hint_sht": qty_hint if qty_hint > 0 else None,
    }


def get_gtd_by_number(
    repo: ReviewRepository, *, user_id: int, gtd_number: str
) -> dict[str, Any] | None:
    ensure_supply_gtd_tables(repo)
    num = normalize_gtd_number(gtd_number)
    if not num:
        return None
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM supply_gtd_documents
                WHERE user_id = ? AND gtd_number = ?
                """
            ),
            (user_id, num),
        ).fetchone()
    return repo._row_to_dict(row) if row else None


def list_gtd_documents(
    repo: ReviewRepository,
    *,
    user_id: int,
    kiz_scan: str | None = None,
) -> dict[str, Any]:
    ensure_supply_gtd_tables(repo)
    scan = str(kiz_scan or "").strip()
    short = kiz_short_from_raw(scan) if scan else ""
    # Also try raw extract if scan is already short / partial.
    if scan and not short:
        return {
            "items": [],
            "total": 0,
            "kiz_query": scan,
            "kiz_resolved": False,
        }
    with repo._connect() as conn:
        if short:
            rows = conn.execute(
                repo._sql(
                    """
                    SELECT d.*,
                           (SELECT COUNT(*) FROM supply_gtd_kiz k
                            WHERE k.gtd_id = d.id) AS kiz_count
                    FROM supply_gtd_documents d
                    INNER JOIN supply_gtd_kiz kz
                      ON kz.gtd_id = d.id AND kz.user_id = d.user_id
                    WHERE d.user_id = ? AND kz.kiz_short = ?
                    ORDER BY d.created_at DESC, d.id DESC
                    """
                ),
                (user_id, short),
            ).fetchall()
        else:
            rows = conn.execute(
                repo._sql(
                    """
                    SELECT d.*,
                           (SELECT COUNT(*) FROM supply_gtd_kiz k
                            WHERE k.gtd_id = d.id) AS kiz_count
                    FROM supply_gtd_documents d
                    WHERE d.user_id = ?
                    ORDER BY d.created_at DESC, d.id DESC
                    """
                ),
                (user_id,),
            ).fetchall()
    items = [repo._row_to_dict(r) for r in rows]
    for it in items:
        it["kiz_count"] = int(it.get("kiz_count") or it.get("kiz_inserted") or 0)
        it["created_at"] = str(it.get("created_at") or "")
    return {
        "items": items,
        "total": len(items),
        "kiz_query": short or (scan if scan else ""),
        "kiz_resolved": bool(short),
    }


def import_gtd_pdf(
    repo: ReviewRepository,
    *,
    user_id: int,
    pdf_bytes: bytes,
    gtd_number: str,
    note: str = "",
    filename: str = "",
) -> dict[str, Any]:
    """Import PDF. Refuses if GTD number already exists for the tenant."""
    ensure_supply_gtd_tables(repo)
    manual = normalize_gtd_number(gtd_number)
    if not manual:
        raise ValueError(
            "Укажите номер ГТД в формате 12345678/010126/1234567"
        )

    parsed = parse_gtd_pdf(pdf_bytes)
    pdf_gtd = normalize_gtd_number(parsed.get("gtd_number") or "")
    warnings: list[str] = []
    if pdf_gtd and pdf_gtd != manual:
        warnings.append(
            f"В PDF найден номер {pdf_gtd}, в форме указан {manual}. "
            "Сохраняем номер из формы."
        )
    if not pdf_gtd:
        warnings.append(
            "Номер ГТД в PDF не распознан автоматически — использован номер из формы."
        )

    existing = get_gtd_by_number(repo, user_id=user_id, gtd_number=manual)
    if existing:
        raise ValueError(
            f"ГТД {manual} уже загружена ранее "
            f"(id={existing.get('id')}, КИЗ={existing.get('kiz_inserted') or existing.get('kiz_parsed') or 0}). "
            "Повторная загрузка с перезаписью запрещена."
        )

    kiz_list: list[str] = list(parsed.get("kiz_list") or [])
    if not kiz_list:
        raise ValueError(
            "В PDF не найдено ни одного валидного КИЗ. "
            "Проверьте, что это дополнение к ДТ с блоком «средства идентификации»."
        )

    qty_hint = parsed.get("qty_hint_sht")
    if isinstance(qty_hint, int) and qty_hint > 0:
        if abs(qty_hint - len(kiz_list)) > max(5, int(qty_hint * 0.02)):
            warnings.append(
                f"В тексте ДТ сумма «ШТ» ≈ {qty_hint}, а уникальных КИЗ = {len(kiz_list)}. "
                "Сверьте с бумажной декларацией."
            )

    note_s = str(note or "").strip()[:2000]
    fname = str(filename or "").strip()[:255]

    # Pre-check which KIZ already exist (for report).
    already_same: list[str] = []
    already_other: list[dict[str, str]] = []
    with repo._connect() as conn:
        for i in range(0, len(kiz_list), _INSERT_BATCH):
            chunk = kiz_list[i : i + _INSERT_BATCH]
            placeholders = ",".join("?" for _ in chunk)
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT kiz_short, gtd_number FROM supply_gtd_kiz
                    WHERE user_id = ? AND kiz_short IN ({placeholders})
                    """
                ),
                (user_id, *chunk),
            ).fetchall()
            for r in rows:
                d = repo._row_to_dict(r)
                ks = str(d.get("kiz_short") or "")
                gn = str(d.get("gtd_number") or "")
                if gn == manual:
                    already_same.append(ks)
                else:
                    already_other.append({"kiz_short": ks, "gtd_number": gn})

    already_set = {x for x in already_same} | {x["kiz_short"] for x in already_other}
    to_insert = [k for k in kiz_list if k not in already_set]

    with repo._connect() as conn:
        cur = conn.execute(
            repo._sql(
                """
                INSERT INTO supply_gtd_documents (
                    user_id, gtd_number, note, source_filename, page_count,
                    kiz_parsed, kiz_inserted
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """
            ),
            (
                user_id,
                manual,
                note_s,
                fname,
                int(parsed.get("page_count") or 0),
                len(kiz_list),
                len(to_insert),
            ),
        )
        row = cur.fetchone()
        gtd_id = int(row["id"] if hasattr(row, "keys") else row[0])

        inserted = 0
        for i in range(0, len(to_insert), _INSERT_BATCH):
            chunk = to_insert[i : i + _INSERT_BATCH]
            args: list[Any] = []
            values_sql = []
            for ks in chunk:
                gtin = ks[2:16] if len(ks) >= 16 else ""
                values_sql.append("(?, ?, ?, ?, ?)")
                args.extend([user_id, gtd_id, manual, ks, gtin])
            if not values_sql:
                continue
            conn.execute(
                repo._sql(
                    f"""
                    INSERT INTO supply_gtd_kiz (
                        user_id, gtd_id, gtd_number, kiz_short, gtin
                    ) VALUES {", ".join(values_sql)}
                    ON CONFLICT (user_id, kiz_short) DO NOTHING
                    """
                ),
                tuple(args),
            )
            inserted += len(chunk)

        # Re-count actual rows for this gtd (in case of race).
        cnt_row = conn.execute(
            repo._sql(
                """
                SELECT COUNT(*) AS n FROM supply_gtd_kiz
                WHERE user_id = ? AND gtd_id = ?
                """
            ),
            (user_id, gtd_id),
        ).fetchone()
        real_n = int(cnt_row["n"] if hasattr(cnt_row, "keys") else cnt_row[0] or 0)
        conn.execute(
            repo._sql(
                """
                UPDATE supply_gtd_documents
                SET kiz_inserted = ?
                WHERE id = ? AND user_id = ?
                """
            ),
            (real_n, gtd_id, user_id),
        )

    other_preview = already_other[:20]
    return {
        "ok": True,
        "gtd_id": gtd_id,
        "gtd_number": manual,
        "note": note_s,
        "source_filename": fname,
        "page_count": int(parsed.get("page_count") or 0),
        "kiz_parsed": len(kiz_list),
        "kiz_inserted": real_n,
        "kiz_already_in_db": len(already_set),
        "kiz_already_same_gtd": len(already_same),
        "kiz_already_other_gtd": len(already_other),
        "kiz_rejected_invalid": int(parsed.get("kiz_rejected") or 0),
        "qty_hint_sht": qty_hint,
        "warnings": warnings,
        "already_other_gtd_samples": other_preview,
        "message": (
            f"ГТД {manual} записана. КИЗ в PDF: {len(kiz_list)}, "
            f"добавлено новых: {real_n}, уже были в базе: {len(already_set)}."
        ),
    }


def lookup_gtd_by_kiz(
    repo: ReviewRepository, *, user_id: int, kiz_scan: str
) -> dict[str, Any]:
    ensure_supply_gtd_tables(repo)
    short = kiz_short_from_raw(kiz_scan)
    if not short:
        return {"ok": False, "found": False, "message": "Не похоже на КИЗ", "item": None}
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT d.*, kz.kiz_short,
                       (SELECT COUNT(*) FROM supply_gtd_kiz k WHERE k.gtd_id = d.id) AS kiz_count
                FROM supply_gtd_kiz kz
                INNER JOIN supply_gtd_documents d ON d.id = kz.gtd_id
                WHERE kz.user_id = ? AND kz.kiz_short = ?
                LIMIT 1
                """
            ),
            (user_id, short),
        ).fetchone()
    if not row:
        return {
            "ok": True,
            "found": False,
            "kiz_short": short,
            "message": "КИЗ не найден ни в одной загруженной ГТД",
            "item": None,
        }
    item = repo._row_to_dict(row)
    item["kiz_count"] = int(item.get("kiz_count") or 0)
    item["created_at"] = str(item.get("created_at") or "")
    return {
        "ok": True,
        "found": True,
        "kiz_short": short,
        "message": f"Найдена ГТД {item.get('gtd_number')}",
        "item": item,
    }
