"""Поставки → Настройки → ГТД → «Работа с ЧЗ».

Список КИЗ ГТД, выгрузка статусов из True API, вывод (LK_RECEIPT / DISTANCE)
и ввод в оборот (LP_RETURN / REMOTE_SALE_RETURN).

Источник ЧЗ: Настройки → ЧЗ. WB FBS «Вывод КИЗ» не меняем.
"""

from __future__ import annotations

import base64
import json
import logging
import re
from datetime import datetime, timezone
from typing import Any
from zoneinfo import ZoneInfo

from .chz_true_api import (
    ChzTrueApiClient,
    ChzTrueApiError,
    build_lk_receipt_document,
    build_lp_return_document,
)
from .repository import ReviewRepository
from . import supply_gtd as gtd_mod
from . import wb_kiz_circulation as kiz_circ

_log = logging.getLogger(__name__)

CIS_CHUNK = int(getattr(kiz_circ, "CIS_INFO_CHUNK", 100) or 100)
DOC_PRODUCTS_LIMIT = int(getattr(kiz_circ, "CHZ_PRODUCTS_PER_DOC", 100) or 100)

OP_WITHDRAW = "withdraw"
OP_RETURN = "return"

KIND_IN = "in_circulation"
KIND_OUT = "withdrawn"
KIND_TRANSFERRED = "transferred"
KIND_EMPTY = "unchecked"
KIND_ERROR = "error"
KIND_PRE = "pre"
KIND_OTHER = "other"


def ensure_supply_gtd_chz_tables(repo: ReviewRepository) -> None:
    gtd_mod.ensure_supply_gtd_tables(repo)
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_gtd_chz_kiz_state (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    gtd_id BIGINT NOT NULL REFERENCES supply_gtd_documents(id)
                        ON DELETE CASCADE,
                    kiz_short TEXT NOT NULL,
                    cis_status TEXT NOT NULL DEFAULT '',
                    cis_status_kind TEXT NOT NULL DEFAULT '',
                    cis_status_label TEXT NOT NULL DEFAULT '',
                    cis_owner_inn TEXT NOT NULL DEFAULT '',
                    cis_status_error TEXT NOT NULL DEFAULT '',
                    cis_checked_at TIMESTAMPTZ,
                    last_op TEXT NOT NULL DEFAULT '',
                    last_doc_id TEXT NOT NULL DEFAULT '',
                    last_doc_type TEXT NOT NULL DEFAULT '',
                    last_op_status TEXT NOT NULL DEFAULT '',
                    last_op_error TEXT NOT NULL DEFAULT '',
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, gtd_id, kiz_short)
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_gtd_chz_state_gtd
                ON supply_gtd_chz_kiz_state (user_id, gtd_id)
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE TABLE IF NOT EXISTS supply_gtd_chz_runs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    gtd_id BIGINT NOT NULL REFERENCES supply_gtd_documents(id)
                        ON DELETE CASCADE,
                    op TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'running',
                    requested INTEGER NOT NULL DEFAULT 0,
                    ok_count INTEGER NOT NULL DEFAULT 0,
                    err_count INTEGER NOT NULL DEFAULT 0,
                    log_text TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    finished_at TIMESTAMPTZ
                )
                """
            )
        )
        conn.execute(
            repo._sql(
                """
                CREATE INDEX IF NOT EXISTS idx_supply_gtd_chz_runs_gtd
                ON supply_gtd_chz_runs (user_id, gtd_id, id DESC)
                """
            )
        )


def _moscow_today() -> str:
    try:
        return datetime.now(ZoneInfo("Europe/Moscow")).strftime("%Y-%m-%d")
    except Exception:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _b64_json(obj: dict[str, Any]) -> str:
    raw = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return base64.b64encode(raw).decode("ascii")


def _append_log(lines: list[str], msg: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    lines.append(f"[{ts}] {msg}")


def _require_gtd(
    repo: ReviewRepository, *, user_id: int, gtd_id: int
) -> dict[str, Any]:
    item = gtd_mod.get_gtd_by_id(repo, user_id=user_id, gtd_id=int(gtd_id))
    if not item:
        raise ValueError("ГТД не найдена")
    return item


def _chz_settings_ready(repo: ReviewRepository, *, user_id: int) -> dict[str, Any]:
    settings = kiz_circ.get_chz_settings(repo, user_id=user_id)
    if not settings.get("is_enabled"):
        raise ValueError("ЧЗ выключен в Настройки → ЧЗ")
    inn = str(settings.get("participant_inn") or "").strip()
    if not inn:
        raise ValueError("Укажите ИНН участника в Настройки → ЧЗ")
    pg = str(settings.get("product_group") or "").strip()
    if not pg:
        raise ValueError("Укажите товарную группу в Настройки → ЧЗ")
    if pg.isdigit():
        raise ValueError(
            "Товарная группа — код True API (например lp, shoes), не число"
        )
    return settings


def _display_kind(
    *,
    status: str,
    owner_inn: str,
    participant_inn: str,
    error: str = "",
) -> tuple[str, str]:
    """Return (label, kind). Foreign owner → transferred (not withdrawn)."""
    if error and not status:
        return (error[:80] or "Ошибка", KIND_ERROR)
    if not status and not owner_inn:
        return ("Не проверен", KIND_EMPTY)
    if kiz_circ.cis_owner_is_foreign(
        owner_inn=owner_inn, participant_inn=participant_inn
    ):
        return ("Передан", KIND_TRANSFERRED)
    label = kiz_circ.cis_status_label(status)
    kind = kiz_circ.classify_cis_status(status)
    if kind == "unknown" and not status:
        return ("Не проверен", KIND_EMPTY)
    if kind == "unknown":
        kind = KIND_OTHER
    return (label or status or "—", kind)


def list_gtd_kiz_for_chz(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    offset: int = 0,
    limit: int = 2000,
    status_kind: str = "",
) -> dict[str, Any]:
    ensure_supply_gtd_chz_tables(repo)
    gtd = _require_gtd(repo, user_id=user_id, gtd_id=gtd_id)
    off = max(0, int(offset or 0))
    lim = max(1, min(int(limit or 2000), 5000))
    kind_filter = str(status_kind or "").strip()

    with repo._connect() as conn:
        total_row = conn.execute(
            repo._sql(
                """
                SELECT COUNT(*) AS n FROM supply_gtd_kiz
                WHERE user_id = ? AND gtd_id = ?
                """
            ),
            (user_id, int(gtd_id)),
        ).fetchone()
        total = int(repo._row_to_dict(total_row).get("n") or 0)
        rows = conn.execute(
            repo._sql(
                """
                SELECT k.id AS kiz_id, k.kiz_short, k.gtin,
                       s.cis_status, s.cis_status_kind, s.cis_status_label,
                       s.cis_owner_inn, s.cis_status_error, s.cis_checked_at,
                       s.last_op, s.last_doc_id, s.last_doc_type,
                       s.last_op_status, s.last_op_error
                FROM supply_gtd_kiz k
                LEFT JOIN supply_gtd_chz_kiz_state s
                  ON s.user_id = k.user_id AND s.gtd_id = k.gtd_id
                 AND s.kiz_short = k.kiz_short
                WHERE k.user_id = ? AND k.gtd_id = ?
                ORDER BY k.id ASC
                """
            ),
            (user_id, int(gtd_id)),
        ).fetchall()

    items: list[dict[str, Any]] = []
    kind_counts: dict[str, int] = {}
    for r in rows:
        d = repo._row_to_dict(r)
        kind = str(d.get("cis_status_kind") or "").strip() or KIND_EMPTY
        label = str(d.get("cis_status_label") or "").strip() or (
            "Не проверен" if kind == KIND_EMPTY else ""
        )
        kind_counts[kind] = kind_counts.get(kind, 0) + 1
        if kind_filter and kind != kind_filter:
            continue
        items.append(
            {
                "kiz_id": int(d.get("kiz_id") or 0),
                "kiz_short": str(d.get("kiz_short") or ""),
                "gtin": str(d.get("gtin") or ""),
                "cis_status": str(d.get("cis_status") or ""),
                "cis_status_kind": kind,
                "cis_status_label": label,
                "cis_owner_inn": str(d.get("cis_owner_inn") or ""),
                "cis_status_error": str(d.get("cis_status_error") or ""),
                "cis_checked_at": str(d.get("cis_checked_at") or ""),
                "last_op": str(d.get("last_op") or ""),
                "last_doc_id": str(d.get("last_doc_id") or ""),
                "last_doc_type": str(d.get("last_doc_type") or ""),
                "last_op_status": str(d.get("last_op_status") or ""),
                "last_op_error": str(d.get("last_op_error") or ""),
            }
        )

    filtered_total = len(items)
    page = items[off : off + lim]
    return {
        "ok": True,
        "gtd": {
            "id": int(gtd.get("id") or gtd_id),
            "gtd_number": str(gtd.get("gtd_number") or ""),
            "kiz_count": int(gtd.get("kiz_count") or total),
            "note": str(gtd.get("note") or ""),
        },
        "total": total,
        "filtered_total": filtered_total,
        "offset": off,
        "limit": lim,
        "has_more": off + lim < filtered_total,
        "kind_counts": kind_counts,
        "items": page,
    }


def _start_run(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    op: str,
    requested: int,
) -> int:
    with repo._connect() as conn:
        cur = conn.execute(
            repo._sql(
                """
                INSERT INTO supply_gtd_chz_runs (
                    user_id, gtd_id, op, status, requested, log_text, created_at
                ) VALUES (?, ?, ?, 'running', ?, '', NOW())
                RETURNING id
                """
            ),
            (user_id, int(gtd_id), op, int(requested)),
        )
        row = cur.fetchone()
    return int(repo._row_to_dict(row).get("id") or 0)


def _finish_run(
    repo: ReviewRepository,
    *,
    run_id: int,
    status: str,
    ok_count: int = 0,
    err_count: int = 0,
    log_text: str = "",
) -> None:
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                UPDATE supply_gtd_chz_runs
                SET status = ?, ok_count = ?, err_count = ?, log_text = ?,
                    finished_at = NOW()
                WHERE id = ?
                """
            ),
            (
                str(status or "done")[:40],
                int(ok_count),
                int(err_count),
                str(log_text or "")[:50000],
                int(run_id),
            ),
        )


def get_run(
    repo: ReviewRepository, *, user_id: int, run_id: int
) -> dict[str, Any] | None:
    ensure_supply_gtd_chz_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM supply_gtd_chz_runs
                WHERE user_id = ? AND id = ?
                """
            ),
            (user_id, int(run_id)),
        ).fetchone()
    if not row:
        return None
    d = repo._row_to_dict(row)
    return {
        "id": int(d.get("id") or 0),
        "gtd_id": int(d.get("gtd_id") or 0),
        "op": str(d.get("op") or ""),
        "status": str(d.get("status") or ""),
        "requested": int(d.get("requested") or 0),
        "ok_count": int(d.get("ok_count") or 0),
        "err_count": int(d.get("err_count") or 0),
        "log_text": str(d.get("log_text") or ""),
        "created_at": str(d.get("created_at") or ""),
        "finished_at": str(d.get("finished_at") or ""),
    }


def latest_run_for_gtd(
    repo: ReviewRepository, *, user_id: int, gtd_id: int
) -> dict[str, Any] | None:
    ensure_supply_gtd_chz_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT id FROM supply_gtd_chz_runs
                WHERE user_id = ? AND gtd_id = ?
                ORDER BY id DESC
                LIMIT 1
                """
            ),
            (user_id, int(gtd_id)),
        ).fetchone()
    if not row:
        return None
    return get_run(
        repo, user_id=user_id, run_id=int(repo._row_to_dict(row).get("id") or 0)
    )


def _load_gtd_kiz_codes(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    kiz_shorts: list[str] | None = None,
) -> list[str]:
    wanted = [str(x).strip() for x in (kiz_shorts or []) if str(x or "").strip()]
    with repo._connect() as conn:
        if wanted:
            found: list[str] = []
            for i in range(0, len(wanted), 500):
                chunk = wanted[i : i + 500]
                ph = ",".join("?" for _ in chunk)
                rows = conn.execute(
                    repo._sql(
                        f"""
                        SELECT kiz_short FROM supply_gtd_kiz
                        WHERE user_id = ? AND gtd_id = ?
                          AND kiz_short IN ({ph})
                        """
                    ),
                    (user_id, int(gtd_id), *chunk),
                ).fetchall()
                for r in rows:
                    ks = str(repo._row_to_dict(r).get("kiz_short") or "").strip()
                    if ks:
                        found.append(ks)
            pos = {k: i for i, k in enumerate(wanted)}
            found.sort(key=lambda k: pos.get(k, 10**9))
            return found
        rows = conn.execute(
            repo._sql(
                """
                SELECT kiz_short FROM supply_gtd_kiz
                WHERE user_id = ? AND gtd_id = ?
                ORDER BY id ASC
                """
            ),
            (user_id, int(gtd_id)),
        ).fetchall()
    return [
        str(repo._row_to_dict(r).get("kiz_short") or "").strip()
        for r in rows
        if str(repo._row_to_dict(r).get("kiz_short") or "").strip()
    ]


def _upsert_cis_state(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    kiz_short: str,
    cis_status: str = "",
    cis_owner_inn: str = "",
    cis_status_error: str = "",
    participant_inn: str = "",
) -> None:
    label, kind = _display_kind(
        status=cis_status,
        owner_inn=cis_owner_inn,
        participant_inn=participant_inn,
        error=cis_status_error,
    )
    with repo._connect() as conn:
        conn.execute(
            repo._sql(
                """
                INSERT INTO supply_gtd_chz_kiz_state (
                    user_id, gtd_id, kiz_short, cis_status, cis_status_kind,
                    cis_status_label, cis_owner_inn, cis_status_error,
                    cis_checked_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
                ON CONFLICT (user_id, gtd_id, kiz_short) DO UPDATE SET
                    cis_status = EXCLUDED.cis_status,
                    cis_status_kind = EXCLUDED.cis_status_kind,
                    cis_status_label = EXCLUDED.cis_status_label,
                    cis_owner_inn = EXCLUDED.cis_owner_inn,
                    cis_status_error = EXCLUDED.cis_status_error,
                    cis_checked_at = EXCLUDED.cis_checked_at,
                    updated_at = EXCLUDED.updated_at
                """
            ),
            (
                user_id,
                int(gtd_id),
                kiz_short,
                str(cis_status or "")[:80],
                str(kind or "")[:40],
                str(label or "")[:120],
                str(cis_owner_inn or "")[:20],
                str(cis_status_error or "")[:2000],
            ),
        )


def _mark_op_state(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    kiz_shorts: list[str],
    op: str,
    doc_id: str = "",
    doc_type: str = "",
    op_status: str = "",
    op_error: str = "",
) -> None:
    for ks in kiz_shorts:
        with repo._connect() as conn:
            conn.execute(
                repo._sql(
                    """
                    INSERT INTO supply_gtd_chz_kiz_state (
                        user_id, gtd_id, kiz_short, last_op, last_doc_id,
                        last_doc_type, last_op_status, last_op_error, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())
                    ON CONFLICT (user_id, gtd_id, kiz_short) DO UPDATE SET
                        last_op = EXCLUDED.last_op,
                        last_doc_id = EXCLUDED.last_doc_id,
                        last_doc_type = EXCLUDED.last_doc_type,
                        last_op_status = EXCLUDED.last_op_status,
                        last_op_error = EXCLUDED.last_op_error,
                        updated_at = EXCLUDED.updated_at
                    """
                ),
                (
                    user_id,
                    int(gtd_id),
                    ks,
                    str(op or "")[:40],
                    str(doc_id or "")[:120],
                    str(doc_type or "")[:40],
                    str(op_status or "")[:40],
                    str(op_error or "")[:2000],
                ),
            )


def refresh_gtd_cis_statuses(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    token: str,
    kiz_shorts: list[str] | None = None,
) -> dict[str, Any]:
    ensure_supply_gtd_chz_tables(repo)
    _require_gtd(repo, user_id=user_id, gtd_id=gtd_id)
    settings = _chz_settings_ready(repo, user_id=user_id)
    codes = _load_gtd_kiz_codes(
        repo, user_id=user_id, gtd_id=gtd_id, kiz_shorts=kiz_shorts
    )
    if not codes:
        raise ValueError("Нет КИЗ для проверки")
    token_s = str(token or "").strip()
    if not token_s:
        raise ValueError("Нужен токен ЧЗ (подпишите УКЭП)")

    client = kiz_circ.chz_client_from_settings(settings)
    client.set_token(token_s)
    pg = str(settings.get("product_group") or "").strip()
    inn = str(settings.get("participant_inn") or "").strip()

    run_id = _start_run(
        repo, user_id=user_id, gtd_id=gtd_id, op="cis_status", requested=len(codes)
    )
    log: list[str] = []
    _append_log(log, f"Выгрузка статусов ЧЗ: кодов {len(codes)}")

    updated = found = missing = errors = 0
    try:
        for i in range(0, len(codes), CIS_CHUNK):
            part = codes[i : i + CIS_CHUNK]
            try:
                rows_api = client.cises_info(part, product_group=pg)
                parsed = [
                    kiz_circ.parse_cises_info_item(x if isinstance(x, dict) else None)
                    for x in rows_api
                ]
                nf = sum(
                    1
                    for p in parsed
                    if "не найден" in (p.get("error") or "").lower()
                    or p.get("error_code") == "404"
                )
                if pg and parsed and nf == len(parsed) == len(part):
                    _append_log(log, f"pg={pg}: все «не найден» — повтор без pg")
                    rows_api = client.cises_info(part, product_group="")
                    parsed = [
                        kiz_circ.parse_cises_info_item(
                            x if isinstance(x, dict) else None
                        )
                        for x in rows_api
                    ]
            except ChzTrueApiError as exc:
                errors += len(part)
                _append_log(log, f"Ошибка API: {exc}")
                for ks in part:
                    _upsert_cis_state(
                        repo,
                        user_id=user_id,
                        gtd_id=gtd_id,
                        kiz_short=ks,
                        cis_status_error=str(exc)[:500],
                        participant_inn=inn,
                    )
                    updated += 1
                continue

            by_key: dict[str, dict[str, str]] = {}
            for idx, p in enumerate(parsed):
                req = part[idx] if idx < len(part) else ""
                keys = {req, str(p.get("cis") or "").strip()}
                for k in list(keys):
                    if k:
                        keys.add(k.split("\x1d", 1)[0])
                for k in keys:
                    if k and k not in by_key:
                        by_key[k] = p

            for ks in part:
                hit = by_key.get(ks)
                if not hit:
                    for k, p in by_key.items():
                        if k.startswith(ks) or ks.startswith(k):
                            hit = p
                            break
                if not hit:
                    missing += 1
                    _upsert_cis_state(
                        repo,
                        user_id=user_id,
                        gtd_id=gtd_id,
                        kiz_short=ks,
                        cis_status_error="КИЗ не найден в ответе ЧЗ",
                        participant_inn=inn,
                    )
                    updated += 1
                    continue
                err = str(hit.get("error") or "").strip()
                status = str(hit.get("status") or "").strip()
                owner = str(hit.get("owner_inn") or "").strip()
                if err and not status:
                    errors += 1
                elif status:
                    found += 1
                else:
                    missing += 1
                _upsert_cis_state(
                    repo,
                    user_id=user_id,
                    gtd_id=gtd_id,
                    kiz_short=ks,
                    cis_status=status,
                    cis_owner_inn=owner,
                    cis_status_error=err,
                    participant_inn=inn,
                )
                updated += 1
            _append_log(log, f"Чанк {i // CIS_CHUNK + 1}: {len(part)} код.")

        _append_log(
            log,
            f"Готово: обновлено {updated}, найдено {found}, нет данных {missing}, ошибок {errors}",
        )
        _finish_run(
            repo,
            run_id=run_id,
            status="ok",
            ok_count=found,
            err_count=errors + missing,
            log_text="\n".join(log),
        )
    except Exception as exc:
        _append_log(log, f"Сбой: {exc}")
        _finish_run(
            repo,
            run_id=run_id,
            status="error",
            ok_count=found,
            err_count=errors + 1,
            log_text="\n".join(log),
        )
        raise

    return {
        "ok": True,
        "run_id": run_id,
        "requested": len(codes),
        "updated": updated,
        "found": found,
        "missing": missing,
        "errors": errors,
        "log_text": "\n".join(log),
    }


def _states_by_kiz(
    repo: ReviewRepository, *, user_id: int, gtd_id: int, kiz_shorts: list[str]
) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    if not kiz_shorts:
        return out
    with repo._connect() as conn:
        for i in range(0, len(kiz_shorts), 500):
            chunk = kiz_shorts[i : i + 500]
            ph = ",".join("?" for _ in chunk)
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT * FROM supply_gtd_chz_kiz_state
                    WHERE user_id = ? AND gtd_id = ?
                      AND kiz_short IN ({ph})
                    """
                ),
                (user_id, int(gtd_id), *chunk),
            ).fetchall()
            for r in rows:
                d = repo._row_to_dict(r)
                out[str(d.get("kiz_short") or "")] = d
    return out


def prepare_gtd_chz_documents(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    op: str,
    kiz_shorts: list[str],
) -> dict[str, Any]:
    ensure_supply_gtd_chz_tables(repo)
    gtd = _require_gtd(repo, user_id=user_id, gtd_id=gtd_id)
    settings = _chz_settings_ready(repo, user_id=user_id)
    op_s = str(op or "").strip().lower()
    if op_s not in {OP_WITHDRAW, OP_RETURN}:
        raise ValueError("op: withdraw или return")

    codes = _load_gtd_kiz_codes(
        repo, user_id=user_id, gtd_id=gtd_id, kiz_shorts=kiz_shorts
    )
    if not codes:
        raise ValueError("Выберите КИЗ")

    states = _states_by_kiz(repo, user_id=user_id, gtd_id=gtd_id, kiz_shorts=codes)
    eligible: list[str] = []
    skipped: list[dict[str, str]] = []
    for ks in codes:
        st = states.get(ks) or {}
        kind = str(st.get("cis_status_kind") or "").strip() or KIND_EMPTY
        last_op = str(st.get("last_op") or "").strip()
        last_op_status = str(st.get("last_op_status") or "").strip()
        # Already submitted to ЧЗ for this op — wait for status refresh / do not duplicate.
        if last_op_status == "submitted" and last_op == op_s:
            skipped.append(
                {
                    "kiz_short": ks,
                    "reason": "Уже отправлено в ЧЗ — сначала выгрузите статусы",
                }
            )
            continue
        if op_s == OP_WITHDRAW:
            if kind != KIND_IN:
                skipped.append(
                    {
                        "kiz_short": ks,
                        "reason": "Вывод доступен только для статуса «В обороте»",
                    }
                )
                continue
        else:
            if kind == KIND_TRANSFERRED:
                skipped.append(
                    {
                        "kiz_short": ks,
                        "reason": "Код передан другому ИНН — ввод недоступен",
                    }
                )
                continue
            if kind != KIND_OUT:
                skipped.append(
                    {
                        "kiz_short": ks,
                        "reason": "Ввод доступен для статуса «Выведен»",
                    }
                )
                continue
        eligible.append(ks)

    if not eligible:
        raise ValueError(
            "Нет подходящих КИЗ для операции. Сначала выгрузите статусы из ЧЗ."
        )

    inn = str(settings.get("participant_inn") or "").strip()
    pg = str(settings.get("product_group") or "").strip()
    kpp = str(settings.get("kpp") or "").strip()
    fias_id = str(settings.get("fias_id") or "").strip()
    if not kpp or not fias_id:
        place = kiz_circ.resolve_chz_place_details(
            repo, user_id=user_id, participant_inn=inn
        )
        if not kpp:
            kpp = str(place.get("kpp") or "").strip()
        if not fias_id:
            fias_id = str(place.get("fias_id") or "").strip()
    if len(re.sub(r"\D", "", inn)) == 12:
        kpp = ""

    if op_s == OP_WITHDRAW:
        if not fias_id or (len(re.sub(r"\D", "", inn)) == 10 and not kpp):
            raise ValueError(
                "Для вывода DISTANCE укажите КПП (ООО) и ФИАС МОД в Настройки → ЧЗ"
            )

    gtd_number = str(gtd.get("gtd_number") or "").strip()
    doc_date = _moscow_today()
    documents: list[dict[str, Any]] = []

    for part_idx, start in enumerate(range(0, len(eligible), DOC_PRODUCTS_LIMIT), start=1):
        part = eligible[start : start + DOC_PRODUCTS_LIMIT]
        if op_s == OP_WITHDRAW:
            products = [{"cis": ks, "product_cost": 0} for ks in part]
            doc_number = f"GTD-{int(gtd_id)}-{doc_date.replace('-', '')}-{part_idx}"
            body = build_lk_receipt_document(
                inn=inn,
                action="DISTANCE",
                document_number=doc_number,
                document_date=doc_date,
                primary_document_type="OTHER",
                primary_document_custom_name=f"ГТД {gtd_number}"[:255],
                products=products,
                kpp=kpp,
                fias_id=fias_id,
            )
            documents.append(
                {
                    "doc_type": "LK_RECEIPT",
                    "product_group": pg,
                    "title": f"Вывод · ГТД {gtd_number} · часть {part_idx}",
                    "kiz_shorts": part,
                    "product_document": body,
                    "sign_payload_b64": _b64_json(body),
                }
            )
        else:
            products = [{"ki": ks} for ks in part]
            ret_type = str(settings.get("return_type") or "REMOTE_SALE_RETURN").strip()
            body = build_lp_return_document(
                inn=inn,
                return_type=ret_type or "REMOTE_SALE_RETURN",
                products=products,
                paid=False,
            )
            documents.append(
                {
                    "doc_type": "LP_RETURN",
                    "product_group": pg,
                    "title": f"Ввод · ГТД {gtd_number} · часть {part_idx}",
                    "kiz_shorts": part,
                    "product_document": body,
                    "sign_payload_b64": _b64_json(body),
                }
            )

    return {
        "ok": True,
        "op": op_s,
        "gtd_id": int(gtd_id),
        "gtd_number": gtd_number,
        "documents": documents,
        "eligible": len(eligible),
        "skipped": skipped,
        "warnings": [],
        "settings": {
            "cert_thumbprint": str(settings.get("cert_thumbprint") or ""),
            "participant_inn": inn,
            "product_group": pg,
        },
    }


def submit_gtd_chz_documents(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtd_id: int,
    token: str,
    op: str,
    documents: list[dict[str, Any]],
) -> dict[str, Any]:
    ensure_supply_gtd_chz_tables(repo)
    _require_gtd(repo, user_id=user_id, gtd_id=gtd_id)
    settings = _chz_settings_ready(repo, user_id=user_id)
    op_s = str(op or "").strip().lower()
    if op_s not in {OP_WITHDRAW, OP_RETURN}:
        raise ValueError("op: withdraw или return")
    token_s = str(token or "").strip()
    if not token_s:
        raise ValueError("Нужен токен ЧЗ (подпишите УКЭП)")
    docs = [d for d in (documents or []) if isinstance(d, dict)]
    if not docs:
        raise ValueError("Нет документов для отправки")

    client: ChzTrueApiClient = kiz_circ.chz_client_from_settings(settings)
    client.set_token(token_s)
    pg_default = str(settings.get("product_group") or "").strip()

    requested = sum(len(d.get("kiz_shorts") or []) for d in docs)
    run_id = _start_run(
        repo, user_id=user_id, gtd_id=gtd_id, op=op_s, requested=requested
    )
    log: list[str] = []
    label = "вывод" if op_s == OP_WITHDRAW else "ввод"
    _append_log(log, f"Отправка в ЧЗ ({label}): док. {len(docs)}")

    submitted = failed = 0
    results: list[dict[str, Any]] = []
    try:
        for i, doc in enumerate(docs, start=1):
            doc_type = str(doc.get("doc_type") or "").strip()
            pg = str(doc.get("product_group") or pg_default).strip()
            sig = str(
                doc.get("signature_base64") or doc.get("signature_b64") or ""
            ).strip()
            payload_b64 = str(
                doc.get("product_document_b64") or doc.get("sign_payload_b64") or ""
            ).strip()
            kiz_list = [
                str(x).strip()
                for x in (doc.get("kiz_shorts") or [])
                if str(x or "").strip()
            ]
            title = str(doc.get("title") or doc_type)
            if not doc_type or not sig or not payload_b64:
                failed += 1
                _append_log(log, f"{i}. {title}: нет подписи/payload")
                _mark_op_state(
                    repo,
                    user_id=user_id,
                    gtd_id=gtd_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_type=doc_type,
                    op_status="error",
                    op_error="Нет подписи или payload",
                )
                results.append({"title": title, "ok": False, "error": "no signature"})
                continue
            try:
                doc_id = client.create_document(
                    doc_type=doc_type,
                    product_group=pg,
                    signature_b64=sig,
                    product_document_b64=payload_b64,
                )
                submitted += 1
                _append_log(
                    log, f"{i}. {title}: OK id={doc_id} ({len(kiz_list)} КИЗ)"
                )
                _mark_op_state(
                    repo,
                    user_id=user_id,
                    gtd_id=gtd_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_id=str(doc_id),
                    doc_type=doc_type,
                    op_status="submitted",
                )
                results.append(
                    {
                        "title": title,
                        "ok": True,
                        "document_id": str(doc_id),
                        "kiz_count": len(kiz_list),
                    }
                )
            except ChzTrueApiError as exc:
                failed += 1
                _append_log(log, f"{i}. {title}: ошибка {exc}")
                _mark_op_state(
                    repo,
                    user_id=user_id,
                    gtd_id=gtd_id,
                    kiz_shorts=kiz_list,
                    op=op_s,
                    doc_type=doc_type,
                    op_status="error",
                    op_error=str(exc)[:2000],
                )
                results.append({"title": title, "ok": False, "error": str(exc)})

        status = (
            "ok"
            if submitted and not failed
            else ("error" if not submitted else "partial")
        )
        _append_log(log, f"Итого: отправлено {submitted}, ошибок {failed}")
        _finish_run(
            repo,
            run_id=run_id,
            status=status,
            ok_count=submitted,
            err_count=failed,
            log_text="\n".join(log),
        )
    except Exception as exc:
        _append_log(log, f"Сбой: {exc}")
        _finish_run(
            repo,
            run_id=run_id,
            status="error",
            ok_count=submitted,
            err_count=failed + 1,
            log_text="\n".join(log),
        )
        raise

    return {
        "ok": failed == 0 and submitted > 0,
        "run_id": run_id,
        "submitted": submitted,
        "failed": failed,
        "results": results,
        "log_text": "\n".join(log),
    }
