"""Append-only WB FBS operations journal (owner gear modal).

Retention matches sync lookback days from the same auto-sync gear:
if lookback is 3 days, events older than 3 days are purged.
Writes never raise to callers — logging must not block operators.
"""
from __future__ import annotations

import json
import logging
import threading
from datetime import UTC, datetime
from typing import Any

from . import wb_fbs as wb
from .repository import ReviewRepository

_log = logging.getLogger(__name__)

ACTION_SYNC_START = "sync_start"
ACTION_SYNC_DONE = "sync_done"
ACTION_SYNC_STOP = "sync_stop"
ACTION_AUTO_SYNC = "auto_sync"
ACTION_COLLECT_START = "collect_start"
ACTION_COLLECT_DONE = "collect_done"
ACTION_AUTO_COLLECT = "auto_collect"
ACTION_SUPPLY_CREATE = "supply_create"
ACTION_SUPPLY_ADD = "supply_add"
ACTION_MARKING_SAVE = "marking_save"
ACTION_SETTINGS = "settings"

LEVEL_INFO = "info"
LEVEL_WARN = "warn"
LEVEL_ERROR = "error"

_cleanup_lock = threading.Lock()
_last_cleanup_at: dict[int, float] = {}
_CLEANUP_MIN_INTERVAL_SEC = 60.0


def ensure_wb_fbs_ops_log_table(repo: ReviewRepository) -> None:
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wb_fbs_ops_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                actor_user_id BIGINT,
                actor_name TEXT NOT NULL DEFAULT '',
                source_id BIGINT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                action TEXT NOT NULL DEFAULT '',
                level TEXT NOT NULL DEFAULT 'info',
                message TEXT NOT NULL DEFAULT '',
                order_id TEXT NOT NULL DEFAULT '',
                supply_id TEXT NOT NULL DEFAULT '',
                details_json TEXT NOT NULL DEFAULT '{}'
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_ops_log_user_time "
                "ON wb_fbs_ops_log(user_id, created_at DESC, id DESC)"
            )
        )


def actor_label(user: dict[str, Any] | None) -> str:
    if not isinstance(user, dict):
        return ""
    name = str(user.get("full_name") or user.get("email") or "").strip()
    if name:
        return name
    uid = user.get("id")
    return f"user:{uid}" if uid is not None else ""


def _lookback_days(repo: ReviewRepository, *, user_id: int) -> int:
    try:
        settings = repo.get_wb_fbs_auto_sync_settings(user_id=int(user_id))
        days = int(settings.get("lookback_days") or 3)
    except Exception:
        days = 3
    return max(1, min(days, 30))


def cleanup_old_events(
    repo: ReviewRepository,
    *,
    user_id: int,
    lookback_days: int | None = None,
    force: bool = False,
) -> int:
    """Delete events older than lookback days. Throttled unless force=True."""
    uid = int(user_id)
    days = int(lookback_days) if lookback_days is not None else _lookback_days(repo, user_id=uid)
    days = max(1, min(days, 30))
    now_mono = datetime.now(UTC).timestamp()
    with _cleanup_lock:
        last = _last_cleanup_at.get(uid, 0.0)
        if not force and (now_mono - last) < _CLEANUP_MIN_INTERVAL_SEC:
            return 0
        _last_cleanup_at[uid] = now_mono
    try:
        ensure_wb_fbs_ops_log_table(repo)
        cutoff = f"NOW() - INTERVAL '{days} days'"
        with repo._connect() as conn:
            cur = conn.execute(
                repo._sql(
                    f"DELETE FROM wb_fbs_ops_log WHERE user_id = ? AND created_at < {cutoff}"
                ),
                (uid,),
            )
            deleted = int(getattr(cur, "rowcount", 0) or 0)
        return max(0, deleted)
    except Exception as exc:
        _log.warning("wb_fbs ops log cleanup failed user=%s: %s", uid, exc)
        return 0


def append_event(
    repo: ReviewRepository,
    *,
    user_id: int,
    action: str,
    message: str,
    level: str = LEVEL_INFO,
    actor_user_id: int | None = None,
    actor_name: str = "",
    source_id: int | None = None,
    order_id: str = "",
    supply_id: str = "",
    details: dict[str, Any] | None = None,
) -> dict[str, Any] | None:
    """Append one journal row. Never raises — returns None on failure."""
    try:
        ensure_wb_fbs_ops_log_table(repo)
        cleanup_old_events(repo, user_id=int(user_id))
        msg = str(message or "").strip()
        if not msg:
            return None
        act = str(action or "").strip()[:64] or "event"
        lvl = str(level or LEVEL_INFO).strip().lower()
        if lvl not in (LEVEL_INFO, LEVEL_WARN, LEVEL_ERROR):
            lvl = LEVEL_INFO
        details_json = "{}"
        if isinstance(details, dict) and details:
            try:
                details_json = json.dumps(details, ensure_ascii=False, default=str)[:4000]
            except (TypeError, ValueError):
                details_json = "{}"
        now = datetime.now(UTC).isoformat()
        with repo._connect() as conn:
            event_id = repo._insert_and_get_id(
                conn,
                repo._sql(
                    """
                    INSERT INTO wb_fbs_ops_log (
                        user_id, actor_user_id, actor_name, source_id, created_at,
                        action, level, message, order_id, supply_id, details_json
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """
                ),
                (
                    int(user_id),
                    int(actor_user_id) if actor_user_id is not None else None,
                    str(actor_name or "").strip()[:200],
                    int(source_id) if source_id is not None else None,
                    now,
                    act,
                    lvl,
                    msg[:2000],
                    str(order_id or "").strip()[:128],
                    str(supply_id or "").strip()[:128],
                    details_json,
                ),
            )
        return {
            "id": int(event_id),
            "created_at": wb._normalize_kiz_saved_at(now) if now else "",
            "action": act,
            "level": lvl,
            "message": msg[:2000],
            "actor_name": str(actor_name or "").strip()[:200],
            "source_id": int(source_id) if source_id is not None else None,
            "order_id": str(order_id or "").strip()[:128],
            "supply_id": str(supply_id or "").strip()[:128],
        }
    except Exception as exc:
        _log.warning("wb_fbs ops log append failed: %s", exc)
        return None


def _row_to_api(repo: ReviewRepository, row: dict[str, Any]) -> dict[str, Any]:
    created = row.get("created_at")
    try:
        details = json.loads(str(row.get("details_json") or "{}"))
    except json.JSONDecodeError:
        details = {}
    if not isinstance(details, dict):
        details = {}
    sid = row.get("source_id")
    try:
        sid_out = int(sid) if sid is not None else None
    except (TypeError, ValueError):
        sid_out = None
    return {
        "id": int(row.get("id") or 0),
        "created_at": wb._normalize_kiz_saved_at(created) if created else "",
        "action": str(row.get("action") or "").strip(),
        "level": str(row.get("level") or LEVEL_INFO).strip(),
        "message": str(row.get("message") or "").strip(),
        "actor_name": str(row.get("actor_name") or "").strip(),
        "source_id": sid_out,
        "order_id": str(row.get("order_id") or "").strip(),
        "supply_id": str(row.get("supply_id") or "").strip(),
        "details": details,
    }


def list_events(
    repo: ReviewRepository,
    *,
    user_id: int,
    after_id: int = 0,
    limit: int = 200,
) -> dict[str, Any]:
    """List recent events for owner. Purges by lookback before read."""
    ensure_wb_fbs_ops_log_table(repo)
    lookback = _lookback_days(repo, user_id=int(user_id))
    cleanup_old_events(repo, user_id=int(user_id), lookback_days=lookback, force=True)
    lim = max(1, min(int(limit or 200), 500))
    after = max(0, int(after_id or 0))
    params: list[Any] = [int(user_id)]
    where_extra = ""
    if after > 0:
        where_extra = " AND id > ?"
        params.append(after)
    with repo._connect() as conn:
        if after > 0:
            rows = conn.execute(
                repo._sql(
                    f"""
                    SELECT id, actor_user_id, actor_name, source_id, created_at,
                           action, level, message, order_id, supply_id, details_json
                    FROM wb_fbs_ops_log
                    WHERE user_id = ?{where_extra}
                    ORDER BY id ASC
                    LIMIT ?
                    """
                ),
                (*params, lim),
            ).fetchall()
            items = [_row_to_api(repo, repo._row_to_dict(r)) for r in rows]
        else:
            rows = conn.execute(
                repo._sql(
                    """
                    SELECT id, actor_user_id, actor_name, source_id, created_at,
                           action, level, message, order_id, supply_id, details_json
                    FROM wb_fbs_ops_log
                    WHERE user_id = ?
                    ORDER BY id DESC
                    LIMIT ?
                    """
                ),
                (int(user_id), lim),
            ).fetchall()
            items = [_row_to_api(repo, repo._row_to_dict(r)) for r in rows]
            items.reverse()
    last_id = int(items[-1]["id"]) if items else after
    return {
        "ok": True,
        "items": items,
        "count": len(items),
        "last_id": last_id,
        "lookback_days": lookback,
        "retention_days": lookback,
    }
