"""WB FBS «Возвраты» — return sticker journal, goods-return sync, KIZ reprint."""

from __future__ import annotations

import csv
import io
import json
import logging
import re
import urllib.error
import urllib.request
from datetime import UTC, date, datetime, timedelta
from typing import Any
from urllib.parse import urlencode

from . import wb_fbs as wb
from . import wb_fbs_kiz_restore as kiz_restore
from .repository import ReviewRepository
from .wb_kiz_circulation import WB_ANALYTICS_API, get_wb_analytics_api_key

_log = logging.getLogger(__name__)

SCAN_RETURN = "return_sticker"
SCAN_ASSEMBLY = "assembly_sticker"
SCAN_KIZ = "kiz"


def ensure_wb_fbs_returns_tables(repo: ReviewRepository) -> None:
    wb.ensure_wb_fbs_tables(repo)
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wb_fbs_goods_returns (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                wb_order_id BIGINT NOT NULL DEFAULT 0,
                sticker_id TEXT NOT NULL DEFAULT '',
                barcode TEXT NOT NULL DEFAULT '',
                shk_id TEXT NOT NULL DEFAULT '',
                nm_id BIGINT,
                srid TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT '',
                reason TEXT NOT NULL DEFAULT '',
                ready_to_return_dt TEXT NOT NULL DEFAULT '',
                completed_dt TEXT NOT NULL DEFAULT '',
                order_dt TEXT NOT NULL DEFAULT '',
                raw_json TEXT NOT NULL DEFAULT '{}',
                synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_user_src "
                "ON wb_fbs_goods_returns(user_id, source_id, wb_order_id)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_sticker "
                "ON wb_fbs_goods_returns(user_id, source_id, sticker_id) "
                "WHERE sticker_id <> ''"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_srid_uniq "
                "ON wb_fbs_goods_returns(user_id, source_id, srid) "
                "WHERE srid <> ''"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wb_fbs_return_scans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                scan_type TEXT NOT NULL DEFAULT '',
                scan_raw TEXT NOT NULL DEFAULT '',
                return_sticker_id TEXT NOT NULL DEFAULT '',
                order_id BIGINT,
                assembly_sticker_barcode TEXT NOT NULL DEFAULT '',
                assembly_sticker_number TEXT NOT NULL DEFAULT '',
                kiz_code TEXT NOT NULL DEFAULT '',
                matched_order_ids_json TEXT NOT NULL DEFAULT '[]',
                product_name TEXT NOT NULL DEFAULT '',
                product_article TEXT NOT NULL DEFAULT '',
                product_photo TEXT NOT NULL DEFAULT '',
                product_barcodes_json TEXT NOT NULL DEFAULT '[]',
                gtin14 TEXT NOT NULL DEFAULT '',
                duplicate_of_id BIGINT
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_return_scans_user_src_time "
                "ON wb_fbs_return_scans(user_id, source_id, scanned_at DESC)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_wb_fbs_return_scans_return_dedup "
                "ON wb_fbs_return_scans(user_id, source_id, return_sticker_id) "
                "WHERE scan_type = 'return_sticker' AND return_sticker_id <> ''"
            )
        )


def _digits_only(value: object) -> str:
    return re.sub(r"\D+", "", str(value or ""))


def _scan_key(value: object) -> str:
    return kiz_restore.normalize_sticker_scan(value).casefold()


def _parse_iso_date(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return text[:10] if len(text) >= 10 else text


def fetch_goods_return_report(
    *,
    api_key: str,
    date_from: str,
    date_to: str,
    timeout: int = 60,
) -> list[dict[str, Any]]:
    """WB Analytics: GET /api/v1/analytics/goods-return (max 31 days)."""
    params = urlencode(
        {"dateFrom": _parse_iso_date(date_from), "dateTo": _parse_iso_date(date_to)}
    )
    url = f"{WB_ANALYTICS_API}/api/v1/analytics/goods-return?{params}"
    req = urllib.request.Request(
        url,
        method="GET",
        headers={
            "Authorization": str(api_key or "").strip(),
            "Accept": "application/json",
            "User-Agent": "FeedPilot-WBFBS-Returns/1.0",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = resp.read()
    except urllib.error.HTTPError as exc:
        err = ""
        try:
            err = exc.read().decode("utf-8", errors="replace")[:500]
        except Exception:
            pass
        raise RuntimeError(f"WB goods-return HTTP {exc.code}: {err or exc.reason}") from exc
    if not payload:
        return []
    parsed = json.loads(payload.decode("utf-8"))
    if isinstance(parsed, dict):
        report = parsed.get("report")
        if isinstance(report, list):
            return [x for x in report if isinstance(x, dict)]
    if isinstance(parsed, list):
        return [x for x in parsed if isinstance(x, dict)]
    return []


def sync_goods_returns(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    date_from: str,
    date_to: str,
) -> dict[str, Any]:
    ensure_wb_fbs_returns_tables(repo)
    rows = fetch_goods_return_report(
        api_key=api_key, date_from=date_from, date_to=date_to
    )
    now = datetime.now(UTC).isoformat()
    upserted = 0
    with repo._connect() as conn:
        for row in rows:
            try:
                order_id = int(row.get("orderId") or 0)
            except (TypeError, ValueError):
                order_id = 0
            sticker_id = str(row.get("stickerId") or "").strip()
            srid = str(row.get("srid") or "").strip()
            if not srid and not sticker_id and order_id <= 0:
                continue
            barcode = str(row.get("barcode") or "").strip()
            shk_id = str(row.get("shkId") or "").strip()
            try:
                nm_id = int(row.get("nmId") or 0) or None
            except (TypeError, ValueError):
                nm_id = None
            raw_json = json.dumps(row, ensure_ascii=False)
            status = str(row.get("status") or "").strip()
            reason = str(row.get("reason") or "").strip()
            ready_dt = str(row.get("readyToReturnDt") or "").strip()
            completed_dt = str(row.get("completedDt") or "").strip()
            order_dt = str(row.get("orderDt") or "").strip()
            values = (
                user_id,
                source_id,
                order_id,
                sticker_id,
                barcode,
                shk_id,
                nm_id,
                srid,
                status,
                reason,
                ready_dt,
                completed_dt,
                order_dt,
                raw_json,
                now,
            )
            if srid:
                conn.execute(
                    repo._sql(
                        """
                        INSERT INTO wb_fbs_goods_returns (
                            user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                            nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                            order_dt, raw_json, synced_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        ON CONFLICT (user_id, source_id, srid) WHERE srid <> ''
                        DO UPDATE SET
                            wb_order_id = EXCLUDED.wb_order_id,
                            sticker_id = EXCLUDED.sticker_id,
                            barcode = EXCLUDED.barcode,
                            shk_id = EXCLUDED.shk_id,
                            nm_id = EXCLUDED.nm_id,
                            status = EXCLUDED.status,
                            reason = EXCLUDED.reason,
                            ready_to_return_dt = EXCLUDED.ready_to_return_dt,
                            completed_dt = EXCLUDED.completed_dt,
                            order_dt = EXCLUDED.order_dt,
                            raw_json = EXCLUDED.raw_json,
                            synced_at = EXCLUDED.synced_at
                        """
                    ),
                    values,
                )
            elif order_id > 0 and sticker_id:
                cur = conn.execute(
                    repo._sql(
                        """
                        UPDATE wb_fbs_goods_returns SET
                            barcode = ?, shk_id = ?, nm_id = ?, status = ?, reason = ?,
                            ready_to_return_dt = ?, completed_dt = ?, order_dt = ?,
                            raw_json = ?, synced_at = ?
                        WHERE user_id = ? AND source_id = ? AND wb_order_id = ?
                          AND sticker_id = ? AND srid = ''
                        """
                    ),
                    (
                        barcode,
                        shk_id,
                        nm_id,
                        status,
                        reason,
                        ready_dt,
                        completed_dt,
                        order_dt,
                        raw_json,
                        now,
                        user_id,
                        source_id,
                        order_id,
                        sticker_id,
                    ),
                )
                if getattr(cur, "rowcount", 0) == 0:
                    conn.execute(
                        repo._sql(
                            """
                            INSERT INTO wb_fbs_goods_returns (
                                user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                                nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                                order_dt, raw_json, synced_at
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """
                        ),
                        values,
                    )
            else:
                conn.execute(
                    repo._sql(
                        """
                        INSERT INTO wb_fbs_goods_returns (
                            user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                            nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                            order_dt, raw_json, synced_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """
                    ),
                    values,
                )
            upserted += 1
    return {"ok": True, "synced": upserted, "date_from": date_from, "date_to": date_to}


def _goods_return_rows(repo: ReviewRepository, *, user_id: int, source_id: int) -> list[dict[str, Any]]:
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT * FROM wb_fbs_goods_returns
                WHERE user_id = ? AND source_id = ?
                ORDER BY synced_at DESC
                """
            ),
            (user_id, source_id),
        ).fetchall()
    return [repo._row_to_dict(r) for r in rows]


def find_goods_return_by_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    scan: str,
) -> dict[str, Any] | None:
    raw = kiz_restore.normalize_sticker_scan(scan)
    if not raw:
        return None
    raw_key = _scan_key(raw)
    digits = _digits_only(raw)
    for row in _goods_return_rows(repo, user_id=user_id, source_id=source_id):
        sticker_id = str(row.get("sticker_id") or "").strip()
        if sticker_id and (
            sticker_id == raw
            or sticker_id == digits
            or _scan_key(sticker_id) == raw_key
        ):
            return row
        barcode = str(row.get("barcode") or "").strip()
        shk_id = str(row.get("shk_id") or "").strip()
        if barcode and (barcode == raw or _digits_only(barcode) == digits):
            return row
        if shk_id and (shk_id == raw or _digits_only(shk_id) == digits):
            return row
    return None


def _catalog_barcodes_index(repo: ReviewRepository, *, user_id: int) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for p in repo.list_product_photos(user_id=user_id):
        for b in p.get("barcodes") or []:
            code = str(b or "").strip()
            if not code:
                continue
            index[code] = p
            index[code.casefold()] = p
            d = _digits_only(code)
            if d:
                index[d] = p
    return index


def _product_from_order(
    repo: ReviewRepository,
    *,
    user_id: int,
    order_row: dict[str, Any] | None,
) -> dict[str, Any]:
    if not order_row:
        return {}
    article = str(order_row.get("article") or "").strip()
    nm_id = str(order_row.get("nm_id") or "").strip()
    name_map = repo.get_product_name_by_article(user_id=user_id)
    photo_map = repo.get_product_photo_map(user_id=user_id)
    name = (
        name_map.get(article)
        or name_map.get(article.casefold())
        or name_map.get(nm_id)
        or name_map.get(nm_id.casefold())
        or ""
    )
    photo = photo_map.get(article) or photo_map.get(nm_id) or ""
    barcodes: list[str] = []
    try:
        parsed = json.loads(order_row.get("skus_json") or "[]")
        if isinstance(parsed, list):
            barcodes = [str(x).strip() for x in parsed if str(x or "").strip()]
    except Exception:
        pass
    catalog = _catalog_barcodes_index(repo, user_id=user_id)
    for p in repo.list_product_photos(user_id=user_id):
        if article and str(p.get("supplier_article") or "").strip() == article:
            for b in p.get("barcodes") or []:
                text = str(b or "").strip()
                if text and text not in barcodes:
                    barcodes.append(text)
            break
        if nm_id and str(p.get("wb_nmid") or "").strip() == nm_id:
            for b in p.get("barcodes") or []:
                text = str(b or "").strip()
                if text and text not in barcodes:
                    barcodes.append(text)
            break
    return {
        "product_name": name,
        "product_article": article,
        "product_photo": photo,
        "product_barcodes": barcodes,
    }


def _product_from_gtin(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtin14: str,
) -> dict[str, Any]:
    if not gtin14:
        return {}
    catalog = _catalog_barcodes_index(repo, user_id=user_id)
    p = catalog.get(gtin14) or catalog.get(gtin14.lstrip("0")) or catalog.get(_digits_only(gtin14))
    if not p:
        return {}
    pid = int(p.get("id") or 0)
    photo = f"/api/products/photo/{pid}" if pid and p.get("photo_path") else ""
    return {
        "product_name": str(p.get("name") or "").strip(),
        "product_article": str(p.get("supplier_article") or "").strip(),
        "product_photo": photo,
        "product_barcodes": list(p.get("barcodes") or []),
    }


def _load_order_row(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
) -> dict[str, Any] | None:
    row = wb.get_order_by_id(
        repo, user_id=user_id, source_id=source_id, order_id=int(order_id)
    )
    return row if row else None


def _kiz_codes_for_order(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
    api_key: str = "",
) -> list[str]:
    return kiz_restore.load_kiz_for_order(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=int(order_id),
        api_key=api_key,
    )


def _return_scan_duplicate(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    return_sticker_id: str,
) -> dict[str, Any] | None:
    if not return_sticker_id:
        return None
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM wb_fbs_return_scans
                WHERE user_id = ? AND source_id = ?
                  AND scan_type = ?
                  AND return_sticker_id = ?
                ORDER BY scanned_at DESC
                LIMIT 1
                """
            ),
            (user_id, source_id, SCAN_RETURN, return_sticker_id),
        ).fetchone()
    return repo._row_to_dict(row) if row else None


def _insert_return_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    payload: dict[str, Any],
) -> dict[str, Any]:
    ensure_wb_fbs_returns_tables(repo)
    now = datetime.now(UTC).isoformat()
    with repo._connect() as conn:
        scan_id = repo._insert_and_get_id(
            conn,
            repo._sql(
                """
                INSERT INTO wb_fbs_return_scans (
                    user_id, source_id, scanned_at, scan_type, scan_raw,
                    return_sticker_id, order_id, assembly_sticker_barcode,
                    assembly_sticker_number, kiz_code, matched_order_ids_json,
                    product_name, product_article, product_photo,
                    product_barcodes_json, gtin14, duplicate_of_id
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """
            ),
            (
                user_id,
                source_id,
                now,
                str(payload.get("scan_type") or "").strip(),
                str(payload.get("scan_raw") or "").strip(),
                str(payload.get("return_sticker_id") or "").strip(),
                payload.get("order_id"),
                str(payload.get("assembly_sticker_barcode") or "").strip(),
                str(payload.get("assembly_sticker_number") or "").strip(),
                str(payload.get("kiz_code") or "").strip(),
                json.dumps(payload.get("matched_order_ids") or [], ensure_ascii=False),
                str(payload.get("product_name") or "").strip(),
                str(payload.get("product_article") or "").strip(),
                str(payload.get("product_photo") or "").strip(),
                json.dumps(payload.get("product_barcodes") or [], ensure_ascii=False),
                str(payload.get("gtin14") or "").strip(),
                payload.get("duplicate_of_id"),
            ),
        )
        row = conn.execute(
            repo._sql("SELECT * FROM wb_fbs_return_scans WHERE id = ?"),
            (scan_id,),
        ).fetchone()
    return _scan_row_to_api(repo._row_to_dict(row) if row else {})


def _scan_row_to_api(row: dict[str, Any]) -> dict[str, Any]:
    if not row:
        return {}
    out = dict(row)
    try:
        out["matched_order_ids"] = json.loads(out.pop("matched_order_ids_json", "[]") or "[]")
    except Exception:
        out["matched_order_ids"] = []
    try:
        out["product_barcodes"] = json.loads(out.pop("product_barcodes_json", "[]") or "[]")
    except Exception:
        out["product_barcodes"] = []
    out.pop("product_barcodes_json", None)
    out.pop("matched_order_ids_json", None)
    return out


def process_return_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
) -> dict[str, Any]:
    """Classify scan, resolve order/product/KIZ, persist journal row."""
    scan_text = str(scan or "").strip()
    if not scan_text:
        return {"ok": False, "error": "empty_scan", "message": "Пустое сканирование"}

    if kiz_restore.looks_like_kiz_scan(scan_text):
        return _process_kiz_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
        )

    goods_hit = find_goods_return_by_scan(
        repo, user_id=user_id, source_id=source_id, scan=scan_text
    )
    if goods_hit:
        return _process_return_sticker_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
            goods_row=goods_hit,
        )

    sticker_hit = kiz_restore.find_orders_by_sticker_scan(
        repo, user_id=user_id, source_id=source_id, scan=scan_text
    )
    if sticker_hit.get("ambiguous"):
        ids = [
            int(r.get("order_id"))
            for r in (sticker_hit.get("matches") or [])
            if r.get("order_id") is not None
        ]
        return {
            "ok": False,
            "error": "ambiguous_sticker",
            "message": "Стикер совпадает у нескольких заказов",
            "order_ids": ids[:10],
        }
    if sticker_hit.get("row"):
        return _process_assembly_sticker_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
            order_row=sticker_hit["row"],
        )

    return {
        "ok": False,
        "error": "not_found",
        "message": "Не удалось распознать скан. Синхронизируйте возвраты WB или проверьте сканирование.",
    }


def _process_return_sticker_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
    goods_row: dict[str, Any],
) -> dict[str, Any]:
    sticker_id = str(goods_row.get("sticker_id") or "").strip() or _digits_only(scan)
    dup = _return_scan_duplicate(
        repo, user_id=user_id, source_id=source_id, return_sticker_id=sticker_id
    )
    if dup:
        return {
            "ok": False,
            "error": "duplicate",
            "message": "Этот стикер возврата уже просканирован ранее",
            "item": _scan_row_to_api(dup),
        }
    try:
        order_id = int(goods_row.get("wb_order_id") or 0)
    except (TypeError, ValueError):
        order_id = 0
    order_row = (
        _load_order_row(repo, user_id=user_id, source_id=source_id, order_id=order_id)
        if order_id > 0
        else None
    )
    product = _product_from_order(repo, user_id=user_id, order_row=order_row)
    kiz_codes = (
        _kiz_codes_for_order(
            repo,
            user_id=user_id,
            source_id=source_id,
            order_id=order_id,
            api_key=api_key,
        )
        if order_id > 0
        else []
    )
    kiz_code = kiz_codes[0] if kiz_codes else ""
    assembly_number = ""
    assembly_barcode = ""
    if order_row:
        part_a = str(order_row.get("sticker_part_a") or "").strip()
        part_b = str(order_row.get("sticker_part_b") or "").strip()
        assembly_number = kiz_restore.sticker_number(part_a, part_b)
        assembly_barcode = str(order_row.get("sticker_barcode") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_RETURN,
            "scan_raw": scan,
            "return_sticker_id": sticker_id,
            "order_id": order_id if order_id > 0 else None,
            "assembly_sticker_barcode": assembly_barcode,
            "assembly_sticker_number": assembly_number,
            "kiz_code": kiz_code,
            "matched_order_ids": [order_id] if order_id > 0 else [],
            "gtin14": kiz_restore.extract_gtin14(kiz_code) if kiz_code else "",
            **product,
        },
    )
    if not kiz_code and order_id > 0:
        item["warning"] = f"Для заказа {order_id} не найден сохранённый КИЗ"
    return {"ok": True, "item": item}


def _process_assembly_sticker_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
    order_row: dict[str, Any],
) -> dict[str, Any]:
    try:
        order_id = int(order_row.get("order_id"))
    except (TypeError, ValueError, KeyError):
        return {"ok": False, "error": "not_found", "message": "Некорректный заказ"}
    wb.persist_order_stickers_batch(
        repo,
        user_id=user_id,
        source_id=source_id,
        stickers={
            order_id: {
                "sticker_barcode": kiz_restore.normalize_sticker_scan(scan),
                "sticker_part_a": str(order_row.get("sticker_part_a") or "").strip(),
                "sticker_part_b": str(order_row.get("sticker_part_b") or "").strip(),
            }
        },
    )
    product = _product_from_order(repo, user_id=user_id, order_row=order_row)
    kiz_codes = _kiz_codes_for_order(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=order_id,
        api_key=api_key,
    )
    kiz_code = kiz_codes[0] if kiz_codes else ""
    part_a = str(order_row.get("sticker_part_a") or "").strip()
    part_b = str(order_row.get("sticker_part_b") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_ASSEMBLY,
            "scan_raw": scan,
            "order_id": order_id,
            "assembly_sticker_barcode": kiz_restore.normalize_sticker_scan(scan),
            "assembly_sticker_number": kiz_restore.sticker_number(part_a, part_b),
            "kiz_code": kiz_code,
            "matched_order_ids": [order_id],
            "gtin14": kiz_restore.extract_gtin14(kiz_code) if kiz_code else "",
            **product,
        },
    )
    return {"ok": True, "item": item}


def _process_kiz_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
) -> dict[str, Any]:
    code = kiz_restore.normalize_kiz_mark(scan)
    gtin14 = kiz_restore.extract_gtin14(code)
    db_hit = kiz_restore.find_kiz_in_local_database(
        repo, user_id=user_id, source_id=source_id, kiz_code=code
    )
    matched_ids = [int(x) for x in (db_hit.get("order_ids") or [])]
    order_id: int | None = matched_ids[0] if len(matched_ids) == 1 else None
    order_row = (
        _load_order_row(repo, user_id=user_id, source_id=source_id, order_id=order_id)
        if order_id
        else None
    )
    product = (
        _product_from_order(repo, user_id=user_id, order_row=order_row)
        if order_row
        else _product_from_gtin(repo, user_id=user_id, gtin14=gtin14)
    )
    if gtin14 and product.get("product_barcodes"):
        catalog = _catalog_barcodes_index(repo, user_id=user_id)
        if gtin14 not in catalog and _digits_only(gtin14) not in {
            _digits_only(k) for k in catalog
        }:
            product["gtin_warning"] = "GTIN не найден в каталоге товаров"
    assembly_number = ""
    assembly_barcode = ""
    if order_row:
        part_a = str(order_row.get("sticker_part_a") or "").strip()
        part_b = str(order_row.get("sticker_part_b") or "").strip()
        assembly_number = kiz_restore.sticker_number(part_a, part_b)
        assembly_barcode = str(order_row.get("sticker_barcode") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_KIZ,
            "scan_raw": scan,
            "order_id": order_id,
            "assembly_sticker_barcode": assembly_barcode,
            "assembly_sticker_number": assembly_number,
            "kiz_code": code,
            "matched_order_ids": matched_ids,
            "gtin14": gtin14,
            **product,
        },
    )
    if len(matched_ids) > 1:
        item["warning"] = (
            f"КИЗ найден у заказов: {', '.join(str(x) for x in matched_ids[:5])}"
            f"{'…' if len(matched_ids) > 5 else ''}"
        )
    elif not db_hit.get("found"):
        item["warning"] = "КИЗ не найден в локальной базе заказов"
    return {"ok": True, "item": item}


def get_return_scan_by_id(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    scan_id: int,
) -> dict[str, Any] | None:
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM wb_fbs_return_scans
                WHERE user_id = ? AND source_id = ? AND id = ?
                """
            ),
            (user_id, source_id, scan_id),
        ).fetchone()
    return _scan_row_to_api(repo._row_to_dict(row)) if row else None


def list_return_scans(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    date_from: str = "",
    date_to: str = "",
    search: str = "",
    scan_types: list[str] | None = None,
    limit: int = 500,
) -> list[dict[str, Any]]:
    ensure_wb_fbs_returns_tables(repo)
    clauses = ["user_id = ?", "source_id = ?"]
    params: list[Any] = [user_id, source_id]
    df = _parse_iso_date(date_from)
    dt = _parse_iso_date(date_to)
    if df:
        clauses.append("scanned_at >= ?")
        params.append(f"{df}T00:00:00+00:00")
    if dt:
        clauses.append("scanned_at < ?")
        end = date.fromisoformat(dt) + timedelta(days=1)
        params.append(f"{end.isoformat()}T00:00:00+00:00")
    if scan_types:
        placeholders = ",".join("?" for _ in scan_types)
        clauses.append(f"scan_type IN ({placeholders})")
        params.extend(scan_types)
    sql = (
        "SELECT * FROM wb_fbs_return_scans WHERE "
        + " AND ".join(clauses)
        + " ORDER BY scanned_at DESC LIMIT ?"
    )
    params.append(max(1, min(int(limit), 2000)))
    with repo._connect() as conn:
        rows = conn.execute(repo._sql(sql), tuple(params)).fetchall()
    items = [_scan_row_to_api(repo._row_to_dict(r)) for r in rows]
    q = str(search or "").strip().casefold()
    if not q:
        return items
    out: list[dict[str, Any]] = []
    for item in items:
        blob = " ".join(
            [
                str(item.get("order_id") or ""),
                str(item.get("return_sticker_id") or ""),
                str(item.get("assembly_sticker_barcode") or ""),
                str(item.get("assembly_sticker_number") or ""),
                str(item.get("kiz_code") or ""),
                str(item.get("scan_raw") or ""),
                str(item.get("product_name") or ""),
                str(item.get("product_article") or ""),
                " ".join(str(x) for x in (item.get("product_barcodes") or [])),
                " ".join(str(x) for x in (item.get("matched_order_ids") or [])),
            ]
        ).casefold()
        if q in blob:
            out.append(item)
    return out


def render_kiz_print_png(kiz_code: str) -> str:
    return kiz_restore.kiz_datamatrix_png_base64(kiz_code)


def export_return_scans_csv(items: list[dict[str, Any]]) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, delimiter=";")
    writer.writerow(
        [
            "Дата",
            "Тип",
            "Заказ",
            "Стикер возврата",
            "Стикер заказа",
            "КИЗ",
            "Товар",
            "Артикул",
            "ШК",
        ]
    )
    for item in items:
        writer.writerow(
            [
                str(item.get("scanned_at") or ""),
                str(item.get("scan_type") or ""),
                str(item.get("order_id") or ""),
                str(item.get("return_sticker_id") or ""),
                str(item.get("assembly_sticker_number") or item.get("assembly_sticker_barcode") or ""),
                str(item.get("kiz_code") or ""),
                str(item.get("product_name") or ""),
                str(item.get("product_article") or ""),
                ", ".join(str(x) for x in (item.get("product_barcodes") or [])),
            ]
        )
    return "\ufeff" + buf.getvalue()


def default_sync_date_range(days: int = 31) -> tuple[str, str]:
    end = date.today()
    start = end - timedelta(days=max(1, days) - 1)
    return start.isoformat(), end.isoformat()


def sync_goods_returns_default(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
) -> dict[str, Any]:
    api_key = get_wb_analytics_api_key(repo, user_id=user_id)
    if not api_key:
        return {"ok": False, "error": "no_analytics_key", "message": "Не задан WB Analytics API ключ"}
    date_from, date_to = default_sync_date_range(31)
    return sync_goods_returns(
        repo,
        user_id=user_id,
        source_id=source_id,
        api_key=api_key,
        date_from=date_from,
        date_to=date_to,
    )
