"""WB FBS «Возвраты» — return sticker journal, goods-return sync, KIZ reprint."""

from __future__ import annotations

import contextlib
import csv
import io
import json
import logging
import re
import threading
import time
import urllib.error
import urllib.request
from datetime import UTC, date, datetime, timedelta
from typing import Any
from urllib.parse import urlencode
from zoneinfo import ZoneInfo

from . import wb_fbs as wb
from . import wb_fbs_kiz_restore as kiz_restore
from .repository import ReviewRepository
from .wb_kiz_circulation import WB_ANALYTICS_API, get_wb_analytics_api_key

_log = logging.getLogger(__name__)

SCAN_RETURN = "return_sticker"
SCAN_ASSEMBLY = "assembly_sticker"
SCAN_KIZ = "kiz"
SCAN_LOOKUP = "lookup"


def ensure_wb_fbs_returns_tables(repo: ReviewRepository) -> None:
    wb.ensure_wb_fbs_tables(repo)
    with repo._connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wb_fbs_goods_returns (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                wb_order_id BIGINT NOT NULL DEFAULT 0,
                sticker_id TEXT NOT NULL DEFAULT '',
                barcode TEXT NOT NULL DEFAULT '',
                shk_id TEXT NOT NULL DEFAULT '',
                nm_id BIGINT,
                srid TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT '',
                reason TEXT NOT NULL DEFAULT '',
                ready_to_return_dt TEXT NOT NULL DEFAULT '',
                completed_dt TEXT NOT NULL DEFAULT '',
                order_dt TEXT NOT NULL DEFAULT '',
                raw_json TEXT NOT NULL DEFAULT '{}',
                synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_user_src "
                "ON wb_fbs_goods_returns(user_id, source_id, wb_order_id)"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_sticker "
                "ON wb_fbs_goods_returns(user_id, source_id, sticker_id) "
                "WHERE sticker_id <> ''"
            )
        )
        conn.execute(
            repo._sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_wb_fbs_goods_returns_srid_uniq "
                "ON wb_fbs_goods_returns(user_id, source_id, srid) "
                "WHERE srid <> ''"
            )
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS wb_fbs_return_scans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                source_id BIGINT NOT NULL,
                scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                scan_type TEXT NOT NULL DEFAULT '',
                scan_raw TEXT NOT NULL DEFAULT '',
                return_sticker_id TEXT NOT NULL DEFAULT '',
                order_id BIGINT,
                assembly_sticker_barcode TEXT NOT NULL DEFAULT '',
                assembly_sticker_number TEXT NOT NULL DEFAULT '',
                kiz_code TEXT NOT NULL DEFAULT '',
                matched_order_ids_json TEXT NOT NULL DEFAULT '[]',
                product_name TEXT NOT NULL DEFAULT '',
                product_article TEXT NOT NULL DEFAULT '',
                product_photo TEXT NOT NULL DEFAULT '',
                product_barcodes_json TEXT NOT NULL DEFAULT '[]',
                gtin14 TEXT NOT NULL DEFAULT '',
                duplicate_of_id BIGINT
            )
            """
        )
        conn.execute(
            repo._sql(
                "CREATE INDEX IF NOT EXISTS idx_wb_fbs_return_scans_user_src_time "
                "ON wb_fbs_return_scans(user_id, source_id, scanned_at DESC)"
            )
        )
        try:
            conn.execute(
                repo._sql(
                    "CREATE UNIQUE INDEX IF NOT EXISTS idx_wb_fbs_return_scans_return_dedup "
                    "ON wb_fbs_return_scans(user_id, source_id, return_sticker_id) "
                    "WHERE scan_type = 'return_sticker' AND return_sticker_id <> ''"
                )
            )
        except Exception as exc:
            msg = str(exc).lower()
            if "already exists" not in msg and "duplicate" not in msg:
                raise


GOODS_RETURN_MAX_WINDOW_DAYS = 31
GOODS_RETURN_DEFAULT_TOTAL_DAYS = 90
GOODS_RETURN_STATUS_BATCH = 500
# WB Personal/Service token: 1 request / minute for goods-return.
GOODS_RETURN_REQUEST_INTERVAL_SEC = 61
GOODS_RETURN_HYDRATE_CONFIRMED_LIMIT = 30

_goods_return_sync_lock_guard = threading.Lock()
_goods_return_sync_locks: dict[str, threading.Lock] = {}

_goods_return_job_guard = threading.Lock()
_goods_return_jobs: dict[str, dict[str, Any]] = {}


def _goods_return_job_key(*, user_id: int, source_id: int) -> str:
    return f"wb-goods-return-job:{int(user_id)}:{int(source_id)}"


def get_goods_return_sync_job(
    *,
    user_id: int,
    source_id: int,
) -> dict[str, Any] | None:
    key = _goods_return_job_key(user_id=user_id, source_id=source_id)
    with _goods_return_job_guard:
        job = _goods_return_jobs.get(key)
        return dict(job) if isinstance(job, dict) else None


def start_goods_return_sync_async(
    *,
    user_id: int,
    source_id: int,
    sync_callable,
) -> dict[str, Any]:
    """Run ``sync_callable()`` in a daemon thread; return job handle for polling."""
    key = _goods_return_job_key(user_id=user_id, source_id=source_id)
    with _goods_return_job_guard:
        existing = _goods_return_jobs.get(key)
        if isinstance(existing, dict) and str(existing.get("status") or "") == "running":
            return {
                "ok": True,
                "async": True,
                "status": "running",
                "already_running": True,
                "source_id": int(source_id),
                "started_at": existing.get("started_at"),
                "message": (
                    "Синхронизация возвратов WB уже выполняется для этого источника. "
                    "Дождитесь завершения (~2 мин для 90 дней)."
                ),
            }
        started_at = datetime.now(UTC).isoformat()
        _goods_return_jobs[key] = {
            "status": "running",
            "source_id": int(source_id),
            "started_at": started_at,
        }

    def _worker() -> None:
        try:
            result = sync_callable()
            with _goods_return_job_guard:
                _goods_return_jobs[key] = {
                    "status": "ok",
                    "source_id": int(source_id),
                    "started_at": started_at,
                    "finished_at": datetime.now(UTC).isoformat(),
                    "result": result,
                }
        except GoodsReturnSyncInProgress as exc:
            with _goods_return_job_guard:
                _goods_return_jobs[key] = {
                    "status": "error",
                    "source_id": int(source_id),
                    "started_at": started_at,
                    "finished_at": datetime.now(UTC).isoformat(),
                    "error": str(exc),
                }
        except RuntimeError as exc:
            with _goods_return_job_guard:
                _goods_return_jobs[key] = {
                    "status": "error",
                    "source_id": int(source_id),
                    "started_at": started_at,
                    "finished_at": datetime.now(UTC).isoformat(),
                    "error": str(exc),
                }
        except Exception as exc:
            _log.exception("goods-return async sync failed user=%s source=%s", user_id, source_id)
            with _goods_return_job_guard:
                _goods_return_jobs[key] = {
                    "status": "error",
                    "source_id": int(source_id),
                    "started_at": started_at,
                    "finished_at": datetime.now(UTC).isoformat(),
                    "error": str(exc) or "Синхронизация не удалась",
                }

    threading.Thread(
        target=_worker,
        name=f"wb-goods-return-sync-{user_id}-{source_id}",
        daemon=True,
    ).start()
    return {
        "ok": True,
        "async": True,
        "status": "running",
        "already_running": False,
        "source_id": int(source_id),
        "started_at": started_at,
        "message": (
            "Синхронизация возвратов WB запущена в фоне (~2 мин для 90 дней). "
            "Не закрывайте окно — статус обновится автоматически."
        ),
    }


def _goods_return_sync_lock_key(*, user_id: int, cabinet_uid: int | None) -> str:
    uid = int(cabinet_uid or 0)
    return f"wb-goods-return:{int(user_id)}:{uid}"


class GoodsReturnSyncInProgress(RuntimeError):
    """Another goods-return sync is running for this WB seller cabinet."""


@contextlib.contextmanager
def goods_return_sync_lock(*, user_id: int, cabinet_uid: int | None):
    key = _goods_return_sync_lock_key(user_id=user_id, cabinet_uid=cabinet_uid)
    with _goods_return_sync_lock_guard:
        lock = _goods_return_sync_locks.setdefault(key, threading.Lock())
    if not lock.acquire(blocking=False):
        raise GoodsReturnSyncInProgress(
            "Синхронизация возвратов WB для этого кабинета уже выполняется. "
            "Дождитесь завершения или повторите через 1–2 мин."
        )
    try:
        yield
    finally:
        lock.release()


def resolve_goods_return_api_key(
    *,
    source_api_key: str | None,
    source_analytics_api_key: str | None = None,
    fallback_analytics_key: str | None,
) -> tuple[str, str, bool]:
    """Pick WB token for goods-return report.

    goods-return lives on seller-analytics API and requires Analytics/Statistics
    scope. Marketplace-only source tokens get 403. When the global Settings key
    belongs to the same seller (JWT uid), it is used as fallback.

    Returns ``(api_key, api_key_source, trust_report)``.
    """
    ordered, trust = resolve_goods_return_api_keys(
        source_api_key=source_api_key,
        source_analytics_api_key=source_analytics_api_key,
        fallback_analytics_key=fallback_analytics_key,
    )
    key, label = ordered[0]
    return key, label, trust


def resolve_goods_return_api_keys(
    *,
    source_api_key: str | None,
    source_analytics_api_key: str | None = None,
    fallback_analytics_key: str | None,
) -> tuple[list[tuple[str, str]], bool]:
    """Ordered Analytics-capable keys: [(token, label), ...], trust_report."""
    source = str(source_api_key or "").strip()
    source_analytics = str(source_analytics_api_key or "").strip()
    fallback = str(fallback_analytics_key or "").strip()
    source_uid = wb.wb_jwt_uid(source) if source else None

    ordered: list[tuple[str, str]] = []
    seen: set[str] = set()

    def _add(key: str, label: str) -> None:
        if not key or key in seen:
            return
        if not wb.wb_token_has_goods_return_scope(key):
            return
        seen.add(key)
        ordered.append((key, label))

    if source_analytics:
        _add(source_analytics, "source_analytics")
    if source:
        _add(source, "source")
    if fallback:
        fb_uid = wb.wb_jwt_uid(fallback)
        if source_uid is None or fb_uid == source_uid:
            _add(fallback, "settings")

    if not ordered:
        raise RuntimeError(
            _goods_return_key_resolution_error(
                source, fallback, source_uid, has_source_analytics=bool(source_analytics)
            )
        )

    key, _label = ordered[0]
    trust = bool(source_uid and wb.wb_jwt_uid(key) == source_uid)
    return ordered, trust


def _goods_return_key_resolution_error(
    source_key: str,
    fallback_key: str,
    source_uid: int | None,
    *,
    has_source_analytics: bool = False,
) -> str:
    if (
        fallback_key
        and wb.wb_token_has_goods_return_scope(fallback_key)
        and source_uid
        and wb.wb_jwt_uid(fallback_key) not in (None, source_uid)
    ):
        return (
            "Analytics-ключ в Настройках (Честный знак) принадлежит другому кабинету WB. "
            "Обновите API-токен источника с категориями «Маркетплейс» и «Аналитика» "
            "или укажите Analytics-ключ того же кабинета в Настройках → ЧЗ."
        )
    if has_source_analytics:
        return (
            "API-токен источника не имеет категории «Аналитика» или «Статистика». "
            "Создайте в ЛК WB токен с категориями «Маркетплейс» и «Аналитика» "
            "и обновите ключ источника."
        )
    if source_key and not wb.wb_token_has_goods_return_scope(source_key):
        scopes = ", ".join(wb.wb_token_scope_labels(source_key)) or "не определены"
        return (
            "API-ключ источника не имеет категории «Аналитика» или «Статистика» "
            f"(сейчас: {scopes}). Создайте в ЛК WB новый токен с категорией «Аналитика» "
            "и обновите ключ источника."
        )
    return (
        "Не задан подходящий WB API-ключ для отчёта по возвратам "
        "(нужна категория «Аналитика» или «Статистика»)."
    )


def goods_return_report_trusted(api_key_source: str, *, trust_report: bool | None = None) -> bool:
    """Whether goods-return rows can be stored without local order matching."""
    if trust_report is not None:
        return bool(trust_report)
    return str(api_key_source or "").strip() == "source"


def _goods_return_row_has_identity(
    *,
    order_id: int,
    srid: str,
    sticker_id: str = "",
    nm_id: int | None = None,
) -> bool:
    if order_id > 0:
        return True
    if str(srid or "").strip():
        return True
    if str(sticker_id or "").strip():
        return True
    if nm_id and int(nm_id) > 0:
        return True
    return False


def _confirm_order_ids_on_marketplace(
    marketplace_api_key: str,
    order_ids: list[int],
) -> set[int]:
    """Order IDs that exist on this seller cabinet (POST /api/v3/orders/status)."""
    ids = sorted({int(x) for x in order_ids if int(x) > 0})
    if not ids or not str(marketplace_api_key or "").strip():
        return set()
    client = wb.WbFbsClient(str(marketplace_api_key).strip())
    confirmed: set[int] = set()
    for i in range(0, len(ids), GOODS_RETURN_STATUS_BATCH):
        chunk = ids[i : i + GOODS_RETURN_STATUS_BATCH]
        try:
            statuses = client.get_statuses(chunk)
        except Exception as exc:
            _log.warning("goods-return order status batch failed: %s", exc)
            continue
        for st in statuses or []:
            if not isinstance(st, dict):
                continue
            try:
                oid = int(st.get("id") or 0)
            except (TypeError, ValueError):
                continue
            if oid > 0:
                confirmed.add(oid)
    return confirmed


def _hydrate_confirmed_return_orders(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_ids: set[int],
    known_order_ids: set[int],
    api_key: str,
    limit: int = GOODS_RETURN_HYDRATE_CONFIRMED_LIMIT,
) -> int:
    """Pull minimal order rows for confirmed return orderIds missing locally."""
    missing = sorted({int(x) for x in order_ids if int(x) > 0 and int(x) not in known_order_ids})
    if not missing or not str(api_key or "").strip():
        return 0
    client = wb.WbFbsClient(str(api_key).strip())
    hydrated = 0
    for oid in missing[: max(0, int(limit))]:
        try:
            payload, is_archive, status = wb._fetch_order_payload_from_wb(
                client, oid, max_archive_pages=12
            )
        except Exception as exc:
            _log.warning("returns hydrate confirmed order %s failed: %s", oid, exc)
            continue
        if not payload:
            continue
        ss = str((status or {}).get("supplierStatus") or payload.get("supplierStatus") or "")
        ws = str((status or {}).get("wbStatus") or payload.get("wbStatus") or "")
        wb.upsert_order(
            repo,
            user_id=user_id,
            source_id=source_id,
            order=payload,
            supplier_status=ss,
            wb_status=ws,
            is_archive=is_archive,
        )
        hydrated += 1
    return hydrated


GOODS_RETURN_CHUNK_DAYS = 30
MSK = ZoneInfo("Europe/Moscow")


def _digits_only(value: object) -> str:
    return re.sub(r"\D+", "", str(value or ""))


def _scan_key(value: object) -> str:
    return kiz_restore.normalize_sticker_scan(value).casefold()


def _parse_iso_date(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return text[:10] if len(text) >= 10 else text


def _parse_sync_date(value: str) -> date:
    return date.fromisoformat(_parse_iso_date(value))


def iter_goods_return_windows(
    date_from: str,
    date_to: str,
    *,
    chunk_days: int = GOODS_RETURN_CHUNK_DAYS,
) -> list[tuple[str, str]]:
    """Split a range into non-overlapping WB windows (each ≤ 31 days)."""
    start = _parse_sync_date(date_from)
    end = _parse_sync_date(date_to)
    if end < start:
        start, end = end, start
    max_chunk = min(max(1, int(chunk_days)), GOODS_RETURN_MAX_WINDOW_DAYS)
    windows: list[tuple[str, str]] = []
    cur = end
    while cur >= start:
        win_start = max(start, cur - timedelta(days=max_chunk - 1))
        windows.append((win_start.isoformat(), cur.isoformat()))
        cur = win_start - timedelta(days=1)
    windows.reverse()
    return windows


def _http_header_get(headers: Any, *names: str) -> str:
    if headers is None:
        return ""
    for name in names:
        try:
            val = headers.get(name)
        except Exception:
            val = None
        if val is None and hasattr(headers, "get"):
            try:
                val = headers.get(name.lower())
            except Exception:
                val = None
        if val is not None and str(val).strip():
            return str(val).strip()
    return ""


def _format_wb_retry_hint(retry_after: str) -> str:
    retry = str(retry_after or "").strip()
    if not retry:
        return ""
    if retry.isdigit():
        secs = int(retry)
        if secs > 1_700_000_000:
            dt = datetime.fromtimestamp(secs, tz=UTC).astimezone(MSK)
            return f" Повторите после {dt.strftime('%H:%M')} МСК ({dt.strftime('%d.%m.%Y')})."
        if secs >= 3600:
            hours = secs // 3600
            mins = (secs % 3600 + 59) // 60
            if mins and hours < 24:
                return f" Повторите примерно через {hours} ч {mins} мин."
            return f" Повторите примерно через {hours} ч."
        if secs >= 60:
            return f" Повторите примерно через {(secs + 59) // 60} мин."
        if secs > 0:
            return f" Повторите примерно через {secs} сек."
        return ""
    try:
        dt = datetime.fromisoformat(retry.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=UTC)
        msk = dt.astimezone(MSK)
        return f" Повторите после {msk.strftime('%H:%M')} МСК ({msk.strftime('%d.%m.%Y')})."
    except Exception:
        return f" Повторите после: {retry}."


def format_wb_goods_return_http_error(
    *,
    code: int,
    body: str = "",
    retry_after: str = "",
    reason: str = "",
) -> RuntimeError:
    """Human-readable WB Analytics goods-return errors (esp. 429 rate limit)."""
    if int(code) == 429:
        msg = (
            "Лимит WB на отчёт по возвратам: слишком много запросов к Analytics API. "
            "Синхронизация за 90 дней делает 3 запроса с паузой ~1 мин между ними. "
            "Не запускайте «Синхр. WB» для нескольких источников подряд без паузы."
        )
        hint = _format_wb_retry_hint(retry_after)
        if hint:
            msg += hint
        return RuntimeError(msg)
    if int(code) == 403 and (
        "scope is not allowed" in (body or "").lower()
        or "scope is not allowed" in (reason or "").lower()
    ):
        return RuntimeError(
            "WB goods-return: у API-ключа нет категории «Аналитика» или «Статистика». "
            "Создайте токен в ЛК WB с категорией «Аналитика» и обновите ключ источника."
        )
    detail = (body or reason or "").strip()
    if detail:
        return RuntimeError(f"WB goods-return HTTP {code}: {detail[:500]}")
    return RuntimeError(f"WB goods-return HTTP {code}")


def _goods_return_values_from_row(
    row: dict[str, Any],
    *,
    user_id: int,
    source_id: int,
    synced_at: str,
) -> tuple[tuple[Any, ...], str, str, int, str] | None:
    try:
        order_id = int(row.get("orderId") or 0)
    except (TypeError, ValueError):
        order_id = 0
    sticker_id = str(row.get("stickerId") or "").strip()
    srid = str(row.get("srid") or "").strip()
    if not srid and not sticker_id and order_id <= 0:
        return None
    barcode = str(row.get("barcode") or "").strip()
    shk_id = str(row.get("shkId") or "").strip()
    try:
        nm_id = int(row.get("nmId") or 0) or None
    except (TypeError, ValueError):
        nm_id = None
    raw_json = json.dumps(row, ensure_ascii=False)
    status = str(row.get("status") or "").strip()
    reason = str(row.get("reason") or "").strip()
    ready_dt = str(row.get("readyToReturnDt") or "").strip()
    completed_dt = str(row.get("completedDt") or "").strip()
    order_dt = str(row.get("orderDt") or "").strip()
    values = (
        user_id,
        source_id,
        order_id,
        sticker_id,
        barcode,
        shk_id,
        nm_id,
        srid,
        status,
        reason,
        ready_dt,
        completed_dt,
        order_dt,
        raw_json,
        synced_at,
    )
    return values, raw_json, srid, order_id, sticker_id


def _upsert_goods_return_row(
    conn,
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    values: tuple[Any, ...],
    raw_json: str,
    srid: str,
    order_id: int,
    sticker_id: str,
) -> str:
    """Insert or update one goods-return row. Returns inserted/updated/unchanged."""
    if srid:
        existing = conn.execute(
            repo._sql(
                """
                SELECT raw_json FROM wb_fbs_goods_returns
                WHERE user_id = ? AND source_id = ? AND srid = ?
                LIMIT 1
                """
            ),
            (user_id, source_id, srid),
        ).fetchone()
        if existing:
            prev = repo._row_to_dict(existing)
            if str(prev.get("raw_json") or "") == raw_json:
                return "unchanged"
            conn.execute(
                repo._sql(
                    """
                    UPDATE wb_fbs_goods_returns SET
                        wb_order_id = ?, sticker_id = ?, barcode = ?, shk_id = ?,
                        nm_id = ?, status = ?, reason = ?,
                        ready_to_return_dt = ?, completed_dt = ?, order_dt = ?,
                        raw_json = ?, synced_at = ?
                    WHERE user_id = ? AND source_id = ? AND srid = ?
                    """
                ),
                (
                    values[2],
                    values[3],
                    values[4],
                    values[5],
                    values[6],
                    values[8],
                    values[9],
                    values[10],
                    values[11],
                    values[12],
                    raw_json,
                    values[14],
                    user_id,
                    source_id,
                    srid,
                ),
            )
            return "updated"
        try:
            conn.execute(
                repo._sql(
                    """
                    INSERT INTO wb_fbs_goods_returns (
                        user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                        nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                        order_dt, raw_json, synced_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """
                ),
                values,
            )
            return "inserted"
        except Exception as exc:
            msg = str(exc).lower()
            if "duplicate" not in msg and "unique" not in msg and "already exists" not in msg:
                raise
            existing = conn.execute(
                repo._sql(
                    """
                    SELECT raw_json FROM wb_fbs_goods_returns
                    WHERE user_id = ? AND source_id = ? AND srid = ?
                    LIMIT 1
                    """
                ),
                (user_id, source_id, srid),
            ).fetchone()
            if not existing:
                raise
            prev = repo._row_to_dict(existing)
            if str(prev.get("raw_json") or "") == raw_json:
                return "unchanged"
            conn.execute(
                repo._sql(
                    """
                    UPDATE wb_fbs_goods_returns SET
                        wb_order_id = ?, sticker_id = ?, barcode = ?, shk_id = ?,
                        nm_id = ?, status = ?, reason = ?,
                        ready_to_return_dt = ?, completed_dt = ?, order_dt = ?,
                        raw_json = ?, synced_at = ?
                    WHERE user_id = ? AND source_id = ? AND srid = ?
                    """
                ),
                (
                    values[2],
                    values[3],
                    values[4],
                    values[5],
                    values[6],
                    values[8],
                    values[9],
                    values[10],
                    values[11],
                    values[12],
                    raw_json,
                    values[14],
                    user_id,
                    source_id,
                    srid,
                ),
            )
            return "updated"

    if order_id > 0 and sticker_id:
        existing = conn.execute(
            repo._sql(
                """
                SELECT raw_json FROM wb_fbs_goods_returns
                WHERE user_id = ? AND source_id = ? AND wb_order_id = ?
                  AND sticker_id = ? AND srid = ''
                LIMIT 1
                """
            ),
            (user_id, source_id, order_id, sticker_id),
        ).fetchone()
        if existing:
            prev = repo._row_to_dict(existing)
            if str(prev.get("raw_json") or "") == raw_json:
                return "unchanged"
        cur = conn.execute(
            repo._sql(
                """
                UPDATE wb_fbs_goods_returns SET
                    barcode = ?, shk_id = ?, nm_id = ?, status = ?, reason = ?,
                    ready_to_return_dt = ?, completed_dt = ?, order_dt = ?,
                    raw_json = ?, synced_at = ?
                WHERE user_id = ? AND source_id = ? AND wb_order_id = ?
                  AND sticker_id = ? AND srid = ''
                """
            ),
            (
                values[4],
                values[5],
                values[6],
                values[8],
                values[9],
                values[10],
                values[11],
                values[12],
                raw_json,
                values[14],
                user_id,
                source_id,
                order_id,
                sticker_id,
            ),
        )
        if getattr(cur, "rowcount", 0) == 0:
            conn.execute(
                repo._sql(
                    """
                    INSERT INTO wb_fbs_goods_returns (
                        user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                        nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                        order_dt, raw_json, synced_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """
                ),
                values,
            )
            return "inserted"
        return "updated" if existing else "inserted"

    conn.execute(
        repo._sql(
            """
            INSERT INTO wb_fbs_goods_returns (
                user_id, source_id, wb_order_id, sticker_id, barcode, shk_id,
                nm_id, srid, status, reason, ready_to_return_dt, completed_dt,
                order_dt, raw_json, synced_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """
        ),
        values,
    )
    return "inserted"


def fetch_goods_return_report(
    *,
    api_key: str,
    date_from: str,
    date_to: str,
    timeout: int = 60,
) -> list[dict[str, Any]]:
    """WB Analytics: GET /api/v1/analytics/goods-return (max 31 days)."""
    params = urlencode(
        {"dateFrom": _parse_iso_date(date_from), "dateTo": _parse_iso_date(date_to)}
    )
    url = f"{WB_ANALYTICS_API}/api/v1/analytics/goods-return?{params}"
    req = urllib.request.Request(
        url,
        method="GET",
        headers={
            "Authorization": str(api_key or "").strip(),
            "Accept": "application/json",
            "User-Agent": "FeedPilot-WBFBS-Returns/1.0",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = resp.read()
    except urllib.error.HTTPError as exc:
        err = ""
        try:
            err = exc.read().decode("utf-8", errors="replace")[:500]
        except Exception:
            pass
        retry_after = _http_header_get(
            getattr(exc, "headers", None),
            "X-RateLimit-Retry",
            "x-ratelimit-retry",
            "Retry-After",
            "retry-after",
        )
        raise format_wb_goods_return_http_error(
            code=int(exc.code),
            body=err,
            retry_after=retry_after,
            reason=str(exc.reason or ""),
        ) from exc
    if not payload:
        return []
    parsed = json.loads(payload.decode("utf-8"))
    if isinstance(parsed, dict):
        report = parsed.get("report")
        if isinstance(report, list):
            return [x for x in report if isinstance(x, dict)]
    if isinstance(parsed, list):
        return [x for x in parsed if isinstance(x, dict)]
    return []


def _fetch_goods_return_resilient(
    candidates: list[tuple[str, str]],
    *,
    date_from: str,
    date_to: str,
) -> tuple[list[dict[str, Any]], str, str]:
    """Try each Analytics-capable key; skip 403 scope errors."""
    last_exc: RuntimeError | None = None
    for key, label in candidates:
        try:
            rows = fetch_goods_return_report(
                api_key=key, date_from=date_from, date_to=date_to
            )
            return rows, key, label
        except RuntimeError as exc:
            if wb.is_goods_return_scope_error(exc):
                last_exc = exc
                continue
            raise
    if last_exc is not None:
        raise last_exc
    return [], "", ""


def _load_source_goods_return_matchers(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
) -> dict[str, set[int] | set[str]]:
    """Order/nm/barcodes known for one FBS source (from synced wb_fbs_orders)."""
    wb.ensure_wb_fbs_tables(repo)
    order_ids: set[int] = set()
    nm_ids: set[int] = set()
    barcodes: set[str] = set()
    with repo._connect() as conn:
        rows = conn.execute(
            repo._sql(
                """
                SELECT DISTINCT order_id, nm_id, skus_json
                FROM wb_fbs_orders
                WHERE user_id = ? AND source_id = ?
                """
            ),
            (user_id, source_id),
        ).fetchall()
    for row in rows:
        d = repo._row_to_dict(row)
        try:
            oid = int(d.get("order_id") or 0)
        except (TypeError, ValueError):
            oid = 0
        if oid > 0:
            order_ids.add(oid)
        try:
            nm = int(d.get("nm_id") or 0)
        except (TypeError, ValueError):
            nm = 0
        if nm > 0:
            nm_ids.add(nm)
        try:
            parsed = json.loads(str(d.get("skus_json") or "[]") or "[]")
        except json.JSONDecodeError:
            parsed = []
        if isinstance(parsed, list):
            for sku in parsed:
                code = str(sku or "").strip()
                if code:
                    barcodes.add(code)
    return {"order_ids": order_ids, "nm_ids": nm_ids, "barcodes": barcodes}


def _goods_return_row_matches_source(
    *,
    order_id: int,
    srid: str,
    nm_id: int | None,
    barcode: str = "",
    sticker_id: str = "",
    matchers: dict[str, set[int] | set[str]],
    srid_to_order: dict[str, int],
    confirmed_order_ids: set[int] | None = None,
    trust_report: bool = False,
) -> bool:
    """True when a goods-return row belongs to the selected FBS source."""
    if trust_report:
        return _goods_return_row_has_identity(
            order_id=order_id,
            srid=srid,
            sticker_id=sticker_id,
            nm_id=nm_id,
        )

    if order_id > 0:
        if order_id in matchers["order_ids"]:
            return True
        if confirmed_order_ids and order_id in confirmed_order_ids:
            return True
        return False

    srid_key = str(srid or "").strip()
    if srid_key:
        mapped = int(srid_to_order.get(srid_key) or 0)
        if mapped > 0:
            if mapped in matchers["order_ids"]:
                return True
            if confirmed_order_ids and mapped in confirmed_order_ids:
                return True
            return False
    bc = str(barcode or "").strip()
    if bc and bc in matchers.get("barcodes", set()):
        return True
    if nm_id and int(nm_id) > 0:
        return int(nm_id) in matchers["nm_ids"]
    return False


def _goods_return_api_row_matches_source(
    row: dict[str, Any],
    *,
    matchers: dict[str, set[int] | set[str]],
    srid_to_order: dict[str, int],
    confirmed_order_ids: set[int] | None = None,
    trust_report: bool = False,
) -> bool:
    try:
        order_id = int(row.get("orderId") or 0)
    except (TypeError, ValueError):
        order_id = 0
    srid = str(row.get("srid") or "").strip()
    try:
        nm_id = int(row.get("nmId") or 0) or None
    except (TypeError, ValueError):
        nm_id = None
    barcode = str(row.get("barcode") or "").strip()
    sticker_id = str(row.get("stickerId") or "").strip()
    return _goods_return_row_matches_source(
        order_id=order_id,
        srid=srid,
        nm_id=nm_id,
        barcode=barcode,
        sticker_id=sticker_id,
        matchers=matchers,
        srid_to_order=srid_to_order,
        confirmed_order_ids=confirmed_order_ids,
        trust_report=trust_report,
    )


def _stored_goods_return_matches_source(
    row: dict[str, Any],
    *,
    matchers: dict[str, set[int] | set[str]],
    srid_to_order: dict[str, int],
    confirmed_order_ids: set[int] | None = None,
    trust_report: bool = False,
    fetched_srids: set[str] | None = None,
    fetched_stickers: set[str] | None = None,
    fetched_order_ids: set[int] | None = None,
) -> bool:
    if trust_report and fetched_srids is not None:
        srid = str(row.get("srid") or "").strip()
        sticker = str(row.get("sticker_id") or "").strip()
        try:
            order_id = int(row.get("wb_order_id") or 0)
        except (TypeError, ValueError):
            order_id = 0
        if srid and srid in fetched_srids:
            return True
        if sticker and sticker in (fetched_stickers or set()):
            return True
        if order_id > 0 and order_id in (fetched_order_ids or set()):
            return True
        return False

    try:
        order_id = int(row.get("wb_order_id") or 0)
    except (TypeError, ValueError):
        order_id = 0
    srid = str(row.get("srid") or "").strip()
    try:
        nm_raw = row.get("nm_id")
        nm_id = int(nm_raw) if nm_raw not in (None, "") else None
    except (TypeError, ValueError):
        nm_id = None
    barcode = str(row.get("barcode") or "").strip()
    sticker_id = str(row.get("sticker_id") or "").strip()
    return _goods_return_row_matches_source(
        order_id=order_id,
        srid=srid,
        nm_id=nm_id,
        barcode=barcode,
        sticker_id=sticker_id,
        matchers=matchers,
        srid_to_order=srid_to_order,
        confirmed_order_ids=confirmed_order_ids,
        trust_report=trust_report,
    )


def _purge_foreign_goods_returns_in_range(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    date_from: str,
    date_to: str,
    matchers: dict[str, set[int]],
    srid_to_order: dict[str, int],
    confirmed_order_ids: set[int] | None = None,
    trust_report: bool = False,
    fetched_srids: set[str] | None = None,
    fetched_stickers: set[str] | None = None,
    fetched_order_ids: set[int] | None = None,
) -> int:
    """Remove cached rows stored under source_id that do not belong to it."""
    rows = list_goods_returns(
        repo,
        user_id=user_id,
        source_id=source_id,
        date_from=date_from,
        date_to=date_to,
    )
    pending_srids = sorted(
        {
            str(row.get("srid") or "").strip()
            for row in rows
            if str(row.get("srid") or "").strip()
            and str(row.get("srid") or "").strip() not in srid_to_order
        }
    )
    if pending_srids:
        srid_to_order.update(
            wb.order_ids_by_srids(
                repo,
                user_id=user_id,
                source_id=source_id,
                srids=pending_srids,
            )
        )
    stale_ids: list[int] = []
    for row in rows:
        if _stored_goods_return_matches_source(
            row,
            matchers=matchers,
            srid_to_order=srid_to_order,
            confirmed_order_ids=confirmed_order_ids,
            trust_report=trust_report,
            fetched_srids=fetched_srids,
            fetched_stickers=fetched_stickers,
            fetched_order_ids=fetched_order_ids,
        ):
            continue
        try:
            row_id = int(row.get("id") or 0)
        except (TypeError, ValueError):
            row_id = 0
        if row_id > 0:
            stale_ids.append(row_id)
    if not stale_ids:
        return 0
    with repo._connect() as conn:
        for row_id in stale_ids:
            conn.execute(
                repo._sql(
                    """
                    DELETE FROM wb_fbs_goods_returns
                    WHERE user_id = ? AND source_id = ? AND id = ?
                    """
                ),
                (user_id, source_id, row_id),
            )
    return len(stale_ids)


def sync_goods_returns(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    date_from: str,
    date_to: str,
    marketplace_api_key: str | None = None,
    api_key_source: str = "",
    trust_report: bool | None = None,
    api_key_candidates: list[tuple[str, str]] | None = None,
) -> dict[str, Any]:
    """Sync WB goods-return report for one FBS source.

    Rows are stored when they belong to this ``source_id``. With
    ``trust_report=True`` (same WB seller cabinet), all report rows are kept.
    """
    ensure_wb_fbs_returns_tables(repo)
    date_from, date_to, range_clamped = clamp_goods_return_sync_range(date_from, date_to)
    if trust_report is None:
        trust_report = goods_return_report_trusted(api_key_source)
    candidates = list(api_key_candidates or [])
    if not candidates and api_key:
        candidates = [(str(api_key).strip(), str(api_key_source or "source").strip() or "source")]
    matchers = _load_source_goods_return_matchers(
        repo, user_id=user_id, source_id=source_id
    )
    windows = iter_goods_return_windows(date_from, date_to)
    totals = {
        "fetched": 0,
        "inserted": 0,
        "updated": 0,
        "unchanged": 0,
        "skipped_foreign": 0,
        "purged_foreign": 0,
    }
    window_stats: list[dict[str, Any]] = []
    srid_to_order: dict[str, int] = {}
    confirmed_order_ids: set[int] = set()
    fetched_srids: set[str] = set()
    fetched_stickers: set[str] = set()
    fetched_order_ids: set[int] = set()
    mp_key = str(marketplace_api_key or "").strip()
    cabinet_uid = wb.wb_jwt_uid(mp_key) if mp_key else None
    report_key: str | None = None
    report_label = str(api_key_source or "").strip()
    with goods_return_sync_lock(user_id=user_id, cabinet_uid=cabinet_uid):
        for win_index, (win_from, win_to) in enumerate(windows):
            if win_index > 0:
                if report_key:
                    time.sleep(GOODS_RETURN_REQUEST_INTERVAL_SEC)
                else:
                    raise RuntimeError(
                        "Не удалось определить API-ключ для отчёта WB по возвратам"
                    )
            if report_key:
                rows = fetch_goods_return_report(
                    api_key=report_key, date_from=win_from, date_to=win_to
                )
            else:
                rows, report_key, report_label = _fetch_goods_return_resilient(
                    candidates,
                    date_from=win_from,
                    date_to=win_to,
                )
                if not report_key:
                    raise RuntimeError(
                        "Не удалось загрузить отчёт WB: нет ключа с категорией «Аналитика»"
                    )
            if win_index == 0 and len(windows) > 1:
                totals["rate_limit_windows"] = len(windows)
            for row in rows:
                srid = str(row.get("srid") or "").strip()
                if srid:
                    fetched_srids.add(srid)
                sticker = str(row.get("stickerId") or "").strip()
                if sticker:
                    fetched_stickers.add(sticker)
                try:
                    oid = int(row.get("orderId") or 0)
                except (TypeError, ValueError):
                    oid = 0
                if oid > 0:
                    fetched_order_ids.add(oid)
            window_order_ids = sorted(
                {
                    int(row.get("orderId") or 0)
                    for row in rows
                    if int(row.get("orderId") or 0) > 0
                }
            )
            if window_order_ids and mp_key:
                confirmed_order_ids.update(
                    _confirm_order_ids_on_marketplace(mp_key, window_order_ids)
                )
                try:
                    _hydrate_confirmed_return_orders(
                        repo,
                        user_id=user_id,
                        source_id=source_id,
                        order_ids=confirmed_order_ids,
                        known_order_ids=set(matchers.get("order_ids") or set()),
                        api_key=mp_key,
                    )
                    matchers = _load_source_goods_return_matchers(
                        repo, user_id=user_id, source_id=source_id
                    )
                except Exception as exc:
                    _log.warning("returns hydrate confirmed orders failed: %s", exc)
            pending_srids = sorted(
                {
                    str(row.get("srid") or "").strip()
                    for row in rows
                    if str(row.get("srid") or "").strip()
                    and str(row.get("srid") or "").strip() not in srid_to_order
                }
            )
            if pending_srids and mp_key:
                try:
                    wb.hydrate_orders_for_kiz_srids(
                        repo,
                        user_id=user_id,
                        source_id=source_id,
                        srids=pending_srids,
                        api_key=mp_key,
                        archive_pages=30,
                        lookback_days=GOODS_RETURN_DEFAULT_TOTAL_DAYS,
                    )
                    matchers = _load_source_goods_return_matchers(
                        repo, user_id=user_id, source_id=source_id
                    )
                except Exception as exc:
                    _log.warning("returns hydrate before sync failed: %s", exc)
            if pending_srids:
                srid_to_order.update(
                    wb.order_ids_by_srids(
                        repo,
                        user_id=user_id,
                        source_id=source_id,
                        srids=pending_srids,
                    )
                )
            now = datetime.now(UTC).isoformat()
            stats = {
                "fetched": len(rows),
                "inserted": 0,
                "updated": 0,
                "unchanged": 0,
                "skipped_foreign": 0,
            }
            with repo._connect() as conn:
                for row in rows:
                    if not _goods_return_api_row_matches_source(
                        row,
                        matchers=matchers,
                        srid_to_order=srid_to_order,
                        confirmed_order_ids=confirmed_order_ids,
                        trust_report=trust_report,
                    ):
                        stats["skipped_foreign"] += 1
                        continue
                    parsed = _goods_return_values_from_row(
                        row,
                        user_id=user_id,
                        source_id=source_id,
                        synced_at=now,
                    )
                    if not parsed:
                        continue
                    values, raw_json, srid, order_id, sticker_id = parsed
                    outcome = _upsert_goods_return_row(
                        conn,
                        repo,
                        user_id=user_id,
                        source_id=source_id,
                        values=values,
                        raw_json=raw_json,
                        srid=srid,
                        order_id=order_id,
                        sticker_id=sticker_id,
                    )
                    stats[outcome] += 1
            for key in ("fetched", "inserted", "updated", "unchanged", "skipped_foreign"):
                totals[key] += stats[key]
            window_stats.append(
                {
                    "date_from": win_from,
                    "date_to": win_to,
                    **stats,
                }
            )
        overall_from = windows[0][0] if windows else _parse_iso_date(date_from)
        overall_to = windows[-1][1] if windows else _parse_iso_date(date_to)
        totals["purged_foreign"] = _purge_foreign_goods_returns_in_range(
            repo,
            user_id=user_id,
            source_id=source_id,
            date_from=overall_from,
            date_to=overall_to,
            matchers=matchers,
            srid_to_order=srid_to_order,
            confirmed_order_ids=confirmed_order_ids,
            trust_report=trust_report,
            fetched_srids=fetched_srids if trust_report else None,
            fetched_stickers=fetched_stickers if trust_report else None,
            fetched_order_ids=fetched_order_ids if trust_report else None,
        )
    synced = totals["inserted"] + totals["updated"]
    warning = ""
    if range_clamped:
        warning = (
            f"Период синхронизации ограничен {GOODS_RETURN_DEFAULT_TOTAL_DAYS} днями "
            f"(WB хранит возвраты ~{GOODS_RETURN_DEFAULT_TOTAL_DAYS} дней)."
        )
    has_local_orders = bool(matchers.get("order_ids") or matchers.get("nm_ids"))
    if synced == 0 and totals["fetched"] > 0:
        extra = ""
        if totals["skipped_foreign"] > 0 and str(report_label or api_key_source or "").strip() == "settings":
            extra = (
                "Отчёт загружен глобальным ключом из Настроек, а не ключом источника. "
                "При нескольких кабинетах WB у каждого источника должен быть свой API-ключ."
            )
        elif not has_local_orders and not confirmed_order_ids and not trust_report:
            extra = (
                "Для этого источника нет заказов в базе FeedPilot — "
                "сначала синхронизируйте ВБ ФБС, затем повторите «Синхр. WB»"
            )
        elif totals["skipped_foreign"] > 0 and not trust_report:
            extra = (
                "Все строки отчёта WB не сопоставились с заказами этого источника. "
                "Проверьте, что выбран нужный источник и заказы синхронизированы "
                "(включая архив)."
            )
        elif totals["skipped_foreign"] > 0 and trust_report:
            extra = (
                f"Пропущено {totals['skipped_foreign']} строк без идентификатора "
                "(нет srid, stickerId, orderId, nmId)."
            )
        if extra:
            warning = f"{warning} {extra}".strip() if warning else extra
    return {
        "ok": True,
        "synced": synced,
        "inserted": totals["inserted"],
        "updated": totals["updated"],
        "unchanged": totals["unchanged"],
        "fetched": totals["fetched"],
        "skipped_foreign": totals["skipped_foreign"],
        "purged_foreign": totals["purged_foreign"],
        "warning": warning,
        "api_key_source": report_label or str(api_key_source or "").strip() or None,
        "report_trusted": trust_report,
        "range_clamped": range_clamped,
        "rate_limit_windows": totals.get("rate_limit_windows"),
        "windows": window_stats,
        "date_from": overall_from,
        "date_to": overall_to,
        "goods_cached_total": len(
            list_goods_returns(
                repo,
                user_id=user_id,
                source_id=source_id,
                date_from=overall_from,
                date_to=overall_to,
            )
        ),
    }


def _goods_return_rows(repo: ReviewRepository, *, user_id: int, source_id: int) -> list[dict[str, Any]]:
    return list_goods_returns(repo, user_id=user_id, source_id=source_id)


def _goods_return_raw_fields(row: dict[str, Any]) -> dict[str, Any]:
    try:
        raw = json.loads(str(row.get("raw_json") or "{}") or "{}")
    except Exception:
        raw = {}
    if not isinstance(raw, dict):
        raw = {}
    return raw


def list_goods_returns(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    date_from: str = "",
    date_to: str = "",
    search: str = "",
) -> list[dict[str, Any]]:
    """Rows from ``wb_fbs_goods_returns`` (WB goods-return sync cache)."""
    ensure_wb_fbs_returns_tables(repo)
    clauses = ["user_id = ?", "source_id = ?"]
    params: list[Any] = [user_id, source_id]
    df = _parse_iso_date(date_from)
    dt = _parse_iso_date(date_to)
    if df:
        clauses.append("COALESCE(NULLIF(order_dt, ''), ready_to_return_dt, completed_dt) >= ?")
        params.append(df)
    if dt:
        clauses.append("COALESCE(NULLIF(order_dt, ''), ready_to_return_dt, completed_dt) <= ?")
        params.append(dt)
    q = str(search or "").strip()
    if q:
        pattern = f"%{q}%"
        clauses.append(
            """(
                CAST(wb_order_id AS TEXT) ILIKE ?
                OR sticker_id ILIKE ?
                OR barcode ILIKE ?
                OR shk_id ILIKE ?
                OR srid ILIKE ?
                OR status ILIKE ?
                OR reason ILIKE ?
            )"""
        )
        params.extend([pattern] * 7)
    sql = (
        "SELECT * FROM wb_fbs_goods_returns WHERE "
        + " AND ".join(clauses)
        + " ORDER BY COALESCE(NULLIF(order_dt, ''), ready_to_return_dt, completed_dt) DESC, synced_at DESC"
    )
    with repo._connect() as conn:
        rows = conn.execute(repo._sql(sql), tuple(params)).fetchall()
    return [repo._row_to_dict(r) for r in rows]


def find_goods_return_by_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    scan: str,
) -> dict[str, Any] | None:
    raw = kiz_restore.normalize_sticker_scan(scan)
    if not raw:
        return None
    raw_key = _scan_key(raw)
    digits = _digits_only(raw)
    for row in _goods_return_rows(repo, user_id=user_id, source_id=source_id):
        srid = str(row.get("srid") or "").strip()
        if srid and (_scan_key(srid) == raw_key or srid.casefold() == raw.casefold()):
            return row
        sticker_id = str(row.get("sticker_id") or "").strip()
        if sticker_id and (
            sticker_id == raw
            or sticker_id == digits
            or _scan_key(sticker_id) == raw_key
        ):
            return row
        barcode = str(row.get("barcode") or "").strip()
        shk_id = str(row.get("shk_id") or "").strip()
        if barcode and (barcode == raw or _digits_only(barcode) == digits):
            return row
        if shk_id and (shk_id == raw or _digits_only(shk_id) == digits):
            return row
    return None


def _catalog_barcodes_index(repo: ReviewRepository, *, user_id: int) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for p in repo.list_product_photos(user_id=user_id):
        for b in p.get("barcodes") or []:
            code = str(b or "").strip()
            if not code:
                continue
            index[code] = p
            index[code.casefold()] = p
            d = _digits_only(code)
            if d:
                index[d] = p
    return index


def _catalog_product_for_order(
    repo: ReviewRepository,
    *,
    user_id: int,
    order_row: dict[str, Any] | None,
) -> dict[str, Any] | None:
    if not order_row:
        return None
    article = str(order_row.get("article") or "").strip()
    nm_id = str(order_row.get("nm_id") or "").strip()
    for p in repo.list_product_photos(user_id=user_id):
        if article and str(p.get("supplier_article") or "").strip() == article:
            return p
        if nm_id and str(p.get("wb_nmid") or "").strip() == nm_id:
            return p
    return None


def _catalog_fields_from_product(product: dict[str, Any] | None) -> dict[str, Any]:
    if not product:
        return {
            "catalog_barcodes": [],
            "barcode_label_name": "",
        }
    barcodes = [
        str(b or "").strip()
        for b in (product.get("barcodes") or [])
        if str(b or "").strip()
    ]
    return {
        "catalog_barcodes": barcodes,
        "barcode_label_name": str(product.get("barcode_label_name") or "").strip(),
    }


def _product_from_order(
    repo: ReviewRepository,
    *,
    user_id: int,
    order_row: dict[str, Any] | None,
) -> dict[str, Any]:
    if not order_row:
        return {}
    article = str(order_row.get("article") or "").strip()
    nm_id = str(order_row.get("nm_id") or "").strip()
    name_map = repo.get_product_name_by_article(user_id=user_id)
    photo_map = repo.get_product_photo_map(user_id=user_id)
    name = (
        name_map.get(article)
        or name_map.get(article.casefold())
        or name_map.get(nm_id)
        or name_map.get(nm_id.casefold())
        or ""
    )
    photo = photo_map.get(article) or photo_map.get(nm_id) or ""
    barcodes: list[str] = []
    try:
        parsed = json.loads(order_row.get("skus_json") or "[]")
        if isinstance(parsed, list):
            barcodes = [str(x).strip() for x in parsed if str(x or "").strip()]
    except Exception:
        pass
    catalog = _catalog_barcodes_index(repo, user_id=user_id)
    for p in repo.list_product_photos(user_id=user_id):
        if article and str(p.get("supplier_article") or "").strip() == article:
            for b in p.get("barcodes") or []:
                text = str(b or "").strip()
                if text and text not in barcodes:
                    barcodes.append(text)
            break
        if nm_id and str(p.get("wb_nmid") or "").strip() == nm_id:
            for b in p.get("barcodes") or []:
                text = str(b or "").strip()
                if text and text not in barcodes:
                    barcodes.append(text)
            break
    catalog_product = _catalog_product_for_order(
        repo, user_id=user_id, order_row=order_row
    )
    catalog_fields = _catalog_fields_from_product(catalog_product)
    return {
        "product_name": name,
        "product_article": article,
        "product_photo": photo,
        "product_barcodes": barcodes,
        **catalog_fields,
    }


def _product_from_gtin(
    repo: ReviewRepository,
    *,
    user_id: int,
    gtin14: str,
) -> dict[str, Any]:
    if not gtin14:
        return {}
    catalog = _catalog_barcodes_index(repo, user_id=user_id)
    p = catalog.get(gtin14) or catalog.get(gtin14.lstrip("0")) or catalog.get(_digits_only(gtin14))
    if not p:
        return {}
    pid = int(p.get("id") or 0)
    photo = f"/api/products/photo/{pid}" if pid and p.get("photo_path") else ""
    return {
        "product_name": str(p.get("name") or "").strip(),
        "product_article": str(p.get("supplier_article") or "").strip(),
        "product_photo": photo,
        "product_barcodes": list(p.get("barcodes") or []),
        **_catalog_fields_from_product(p),
    }


def _resolve_order_row(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
    api_key: str = "",
) -> dict[str, Any] | None:
    """Local order row, else same remote lookup as supplies search / kiz-restore."""
    row = kiz_restore.resolve_order_for_restore(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=int(order_id),
        api_key=api_key,
    )
    return row if row else None


def _kiz_codes_for_order(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
    api_key: str = "",
    order_row: dict[str, Any] | None = None,
    srid_hint: str = "",
) -> list[str]:
    return kiz_restore.load_kiz_for_order(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=int(order_id),
        api_key=api_key,
        order_row=order_row,
        srid_hint=srid_hint,
    )


def _return_scan_duplicate(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    return_sticker_id: str,
) -> dict[str, Any] | None:
    if not return_sticker_id:
        return None
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM wb_fbs_return_scans
                WHERE user_id = ? AND source_id = ?
                  AND scan_type = ?
                  AND return_sticker_id = ?
                ORDER BY scanned_at DESC
                LIMIT 1
                """
            ),
            (user_id, source_id, SCAN_RETURN, return_sticker_id),
        ).fetchone()
    return repo._row_to_dict(row) if row else None


def _insert_return_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    payload: dict[str, Any],
) -> dict[str, Any]:
    ensure_wb_fbs_returns_tables(repo)
    now = datetime.now(UTC).isoformat()
    with repo._connect() as conn:
        scan_id = repo._insert_and_get_id(
            conn,
            repo._sql(
                """
                INSERT INTO wb_fbs_return_scans (
                    user_id, source_id, scanned_at, scan_type, scan_raw,
                    return_sticker_id, order_id, assembly_sticker_barcode,
                    assembly_sticker_number, kiz_code, matched_order_ids_json,
                    product_name, product_article, product_photo,
                    product_barcodes_json, gtin14, duplicate_of_id
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """
            ),
            (
                user_id,
                source_id,
                now,
                str(payload.get("scan_type") or "").strip(),
                str(payload.get("scan_raw") or "").strip(),
                str(payload.get("return_sticker_id") or "").strip(),
                payload.get("order_id"),
                str(payload.get("assembly_sticker_barcode") or "").strip(),
                str(payload.get("assembly_sticker_number") or "").strip(),
                str(payload.get("kiz_code") or "").strip(),
                json.dumps(payload.get("matched_order_ids") or [], ensure_ascii=False),
                str(payload.get("product_name") or "").strip(),
                str(payload.get("product_article") or "").strip(),
                str(payload.get("product_photo") or "").strip(),
                json.dumps(payload.get("product_barcodes") or [], ensure_ascii=False),
                str(payload.get("gtin14") or "").strip(),
                payload.get("duplicate_of_id"),
            ),
        )
        row = conn.execute(
            repo._sql("SELECT * FROM wb_fbs_return_scans WHERE id = ?"),
            (scan_id,),
        ).fetchone()
    return _scan_row_to_api(repo._row_to_dict(row) if row else {})


def _enrich_return_scan_catalog_fields(
    repo: ReviewRepository,
    *,
    user_id: int,
    item: dict[str, Any],
    by_article: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    article = str(item.get("product_article") or "").strip()
    product: dict[str, Any] | None = None
    if article:
        if by_article is not None:
            product = by_article.get(article)
        else:
            for p in repo.list_product_photos(user_id=user_id):
                if str(p.get("supplier_article") or "").strip() == article:
                    product = p
                    break
    if product is None:
        gtin14 = str(item.get("gtin14") or "").strip()
        if gtin14:
            fields = _product_from_gtin(repo, user_id=user_id, gtin14=gtin14)
            item["catalog_barcodes"] = list(fields.get("catalog_barcodes") or [])
            item["barcode_label_name"] = str(fields.get("barcode_label_name") or "").strip()
            return item
    item.update(_catalog_fields_from_product(product))
    return item


def _catalog_by_article_index(
    repo: ReviewRepository,
    *,
    user_id: int,
) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for p in repo.list_product_photos(user_id=user_id):
        article = str(p.get("supplier_article") or "").strip()
        if article and article not in out:
            out[article] = p
    return out


def _return_scans_search_sql(search: str) -> tuple[str, list[Any]]:
    q = str(search or "").strip()
    if not q:
        return "", []
    pattern = f"%{q}%"
    clause = """(
        CAST(order_id AS TEXT) ILIKE ?
        OR return_sticker_id ILIKE ?
        OR assembly_sticker_barcode ILIKE ?
        OR assembly_sticker_number ILIKE ?
        OR kiz_code ILIKE ?
        OR scan_raw ILIKE ?
        OR product_name ILIKE ?
        OR product_article ILIKE ?
        OR product_barcodes_json ILIKE ?
        OR matched_order_ids_json ILIKE ?
    )"""
    return clause, [pattern] * 10


def _scan_row_to_api(row: dict[str, Any]) -> dict[str, Any]:
    if not row:
        return {}
    out = dict(row)
    try:
        out["matched_order_ids"] = json.loads(out.pop("matched_order_ids_json", "[]") or "[]")
    except Exception:
        out["matched_order_ids"] = []
    try:
        out["product_barcodes"] = json.loads(out.pop("product_barcodes_json", "[]") or "[]")
    except Exception:
        out["product_barcodes"] = []
    out.pop("product_barcodes_json", None)
    out.pop("matched_order_ids_json", None)
    return out


def process_return_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
) -> dict[str, Any]:
    """Classify scan, resolve order/product/KIZ, persist journal row."""
    scan_text = str(scan or "").strip()
    if not scan_text:
        return {"ok": False, "error": "empty_scan", "message": "Пустое сканирование"}

    if kiz_restore.looks_like_kiz_scan(scan_text):
        return _process_kiz_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
        )

    goods_hit = find_goods_return_by_scan(
        repo, user_id=user_id, source_id=source_id, scan=scan_text
    )
    if goods_hit:
        return _process_return_sticker_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
            goods_row=goods_hit,
        )

    sticker_hit = kiz_restore.find_orders_by_sticker_scan(
        repo, user_id=user_id, source_id=source_id, scan=scan_text
    )
    if sticker_hit.get("ambiguous"):
        ids = [
            int(r.get("order_id"))
            for r in (sticker_hit.get("matches") or [])
            if r.get("order_id") is not None
        ]
        return {
            "ok": False,
            "error": "ambiguous_sticker",
            "message": "Стикер совпадает у нескольких заказов",
            "order_ids": ids[:10],
        }
    if sticker_hit.get("row"):
        return _process_assembly_sticker_scan(
            repo,
            user_id=user_id,
            source_id=source_id,
            api_key=api_key,
            scan=scan_text,
            order_row=sticker_hit["row"],
        )

    return {
        "ok": False,
        "error": "not_found",
        "message": "Не удалось распознать скан. Синхронизируйте возвраты WB или проверьте сканирование.",
    }


def _process_return_sticker_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
    goods_row: dict[str, Any],
) -> dict[str, Any]:
    sticker_id = str(goods_row.get("sticker_id") or "").strip() or _digits_only(scan)
    dup = _return_scan_duplicate(
        repo, user_id=user_id, source_id=source_id, return_sticker_id=sticker_id
    )
    if dup:
        return {
            "ok": False,
            "error": "duplicate",
            "message": "Этот стикер возврата уже просканирован",
            "item": _scan_row_to_api(dup),
        }
    try:
        order_id = int(goods_row.get("wb_order_id") or 0)
    except (TypeError, ValueError):
        order_id = 0
    srid_hint = str(goods_row.get("srid") or "").strip()
    order_row = (
        _resolve_order_row(
            repo,
            user_id=user_id,
            source_id=source_id,
            order_id=order_id,
            api_key=api_key,
        )
        if order_id > 0
        else None
    )
    product = _product_from_order(repo, user_id=user_id, order_row=order_row)
    kiz_codes = (
        _kiz_codes_for_order(
            repo,
            user_id=user_id,
            source_id=source_id,
            order_id=order_id,
            api_key=api_key,
            order_row=order_row,
            srid_hint=srid_hint,
        )
        if order_id > 0
        else []
    )
    kiz_code = kiz_codes[0] if kiz_codes else ""
    assembly_number = ""
    assembly_barcode = ""
    if order_row:
        part_a = str(order_row.get("sticker_part_a") or "").strip()
        part_b = str(order_row.get("sticker_part_b") or "").strip()
        assembly_number = kiz_restore.sticker_number(part_a, part_b)
        assembly_barcode = str(order_row.get("sticker_barcode") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_RETURN,
            "scan_raw": scan,
            "return_sticker_id": sticker_id,
            "order_id": order_id if order_id > 0 else None,
            "assembly_sticker_barcode": assembly_barcode,
            "assembly_sticker_number": assembly_number,
            "kiz_code": kiz_code,
            "matched_order_ids": [order_id] if order_id > 0 else [],
            "gtin14": kiz_restore.extract_gtin14(kiz_code) if kiz_code else "",
            **product,
        },
    )
    if not kiz_code and order_id > 0:
        item["warning"] = (
            f"Для заказа {order_id} не найден КИЗ "
            "(маркировка, WB meta или «Вывод КИЗ»)"
        )
    return {"ok": True, "item": item}


def _process_assembly_sticker_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
    order_row: dict[str, Any],
) -> dict[str, Any]:
    try:
        order_id = int(order_row.get("order_id"))
    except (TypeError, ValueError, KeyError):
        return {"ok": False, "error": "not_found", "message": "Некорректный заказ"}
    resolved_order = _resolve_order_row(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=order_id,
        api_key=api_key,
    ) or order_row
    wb.persist_order_stickers_batch(
        repo,
        user_id=user_id,
        source_id=source_id,
        stickers={
            order_id: {
                "sticker_barcode": kiz_restore.normalize_sticker_scan(scan),
                "sticker_part_a": str(resolved_order.get("sticker_part_a") or "").strip(),
                "sticker_part_b": str(resolved_order.get("sticker_part_b") or "").strip(),
            }
        },
    )
    product = _product_from_order(repo, user_id=user_id, order_row=resolved_order)
    kiz_codes = _kiz_codes_for_order(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=order_id,
        api_key=api_key,
        order_row=resolved_order,
    )
    kiz_code = kiz_codes[0] if kiz_codes else ""
    part_a = str(resolved_order.get("sticker_part_a") or "").strip()
    part_b = str(resolved_order.get("sticker_part_b") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_ASSEMBLY,
            "scan_raw": scan,
            "order_id": order_id,
            "assembly_sticker_barcode": kiz_restore.normalize_sticker_scan(scan),
            "assembly_sticker_number": kiz_restore.sticker_number(part_a, part_b),
            "kiz_code": kiz_code,
            "matched_order_ids": [order_id],
            "gtin14": kiz_restore.extract_gtin14(kiz_code) if kiz_code else "",
            **product,
        },
    )
    return {"ok": True, "item": item}


def _process_kiz_scan(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    api_key: str,
    scan: str,
) -> dict[str, Any]:
    code = kiz_restore.normalize_kiz_mark(scan)
    gtin14 = kiz_restore.extract_gtin14(code)
    db_hit = kiz_restore.find_kiz_in_local_database(
        repo, user_id=user_id, source_id=source_id, kiz_code=code
    )
    matched_ids = [int(x) for x in (db_hit.get("order_ids") or [])]
    order_id: int | None = matched_ids[0] if len(matched_ids) == 1 else None
    order_row = (
        _resolve_order_row(
            repo,
            user_id=user_id,
            source_id=source_id,
            order_id=int(order_id),
            api_key=api_key,
        )
        if order_id
        else None
    )
    product = (
        _product_from_order(repo, user_id=user_id, order_row=order_row)
        if order_row
        else _product_from_gtin(repo, user_id=user_id, gtin14=gtin14)
    )
    gtin_warning = ""
    if gtin14:
        catalog = _catalog_barcodes_index(repo, user_id=user_id)
        gtin_digits = _digits_only(gtin14)
        in_catalog = (
            gtin14 in catalog
            or gtin14.lstrip("0") in catalog
            or gtin_digits in catalog
        )
        if not in_catalog:
            gtin_warning = "GTIN не найден в каталоге товаров"
    assembly_number = ""
    assembly_barcode = ""
    if order_row:
        part_a = str(order_row.get("sticker_part_a") or "").strip()
        part_b = str(order_row.get("sticker_part_b") or "").strip()
        assembly_number = kiz_restore.sticker_number(part_a, part_b)
        assembly_barcode = str(order_row.get("sticker_barcode") or "").strip()
    item = _insert_return_scan(
        repo,
        user_id=user_id,
        source_id=source_id,
        payload={
            "scan_type": SCAN_KIZ,
            "scan_raw": scan,
            "order_id": order_id,
            "assembly_sticker_barcode": assembly_barcode,
            "assembly_sticker_number": assembly_number,
            "kiz_code": code,
            "matched_order_ids": matched_ids,
            "gtin14": gtin14,
            **product,
        },
    )
    if len(matched_ids) > 1:
        item["warning"] = (
            f"КИЗ найден у заказов: {', '.join(str(x) for x in matched_ids[:5])}"
            f"{'…' if len(matched_ids) > 5 else ''}"
        )
    elif not db_hit.get("found"):
        item["warning"] = "КИЗ не найден в локальной базе заказов"
    if gtin_warning:
        item["warning"] = (
            f"{item['warning']} · {gtin_warning}"
            if item.get("warning")
            else gtin_warning
        )
    return {"ok": True, "item": item}


def get_return_scan_by_id(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    scan_id: int,
) -> dict[str, Any] | None:
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT * FROM wb_fbs_return_scans
                WHERE user_id = ? AND source_id = ? AND id = ?
                """
            ),
            (user_id, source_id, scan_id),
        ).fetchone()
    return _enrich_return_scan_catalog_fields(
        repo,
        user_id=user_id,
        item=_scan_row_to_api(repo._row_to_dict(row)) if row else {},
    ) if row else None


def list_return_scans(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    date_from: str = "",
    date_to: str = "",
    search: str = "",
    scan_types: list[str] | None = None,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    ensure_wb_fbs_returns_tables(repo)
    clauses = ["user_id = ?", "source_id = ?"]
    params: list[Any] = [user_id, source_id]
    df = _parse_iso_date(date_from)
    dt = _parse_iso_date(date_to)
    if df:
        clauses.append("scanned_at >= ?")
        params.append(f"{df}T00:00:00+00:00")
    if dt:
        clauses.append("scanned_at < ?")
        end = date.fromisoformat(dt) + timedelta(days=1)
        params.append(f"{end.isoformat()}T00:00:00+00:00")
    if scan_types:
        placeholders = ",".join("?" for _ in scan_types)
        clauses.append(f"scan_type IN ({placeholders})")
        params.extend(scan_types)
    search_clause, search_params = _return_scans_search_sql(search)
    if search_clause:
        clauses.append(search_clause)
        params.extend(search_params)
    page_limit = max(1, min(int(limit), 2000))
    page_offset = max(0, int(offset))
    fetch_limit = page_limit + 1
    sql = (
        "SELECT * FROM wb_fbs_return_scans WHERE "
        + " AND ".join(clauses)
        + " ORDER BY scanned_at DESC LIMIT ? OFFSET ?"
    )
    params.extend([fetch_limit, page_offset])
    with repo._connect() as conn:
        rows = conn.execute(repo._sql(sql), tuple(params)).fetchall()
    has_more = len(rows) > page_limit
    if has_more:
        rows = rows[:page_limit]
    items = [_scan_row_to_api(repo._row_to_dict(r)) for r in rows]
    by_article = _catalog_by_article_index(repo, user_id=user_id)
    for item in items:
        _enrich_return_scan_catalog_fields(
            repo,
            user_id=user_id,
            item=item,
            by_article=by_article,
        )
    return {"items": items, "has_more": has_more}


def _goods_return_srid_hint(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
) -> str:
    ensure_wb_fbs_returns_tables(repo)
    with repo._connect() as conn:
        row = conn.execute(
            repo._sql(
                """
                SELECT srid FROM wb_fbs_goods_returns
                WHERE user_id = ? AND source_id = ? AND wb_order_id = ?
                  AND srid <> ''
                ORDER BY synced_at DESC
                LIMIT 1
                """
            ),
            (user_id, source_id, int(order_id)),
        ).fetchone()
    if not row:
        return ""
    return str(repo._row_to_dict(row).get("srid") or "").strip()


def build_return_order_preview(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
    order_id: int,
    api_key: str = "",
) -> dict[str, Any]:
    """Virtual Returns row from order lookup — not saved to wb_fbs_return_scans."""
    oid = int(order_id)
    order_row = _resolve_order_row(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=oid,
        api_key=api_key,
    )
    if not order_row:
        return {
            "found": False,
            "order_id": oid,
            "item": None,
            "message": f"Заказ {oid} не найден в WB FBS",
        }
    product = _product_from_order(repo, user_id=user_id, order_row=order_row)
    srid_hint = _goods_return_srid_hint(
        repo, user_id=user_id, source_id=source_id, order_id=oid
    )
    kiz_codes = _kiz_codes_for_order(
        repo,
        user_id=user_id,
        source_id=source_id,
        order_id=oid,
        api_key=api_key,
        order_row=order_row,
        srid_hint=srid_hint,
    )
    kiz_code = kiz_codes[0] if kiz_codes else ""
    part_a = str(order_row.get("sticker_part_a") or "").strip()
    part_b = str(order_row.get("sticker_part_b") or "").strip()
    item = {
        "id": None,
        "preview": True,
        "scan_type": SCAN_LOOKUP,
        "scanned_at": "",
        "scan_raw": "",
        "return_sticker_id": "",
        "order_id": oid,
        "assembly_sticker_barcode": str(order_row.get("sticker_barcode") or "").strip(),
        "assembly_sticker_number": kiz_restore.sticker_number(part_a, part_b),
        "kiz_code": kiz_code,
        "matched_order_ids": [oid],
        "gtin14": kiz_restore.extract_gtin14(kiz_code) if kiz_code else "",
        **product,
    }
    out: dict[str, Any] = {
        "found": True,
        "order_id": oid,
        "item": item,
        "message": "",
    }
    if not kiz_code:
        out["warning"] = (
            f"Для заказа {oid} не найден КИЗ "
            "(маркировка, «Вывод КИЗ» или WB meta)"
        )
    return out


def render_kiz_print_png(kiz_code: str) -> str:
    return kiz_restore.kiz_datamatrix_png_base64(kiz_code)


def export_goods_returns_csv(rows: list[dict[str, Any]]) -> str:
    """CSV export of synced WB Analytics goods-return report rows."""
    buf = io.StringIO()
    writer = csv.writer(buf, delimiter=";")
    writer.writerow(
        [
            "Заказ (orderId)",
            "Стикер возврата (stickerId)",
            "Баркод товара (barcode)",
            "ШК (shkId)",
            "srid",
            "Артикул WB (nmId)",
            "Статус",
            "Причина",
            "Тип возврата",
            "Дата заказа",
            "Готов к выдаче",
            "Выдан",
            "Истекает",
            "ПВЗ",
            "Бренд",
            "Предмет",
            "Размер",
            "Активный статус",
            "Синхронизировано",
        ]
    )
    for row in rows:
        raw = _goods_return_raw_fields(row)
        writer.writerow(
            [
                str(row.get("wb_order_id") or ""),
                str(row.get("sticker_id") or ""),
                str(row.get("barcode") or ""),
                str(row.get("shk_id") or ""),
                str(row.get("srid") or ""),
                str(row.get("nm_id") or ""),
                str(row.get("status") or ""),
                str(row.get("reason") or ""),
                str(raw.get("returnType") or ""),
                str(row.get("order_dt") or raw.get("orderDt") or ""),
                str(row.get("ready_to_return_dt") or raw.get("readyToReturnDt") or ""),
                str(row.get("completed_dt") or raw.get("completedDt") or ""),
                str(raw.get("expiredDt") or ""),
                str(raw.get("dstOfficeAddress") or ""),
                str(raw.get("brand") or ""),
                str(raw.get("subjectName") or ""),
                str(raw.get("techSize") or ""),
                str(raw.get("isStatusActive") if raw.get("isStatusActive") is not None else ""),
                str(row.get("synced_at") or ""),
            ]
        )
    return "\ufeff" + buf.getvalue()


def export_return_scans_csv(items: list[dict[str, Any]]) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf, delimiter=";")
    writer.writerow(
        [
            "Дата",
            "Тип",
            "Заказ",
            "Стикер возврата",
            "Стикер заказа",
            "КИЗ",
            "Товар",
            "Артикул",
            "ШК",
        ]
    )
    for item in items:
        writer.writerow(
            [
                str(item.get("scanned_at") or ""),
                str(item.get("scan_type") or ""),
                str(item.get("order_id") or ""),
                str(item.get("return_sticker_id") or ""),
                str(item.get("assembly_sticker_number") or item.get("assembly_sticker_barcode") or ""),
                str(item.get("kiz_code") or ""),
                str(item.get("product_name") or ""),
                str(item.get("product_article") or ""),
                ", ".join(str(x) for x in (item.get("product_barcodes") or [])),
            ]
        )
    return "\ufeff" + buf.getvalue()


def default_sync_date_range(
    days: int = GOODS_RETURN_DEFAULT_TOTAL_DAYS,
) -> tuple[str, str]:
    end = date.today()
    start = end - timedelta(days=max(1, days) - 1)
    return start.isoformat(), end.isoformat()


def clamp_goods_return_sync_range(
    date_from: str,
    date_to: str,
    *,
    max_days: int = GOODS_RETURN_DEFAULT_TOTAL_DAYS,
) -> tuple[str, str, bool]:
    """Limit custom sync range to WB storage window (≤90 days). Returns (from, to, was_clamped)."""
    df = _parse_sync_date(_parse_iso_date(date_from))
    dt = _parse_sync_date(_parse_iso_date(date_to))
    if dt < df:
        df, dt = dt, df
    cap = max(1, int(max_days))
    span = (dt - df).days + 1
    if span <= cap:
        return df.isoformat(), dt.isoformat(), False
    df = dt - timedelta(days=cap - 1)
    return df.isoformat(), dt.isoformat(), True


def sync_goods_returns_default(
    repo: ReviewRepository,
    *,
    user_id: int,
    source_id: int,
) -> dict[str, Any]:
    src = repo.get_supply_source_with_key(user_id=user_id, source_id=source_id)
    source_api_key = str((src or {}).get("api_key") or "").strip() or None
    source_analytics_key = str((src or {}).get("analytics_api_key") or "").strip() or None
    fallback = get_wb_analytics_api_key(repo, user_id=user_id)
    try:
        candidates, trust_report = resolve_goods_return_api_keys(
            source_api_key=source_api_key,
            source_analytics_api_key=source_analytics_key,
            fallback_analytics_key=fallback,
        )
    except RuntimeError as exc:
        return {"ok": False, "error": "no_api_key", "message": str(exc)}
    api_key, api_key_source = candidates[0]
    date_from, date_to = default_sync_date_range(GOODS_RETURN_DEFAULT_TOTAL_DAYS)
    return sync_goods_returns(
        repo,
        user_id=user_id,
        source_id=source_id,
        api_key=api_key,
        date_from=date_from,
        date_to=date_to,
        marketplace_api_key=source_api_key,
        api_key_source=api_key_source,
        trust_report=trust_report,
        api_key_candidates=candidates,
    )
